export function Terms() {
  return (
    <div
      style={{
        minHeight: "100%",
        background: "#030308",
        color: "rgba(255,255,255,0.85)",
        fontFamily: "Inter, system-ui, sans-serif",
        padding: "32px 20px 64px",
        maxWidth: 680,
        margin: "0 auto",
        lineHeight: 1.7,
        fontSize: 14,
      }}
    >
      <a
        href="/"
        style={{
          display: "inline-block",
          marginBottom: 32,
          fontSize: 10,
          letterSpacing: "0.2em",
          color: "rgba(255,255,255,0.35)",
          textDecoration: "none",
          textTransform: "uppercase",
        }}
      >
        ← Back to A.v.A
      </a>

      <h1
        style={{
          fontSize: 24,
          fontWeight: 800,
          letterSpacing: "0.08em",
          textTransform: "uppercase",
          color: "#ff0055",
          marginBottom: 4,
        }}
      >
        Terms of Service
      </h1>
      <p style={{ fontSize: 11, color: "rgba(255,255,255,0.3)", marginBottom: 40, letterSpacing: "0.1em" }}>
        A.v.A — Anyone vs Anyone · Last updated: May 2026
      </p>

      <Section title="Acceptance of Terms">
        By accessing or using A.v.A ("the App"), you agree to be bound by these Terms of Service.
        If you do not agree, do not use the App. We may update these terms from time to time;
        continued use of the App after changes constitutes acceptance of the revised terms.
      </Section>

      <Section title="Eligibility">
        You must be at least 13 years old to use the App. The App contains stylized fantasy
        violence and, optionally, strong language; users who confirm they are 16 or older may
        see mature language in fight narratives. If you are under 18, you represent that a
        parent or guardian has reviewed and agreed to these terms on your behalf.
      </Section>

      <Section title="Your Account">
        Accounts are optional. If you create an account, you are responsible for maintaining the
        confidentiality of your sign-in credentials and for all activity under your account.
        Notify us immediately of any unauthorized use. We may suspend or terminate accounts
        that violate these terms, harass other users, attempt to abuse the service, or attempt
        to circumvent rate limits or moderation.
      </Section>

      <Section title="Acceptable Use">
        You agree not to:
        <ul style={{ paddingLeft: 20, margin: "8px 0 0" }}>
          <li>Use the App to harass, threaten, or defame any real person</li>
          <li>Attempt to reverse engineer, scrape, or overload the App or its API</li>
          <li>Submit character suggestions that contain hateful, sexual, or illegal content</li>
          <li>Submit content that infringes third-party intellectual property rights</li>
          <li>Use automated tools to inflate stats, leaderboards, or perfect-day streaks</li>
        </ul>
      </Section>

      <Section title="User-Submitted Content">
        When you submit a character suggestion or other content, you grant us a non-exclusive,
        worldwide, royalty-free license to use, display, and distribute that content within
        the App. You represent that you have the right to submit any content you upload. We
        may remove any submission at our discretion, with or without notice.
      </Section>

      <Section title="AI-Generated Content">
        Fight narratives are generated by third-party large language models (Anthropic / OpenAI)
        and are works of fiction for entertainment only. They do not reflect the views of A.v.A,
        the depicted characters' rights holders, or any real person. AI output may contain
        inaccuracies, anachronisms, or unexpected creative choices. You may not republish
        AI-generated narratives commercially without our written permission.
      </Section>

      <Section title="Intellectual Property">
        Character names, likenesses, and franchise references appearing in the App are the
        property of their respective rights holders and are used for purposes of fan commentary,
        criticism, and parody under applicable fair use / fair dealing principles. A.v.A
        claims no ownership of these third-party properties. If you are a rights holder and
        wish to request removal of a character, contact us at the address below.
        <br /><br />
        All original App code, branding, and design are the property of A.v.A and may not
        be copied or redistributed without permission.
      </Section>

      <Section title="Disclaimers">
        The App is provided <strong style={{ color: "#fff" }}>"as is"</strong> without warranties
        of any kind, express or implied. We do not warrant that the App will be uninterrupted,
        error-free, or free of harmful components. Fight outcomes are AI-generated entertainment
        and have no real-world predictive value.
      </Section>

      <Section title="Limitation of Liability">
        To the maximum extent permitted by law, A.v.A and its operators are not liable for any
        indirect, incidental, special, consequential, or punitive damages arising from your use
        of the App. Our total liability for any claim arising out of these terms will not
        exceed five US dollars (USD $5.00).
      </Section>

      <Section title="Termination">
        We may suspend or terminate your access to the App at any time, with or without notice,
        for any reason — including violation of these terms. You may stop using the App at any
        time and delete your account from the Profile page.
      </Section>

      <Section title="Governing Law">
        These terms are governed by the laws of the United States and the State of California,
        without regard to conflict-of-law principles. Any dispute arising from these terms
        will be resolved in the courts located in California.
      </Section>

      <Section title="Contact">
        For questions about these terms:
        <br /><br />
        <span style={{ color: "#00f0ff" }}>furoys@gmail.com</span>
      </Section>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 32 }}>
      <h2
        style={{
          fontSize: 11,
          fontWeight: 800,
          letterSpacing: "0.25em",
          textTransform: "uppercase",
          color: "#ff0055",
          marginBottom: 10,
          paddingBottom: 6,
          borderBottom: "1px solid rgba(255,0,85,0.2)",
        }}
      >
        {title}
      </h2>
      <div style={{ color: "rgba(255,255,255,0.7)" }}>{children}</div>
    </div>
  );
}
