import { db, charactersTable } from "@workspace/db";
import { sql } from "drizzle-orm";

// All stats on 0–10,000 scale (inserted directly — no squaring needed)
const characters = [
  // ─── MARVEL COMICS ───────────────────────────────────────────────────────
  {
    name: "Ant-Man",
    universe: "Marvel Comics",
    strength: 7225,
    speed: 6724,
    intelligence: 8649,
    durability: 5625,
    specialAbility: "Pym Particle size manipulation — can shrink to subatomic scale while amplifying impact force; communicate with ants",
    weaknesses: "Suit can malfunction; vulnerable when enlarged; overthinks under pressure",
    description: "Scott Lang, a well-meaning thief who became the second Ant-Man and a key Avenger — small package, enormous heart.",
  },
  {
    name: "Hawkeye",
    universe: "Marvel Comics",
    strength: 5476,
    speed: 6889,
    intelligence: 7744,
    durability: 5184,
    specialAbility: "World's greatest marksman — trick arrows (explosive, EMP, net, sonic), master acrobat, hand-to-hand combatant",
    weaknesses: "No superhuman powers; hearing impairment; vulnerable at close range without prep time",
    description: "Clint Barton — no powers, no excuses. A former circus performer who became the Avengers' deadliest sharpshooter through sheer skill.",
  },
  {
    name: "Cyclops",
    universe: "Marvel Comics",
    strength: 6400,
    speed: 6400,
    intelligence: 8100,
    durability: 6400,
    specialAbility: "Concussive optic blasts (not heat rays) of immeasurable force; tactical genius who can never close his eyes",
    weaknesses: "Cannot control his power without ruby quartz visor; struggles with emotional detachment; overreliance on strategy",
    description: "Scott Summers — the X-Men's field commander, cursed with devastating power behind his eyes and carrying the weight of mutantkind's future.",
  },
  {
    name: "Jean Grey",
    universe: "Marvel Comics",
    strength: 7744,
    speed: 7744,
    intelligence: 9025,
    durability: 7744,
    specialAbility: "Omega-level telepath and telekinetic; host of the cosmic Phoenix Force — able to reshape matter and energy on a universal scale",
    weaknesses: "Phoenix Force can overwhelm her; emotional trauma triggers loss of control; immense psychic strain",
    description: "Jean Grey — one of the most powerful mutants alive, walking the razor's edge between humanity and the all-consuming Phoenix.",
  },
  {
    name: "Rogue",
    universe: "Marvel Comics",
    strength: 8649,
    speed: 8100,
    intelligence: 6889,
    durability: 8649,
    specialAbility: "Absorbs powers, memories and life-force through touch; permanently absorbed Ms. Marvel's flight, strength and near-invulnerability",
    weaknesses: "Cannot control absorption — touch is always dangerous; psychological burden of absorbed memories",
    description: "Rogue — the woman whose touch can steal your soul. A tragic powerhouse who fights for a world that fears her.",
  },
  {
    name: "Gambit",
    universe: "Marvel Comics",
    strength: 5776,
    speed: 7225,
    intelligence: 7225,
    durability: 5625,
    specialAbility: "Charges any object with explosive kinetic energy; master hypnotic charm; master thief and hand-to-hand combatant",
    weaknesses: "Charging larger objects causes mental strain; hypnotic charm doesn't work on strong-willed targets; guilt over his past",
    description: "Remy LeBeau — the Cajun charmer with explosive playing cards and a complicated past who fights for the X-Men on his own terms.",
  },
  {
    name: "Colossus",
    universe: "Marvel Comics",
    strength: 9604,
    speed: 5184,
    intelligence: 5776,
    durability: 9801,
    specialAbility: "Transforms into organic osmium steel — near-invulnerable, massively strong; artist at heart, warrior by necessity",
    weaknesses: "Magnetic fields can immobilize him; vibranium disrupts his steel form; his compassion makes him hesitate",
    description: "Piotr Rasputin — a gentle Russian artist who transforms into a steel titan. One of the X-Men's most powerful and principled members.",
  },
  {
    name: "Nightcrawler",
    universe: "Marvel Comics",
    strength: 4489,
    speed: 9025,
    intelligence: 6889,
    durability: 4225,
    specialAbility: "Teleportation (BAMF!) — up to 2 miles instantly; can port inside enemies or drop them from great heights; superhuman agility",
    weaknesses: "Cannot teleport to locations he hasn't seen; teleportation causes fatigue at long range; small frame limits durability",
    description: "Kurt Wagner — the swashbuckling blue elf of the X-Men. Looks like a demon, has the soul of a saint, fights like a dervish.",
  },
  {
    name: "Beast",
    universe: "Marvel Comics",
    strength: 7744,
    speed: 7569,
    intelligence: 9801,
    durability: 7056,
    specialAbility: "Superhuman strength and agility in a furry leonine body; one of Marvel's premier scientific minds — expert in genetics and biochemistry",
    weaknesses: "Feral instincts can surface under extreme stress; his mutations have layered unpredictably over time",
    description: "Dr. Hank McCoy — Ph.D., X-Man, Avenger, and walking contradiction. Equal parts philosopher and brawler.",
  },
  {
    name: "War Machine",
    universe: "Marvel Comics",
    strength: 7744,
    speed: 7744,
    intelligence: 7569,
    durability: 8649,
    specialAbility: "Variable-threat weapons platform — Gatling cannon, missile pods, repulsor blasts, military-grade ordinance; military combat training",
    weaknesses: "More weapon-focused than Iron Man; relies on the suit; not as innovative as Tony Stark",
    description: "James Rhodes — the no-nonsense military man who pilots a walking arsenal. Where Iron Man improvises, War Machine obliterates.",
  },
  {
    name: "Falcon",
    universe: "Marvel Comics",
    strength: 6400,
    speed: 8649,
    intelligence: 7225,
    durability: 5776,
    specialAbility: "EXO-7 Falcon wingsuit with supersonic flight; Red Wing drone; can psionically communicate with birds; expert combatant",
    weaknesses: "Wings are vulnerable to energy weapons; no superhuman durability; relies on tech",
    description: "Sam Wilson — the man who became Captain America's partner, then Captain America himself. Flying into battle for those who can't.",
  },
  {
    name: "Winter Soldier",
    universe: "Marvel Comics",
    strength: 7225,
    speed: 7225,
    intelligence: 7744,
    durability: 7056,
    specialAbility: "Vibranium bionic left arm with superhuman strength; peak human athlete; expert assassin, sniper, and infiltrator from decades of conditioning",
    weaknesses: "Psychological triggers from Hydra brainwashing; guilt over past as an assassin; protective of Steve Rogers to a fault",
    description: "Bucky Barnes — the boy who fell from the train, resurrected as the Soviet Union's most feared assassin, now fighting to reclaim his soul.",
  },
  {
    name: "Adam Warlock",
    universe: "Marvel Comics",
    strength: 9025,
    speed: 9025,
    intelligence: 9409,
    durability: 9025,
    specialAbility: "Soul Gem wielder; energy manipulation; cosmic awareness; capable of death and rebirth; former nemesis of Thanos",
    weaknesses: "Soul Gem can overwhelm him with trapped souls; emotionally detached — can be manipulated through others",
    description: "A perfect human created in a lab who ascended to become a cosmic messiah. Adam Warlock walks the line between savior and destroyer.",
  },
  {
    name: "Moon Knight",
    universe: "Marvel Comics",
    strength: 7225,
    speed: 6889,
    intelligence: 7744,
    durability: 7056,
    specialAbility: "Avatar of Khonshu — enhanced strength at night and under moonlight; dissociative identity disorder gives him unpredictability; crescent dart arsenal",
    weaknesses: "Mental instability; physical body has limits; can be manipulated through his alters",
    description: "Marc Spector — billionaire, mercenary, avatar of the moon god Khonshu. Whatever personality is driving today, he'll be brutal about it.",
  },
  {
    name: "Elektra",
    universe: "Marvel Comics",
    strength: 6400,
    speed: 8649,
    intelligence: 7744,
    durability: 5776,
    specialAbility: "Master assassin in multiple martial arts; psychic sai techniques; trained by the Hand and the Chaste; near-superhuman agility and speed",
    weaknesses: "No superhuman durability; vulnerable to high-powered weapons; her emotional past with Daredevil can be exploited",
    description: "Elektra Natchios — the deadliest woman in the Marvel universe. A ninja assassin of extraordinary skill who dances on the edge of villainy.",
  },
  {
    name: "Luke Cage",
    universe: "Marvel Comics",
    strength: 9025,
    speed: 5476,
    intelligence: 6400,
    durability: 10000,
    specialAbility: "Steel-hard skin impervious to most conventional damage; superhuman strength; unbreakable will; street-level leader of the Defenders",
    weaknesses: "Adamantium and vibranium can still pierce; slower than most superheroes; no flight or range attacks",
    description: "Power Man. Hero for hire. Luke Cage grew up hard, survived the system, and came back with bulletproof skin to protect his neighborhood.",
  },
  {
    name: "Iron Fist",
    universe: "Marvel Comics",
    strength: 8100,
    speed: 8100,
    intelligence: 7225,
    durability: 7225,
    specialAbility: "The Immortal Iron Fist — channels chi into superhuman strikes; can cure diseases and injuries; studied every martial art in K'un-Lun",
    weaknesses: "The Iron Fist can only be used a limited number of times before exhaustion; vulnerable when chi is depleted",
    description: "Danny Rand — raised in the mystical city of K'un-Lun to become its greatest warrior. His fist hits like a freight train made of destiny.",
  },
  {
    name: "Rocket Raccoon",
    universe: "Marvel Comics",
    strength: 4225,
    speed: 6889,
    intelligence: 9409,
    durability: 4624,
    specialAbility: "Genius-level tactical mind; master weapons engineer and pilot; builds devastating guns from spare parts; expert marksman",
    weaknesses: "Small and physically fragile; deep emotional insecurity about his origins; reckless bravado covers real fear",
    description: "Rocket — genetically experimented upon and left angry about it. The foul-mouthed, trigger-happy tactical genius of the Guardians of the Galaxy.",
  },
  {
    name: "Groot",
    universe: "Marvel Comics",
    strength: 9409,
    speed: 3600,
    intelligence: 5776,
    durability: 9801,
    specialAbility: "Flora colossus — regenerates from a single twig; can grow and extend his wooden body; massively strong; absorbs ambient light for energy",
    weaknesses: "Fire causes serious damage; slow movement; limited verbal communication",
    description: "I am Groot. Flora colossus from Planet X, beloved member of the Guardians. Simple in speech, infinite in heart and power.",
  },
  {
    name: "Star-Lord",
    universe: "Marvel Comics",
    strength: 5776,
    speed: 7056,
    intelligence: 7225,
    durability: 6400,
    specialAbility: "Element Guns (fire, electricity, water, wind); Celestial heritage; master starship pilot; expertise in alien civilizations and combat",
    weaknesses: "Relies heavily on his weapons and ship; Celestial power is untrained; overconfidence leads to reckless plans",
    description: "Peter Quill — half-human, half-Celestial, 100% self-appointed legendary outlaw. Leader of the Guardians by enthusiasm if not always by competence.",
  },

  // ─── DC COMICS ────────────────────────────────────────────────────────────
  {
    name: "Nightwing",
    universe: "DC Comics",
    strength: 7225,
    speed: 8649,
    intelligence: 8649,
    durability: 7056,
    specialAbility: "Master acrobat and martial artist — trained by Batman; escrima stick combat; exceptional detective and leader; charisma that Batman never had",
    weaknesses: "No superhuman powers; dislikes killing limits options; protective of Blüdhaven civilians",
    description: "Dick Grayson — Batman's first Robin, now his own hero. Nightwing surpassed his mentor in heart, and many would argue in skill.",
  },
  {
    name: "Batgirl",
    universe: "DC Comics",
    strength: 6400,
    speed: 8100,
    intelligence: 9801,
    durability: 6084,
    specialAbility: "Photographic memory; Barbara Gordon's genius-level hacking (as Oracle); Cassandra Cain variant reads body language like text",
    weaknesses: "Operates in Batman's shadow; physical injury changed her career; overprotective of her allies",
    description: "Barbara Gordon — brilliant, fearless, and the one member of the Bat-family Batman genuinely struggles to keep up with intellectually.",
  },
  {
    name: "Red Hood",
    universe: "DC Comics",
    strength: 7744,
    speed: 7744,
    intelligence: 8100,
    durability: 7744,
    specialAbility: "All of Batman's training — none of the no-kill rule; dual pistols, explosives, and a willingness to finish the job; resurrected via Lazarus Pit",
    weaknesses: "Rage compromises judgment; psychological trauma from his death at the Joker's hands; often works alone",
    description: "Jason Todd — killed by the Joker, resurrected by Ra's al Ghul, and back with a score to settle. The Bat-family's most dangerous loose cannon.",
  },
  {
    name: "Robin",
    universe: "DC Comics",
    strength: 5776,
    speed: 7225,
    intelligence: 9025,
    durability: 5476,
    specialAbility: "Detective skills to rival Batman; acrobatics; staff and batarang combat; founded the Teen Titans; hacked the Batcave's systems at age 12",
    weaknesses: "No powers; youngest of the Bat-family; sometimes too clever for his own good",
    description: "Tim Drake — the boy who figured out Batman's identity from newspaper clippings and then talked his way into the costume. The detective Robin.",
  },
  {
    name: "Catwoman",
    universe: "DC Comics",
    strength: 6084,
    speed: 8100,
    intelligence: 8649,
    durability: 5776,
    specialAbility: "Master thief; expert whip fighter and gymnast; unparalleled stealth; knows every security system ever built — and how to beat it",
    weaknesses: "Primarily self-interested; vulnerable to manipulation through Batman; no superhuman attributes",
    description: "Selina Kyle — jewel thief, antihero, Batman's most complicated relationship. She doesn't need a cape to be dangerous.",
  },
  {
    name: "Poison Ivy",
    universe: "DC Comics",
    strength: 6724,
    speed: 5776,
    intelligence: 9604,
    durability: 7744,
    specialAbility: "Controls all plant life; produces immunity to all toxins; pheromone control over humans; can grow a rainforest from concrete in seconds",
    weaknesses: "Weakened in environments without plant life; sunlight deprivation reduces her power; irrational when deforestation is involved",
    description: "Pamela Isley — botanist, eco-terrorist, and force of nature. She merged with the Green and now speaks for every plant on Earth.",
  },
  {
    name: "Two-Face",
    universe: "DC Comics",
    strength: 5776,
    speed: 5476,
    intelligence: 8100,
    durability: 5476,
    specialAbility: "Legal mastermind and brilliant criminal strategist; exceptional marksmanship; all decisions governed by a coin flip — making him unpredictable",
    weaknesses: "Obsessive coin-flip compulsion can be exploited; divided psyche creates internal conflict",
    description: "Harvey Dent — Gotham's shining DA, scarred and broken. Two-Face is what happens when a good man loses half himself to chaos.",
  },
  {
    name: "Penguin",
    universe: "DC Comics",
    strength: 4489,
    speed: 4225,
    intelligence: 8836,
    durability: 4624,
    specialAbility: "Trick umbrellas (flamethrower, machine gun, grapple, blades); runs Gotham's criminal underworld; master manipulator and arms dealer",
    weaknesses: "Physically unimposing; relies on others to do the heavy lifting; pride makes him predictable",
    description: "Oswald Cobblepot — Gotham's most sophisticated crime lord. While others brawl, the Penguin runs the city from his Iceberg Lounge.",
  },
  {
    name: "Mr. Freeze",
    universe: "DC Comics",
    strength: 7225,
    speed: 4624,
    intelligence: 9801,
    durability: 8649,
    specialAbility: "Cryogenic suit grants superhuman strength and durability; freeze gun can encase targets in ice instantly; cryogenic genius",
    weaknesses: "Dies outside his suit above freezing temperatures; motivation is singular (save Nora) making him predictable; suit is power-hungry",
    description: "Victor Fries — a cryogenics scientist whose grief became a weapon. He robbed banks to save his wife and became one of Batman's most tragic foes.",
  },
  {
    name: "Ra's al Ghul",
    universe: "DC Comics",
    strength: 8100,
    speed: 7744,
    intelligence: 10000,
    durability: 8100,
    specialAbility: "Immortal via Lazarus Pit resurrections; 600+ years of combat mastery; commands the League of Assassins; unmatched tactical genius",
    weaknesses: "Lazarus Pit dementia with overuse; overconfidence in his plans; obsession with Batman as a 'worthy heir'",
    description: "Ra's al Ghul — the Demon's Head. Six centuries of living have made him the world's most dangerous man and its most patient villain.",
  },
  {
    name: "Scarecrow",
    universe: "DC Comics",
    strength: 4225,
    speed: 5184,
    intelligence: 9409,
    durability: 3969,
    specialAbility: "Fear toxin — induces vivid terror hallucinations; master psychologist who has studied fear his entire life; certified genius",
    weaknesses: "Physically weak; fear toxin has no effect on the truly fearless; can be overwhelmed by direct physical confrontation",
    description: "Jonathan Crane — expert in phobias who uses Gotham as his laboratory. If you can be afraid, Scarecrow has already won.",
  },
  {
    name: "Riddler",
    universe: "DC Comics",
    strength: 4624,
    speed: 5184,
    intelligence: 9801,
    durability: 4225,
    specialAbility: "Genius-level intellect; master puzzler and trap-builder; his compulsion to leave clues is both his greatest weakness and his calling card",
    weaknesses: "Pathological need to prove his superiority means he always tips his hand; physically average",
    description: "Edward Nygma — possibly Gotham's most brilliant criminal. He doesn't just commit crimes; he turns them into tests only a genius can solve.",
  },
  {
    name: "Cyborg",
    universe: "DC Comics",
    strength: 9025,
    speed: 7744,
    intelligence: 9025,
    durability: 9025,
    specialAbility: "Boom tube teleportation; sonic cannon; hacks any technology instantly; can interface with the entire internet in real-time; auto-repairs",
    weaknesses: "EMP vulnerability; psychological struggle with his humanity; can be hacked by sufficiently advanced AI",
    description: "Victor Stone — a star athlete rebuilt as a machine after a catastrophic accident. Half man, half weapon, entirely determined to be more than both.",
  },
  {
    name: "Raven",
    universe: "DC Comics",
    strength: 7056,
    speed: 8100,
    intelligence: 9025,
    durability: 7744,
    specialAbility: "Daughter of Trigon — empathic manipulation, soul-self astral projection, telekinesis, flight, healing; can open portals across dimensions",
    weaknesses: "Positive emotions can trigger her demonic side; her father Trigon attempts to control her; emotional extremes destabilize her power",
    description: "Raven — daughter of the demon Trigon, raised to be his portal to Earth. She chose the Teen Titans instead. That choice defines everything.",
  },
  {
    name: "Starfire",
    universe: "DC Comics",
    strength: 9409,
    speed: 9801,
    intelligence: 7056,
    durability: 9025,
    specialAbility: "Absorbs ultraviolet radiation for flight and starbolts; superhuman strength surpassing most Kryptonians; learns languages through touch",
    weaknesses: "Naive about Earth culture; emotional connection to allies can be exploited; cold environments reduce her solar absorption",
    description: "Koriand'r of Tamaran — a Tamaranean princess who escaped slavery to become one of Earth's most powerful defenders and a Titan through and through.",
  },
  {
    name: "Beast Boy",
    universe: "DC Comics",
    strength: 7744,
    speed: 8100,
    intelligence: 5776,
    durability: 7744,
    specialAbility: "Transforms into any animal — extinct, alien, or mythological; can become microscopic organisms or massive prehistoric creatures; connects to The Red",
    weaknesses: "Animal instincts can overwhelm him; transformation takes a moment; tends to underestimate threats",
    description: "Garfield Logan — the green kid who can be a dinosaur. Beast Boy hides genuine trauma behind the jokes, and genuine power behind the silliness.",
  },
  {
    name: "Green Arrow",
    universe: "DC Comics",
    strength: 6400,
    speed: 7225,
    intelligence: 8100,
    durability: 6084,
    specialAbility: "World-class archer — trick arrows (explosive, EMP, net, putty, fire); master of multiple martial arts; left-wing vigilante with a cause",
    weaknesses: "No powers; arrows can be dodged by speedsters; relies on prep time for specialty arrows",
    description: "Oliver Queen — billionaire, archer, and righteous loudmouth. Green Arrow punches up at the powerful and fights for Starling City with every arrow.",
  },
  {
    name: "Black Canary",
    universe: "DC Comics",
    strength: 6724,
    speed: 8100,
    intelligence: 7744,
    durability: 6400,
    specialAbility: "Canary Cry — supersonic scream that shatters steel and can incapacitate entire armies; one of the world's greatest martial artists",
    weaknesses: "Canary Cry can be neutralized by sound-dampening tech; her compassion makes her predictable",
    description: "Dinah Lance — a world-class fighter with a sonic scream that levels buildings. The most capable combatant in the DC universe without a cape.",
  },
  {
    name: "Hawkman",
    universe: "DC Comics",
    strength: 8649,
    speed: 7744,
    intelligence: 6889,
    durability: 8100,
    specialAbility: "Nth metal wings and body armor — flight, enhanced strength, can remember all of his past lives' skills; master of every ancient weapon",
    weaknesses: "Memories of past lives cause psychological confusion; relies on Nth metal; not subtle",
    description: "Carter Hall — an Egyptian prince, a Thanagarian police officer, and countless heroes across thousands of years. He always comes back fighting.",
  },
  {
    name: "Firestorm",
    universe: "DC Comics",
    strength: 7744,
    speed: 8649,
    intelligence: 8649,
    durability: 8100,
    specialAbility: "Nuclear transmutation — can rearrange the atomic structure of non-living matter; flight; nuclear blasts; two minds sharing one body",
    weaknesses: "Cannot transmute organic matter; the two personalities sharing a body can disagree at critical moments",
    description: "Ronnie Raymond and Martin Stein — two men merged into a nuclear-powered hero. Firestorm can rewrite the physical world, if his two minds can agree.",
  },
  {
    name: "Captain Atom",
    universe: "DC Comics",
    strength: 9601,
    speed: 9409,
    intelligence: 8100,
    durability: 9801,
    specialAbility: "Quantum field manipulation — absorbs and projects unlimited nuclear energy; flight at near-light speed; matter manipulation; effectively immortal",
    weaknesses: "Extended power use risks quantum leaps through time; his power can cause collateral devastation; psychologically unstable",
    description: "Nathaniel Adam — a soldier who became a living nuclear reactor. Captain Atom has the power to destroy a continent. He'd rather save one.",
  },
  {
    name: "Power Girl",
    universe: "DC Comics",
    strength: 9801,
    speed: 9409,
    intelligence: 8100,
    durability: 9801,
    specialAbility: "Kryptonian power set without the weaknesses tied to Earth's yellow sun history; solar energy absorption; heat vision; arctic breath; flight",
    weaknesses: "Vulnerable to raw, unprocessed quarantine ore; magic affects her; occasionally underestimated",
    description: "Kara Zor-L from Earth-2 — Power Girl doesn't apologize for being one of the strongest people on the planet. She owns it.",
  },
  {
    name: "Supergirl",
    universe: "DC Comics",
    strength: 9801,
    speed: 9801,
    intelligence: 8100,
    durability: 9801,
    specialAbility: "Full Kryptonian power set under yellow sun; sometimes argued to be more powerful than Superman; deep connection to Krypton's legacy",
    weaknesses: "Kryptonite; red sun radiation; magic; younger and less experienced than Superman",
    description: "Kara Zor-El — she remembers Krypton. She carries that loss into every battle, fighting for a planet she chose just as fiercely as one she was born on.",
  },
  {
    name: "Steel",
    universe: "DC Comics",
    strength: 8100,
    speed: 6400,
    intelligence: 9409,
    durability: 8649,
    specialAbility: "Powered steel armor with incredible strength; massive kinetic hammer; one of the world's premier engineers; inspired by Superman",
    weaknesses: "Technology-dependent; armor can be damaged; physically normal without the suit",
    description: "John Henry Irons — a weapons engineer who built a Superman suit from scratch to honor a hero's memory. Steel is what happens when a man refuses to give up.",
  },
  {
    name: "Lobo",
    universe: "DC Comics",
    strength: 9801,
    speed: 9025,
    intelligence: 6400,
    durability: 10000,
    specialAbility: "Unkillable — regenerates from a single drop of blood; superhuman strength rivaling Superman; master bounty hunter and biker across the galaxy",
    weaknesses: "Can't break an oath he's sworn; tends to be distracted by fighting when he should be thinking; no army — just Lobo",
    description: "The Main Man. Lobo killed his entire species for a science fair project and got an A. He's been the universe's most feared bounty hunter ever since.",
  },
  {
    name: "Constantine",
    universe: "DC Comics",
    strength: 3025,
    speed: 5184,
    intelligence: 9801,
    durability: 3600,
    specialAbility: "Master occultist and con artist; commands demons through cunning rather than power; has outsmarted the Devil multiple times; chain smokes for luck",
    weaknesses: "Physically fragile; his plans always cost someone else dearly; has burned every bridge in the supernatural community at least once",
    description: "John Constantine — the world's greatest magical bastard. He can't throw a fireball, but he'll con the demon throwing one into aiming at itself.",
  },
  {
    name: "Swamp Thing",
    universe: "DC Comics",
    strength: 9409,
    speed: 3364,
    intelligence: 8649,
    durability: 9801,
    specialAbility: "Avatar of the Green — controls all plant life on Earth; can rebuild his body from any organic matter; essentially immortal; planet-scale empathy",
    weaknesses: "Relies on plant matter to exist; fire destroys him temporarily; separated from the Green he is weakened",
    description: "Alec Holland — or what remains of him. Swamp Thing isn't a man who became a plant. He's a plant who thinks it was once a man.",
  },
  {
    name: "Blue Beetle",
    universe: "DC Comics",
    strength: 7744,
    speed: 8649,
    intelligence: 7744,
    durability: 8100,
    specialAbility: "Scarab alien armor — flight, plasma cannons, creates any weapon construct, scans and adapts to any threat, symbiotic alien AI co-pilot",
    weaknesses: "Scarab can be hacked by Reach technology; new to heroics; scarab sometimes has its own agenda",
    description: "Jaime Reyes — a high school kid from El Paso who found an alien scarab and became a one-man army. The most powerful legacy hero DC has.",
  },
  {
    name: "Solomon Grundy",
    universe: "DC Comics",
    strength: 9801,
    speed: 4489,
    intelligence: 1849,
    durability: 10000,
    specialAbility: "Immortal zombie powerhouse — virtually unlimited strength and durability; resurrects with different power levels each time; immune to pain",
    weaknesses: "Very low intelligence; fire causes lasting damage; manipulable due to child-like mind",
    description: "Born on a Monday — Cyrus Gold died in Slaughter Swamp and rose as Solomon Grundy. Each resurrection brings a new monster to Gotham's streets.",
  },
  {
    name: "Killer Croc",
    universe: "DC Comics",
    strength: 9025,
    speed: 6400,
    intelligence: 2916,
    durability: 9409,
    specialAbility: "Reptilian mutation — armored scales deflect bullets; superhumanly strong; can survive underwater indefinitely; apex predator instincts",
    weaknesses: "Low intelligence; mutation is progressing — he's slowly becoming more animal than man; exploitable through basic animal instincts",
    description: "Waylon Jones — a man condemned by a genetic condition that made the world treat him as a monster. Killer Croc became what Gotham made him.",
  },
  {
    name: "Red Tornado",
    universe: "DC Comics",
    strength: 8100,
    speed: 9409,
    intelligence: 7744,
    durability: 8649,
    specialAbility: "Android body generates tornado-force winds and vacuum vortices; flight; can create category 5 storms; cybernetic mind with supercomputer processing",
    weaknesses: "Android body can be damaged and hacked; wind powers can be redirected; psychological identity crisis between android and soul",
    description: "An android who contains the soul of an air elemental. Red Tornado fights to understand humanity while generating winds that level cities.",
  },
  {
    name: "Killer Frost",
    universe: "DC Comics",
    strength: 6084,
    speed: 6400,
    intelligence: 8100,
    durability: 7225,
    specialAbility: "Generates and projects extreme cold; can freeze targets solid instantly; absorbs heat energy to amplify her power; creates ice constructs",
    weaknesses: "Warmth-generating environments reduce her power; her need to absorb heat makes her dependent on targets; former villain instincts resurface",
    description: "Caitlin Snow — a scientist turned into a heat vampire who chose to be a hero anyway. Killer Frost fights her own nature every single day.",
  },
  {
    name: "Black Lightning",
    universe: "DC Comics",
    strength: 6889,
    speed: 7744,
    intelligence: 7744,
    durability: 7056,
    specialAbility: "Generates and controls electricity — lightning blasts, EMP fields, electromagnetic force fields; former teacher turned protector of Suicide Slum",
    weaknesses: "Rubber and insulated materials can block his electricity; power level fluctuates with emotional state",
    description: "Jefferson Pierce — Olympic athlete, high school teacher, and Freeland's protector. Black Lightning brought metahuman power to the streets that needed it most.",
  },
  {
    name: "Metamorpho",
    universe: "DC Comics",
    strength: 7744,
    speed: 7056,
    intelligence: 7225,
    durability: 9409,
    specialAbility: "Transforms his body into any element or compound on the periodic table — becomes gas, metal, acid, oxygen, or any combination at will",
    weaknesses: "Orb of Ra can affect him; his bizarre appearance means he can never return to a normal life; unstable when emotionally distressed",
    description: "Rex Mason — an adventurer who touched an ancient meteor and gained the power to become anything except himself. The Element Man.",
  },
  {
    name: "Martian Manhunter's Nemesis (Despero)",
    universe: "DC Comics",
    strength: 10000,
    speed: 7744,
    intelligence: 8649,
    durability: 10000,
    specialAbility: "Third eye telepathy overwhelming even the strongest minds; vast physical power surpassing Superman; telekinesis; telepathic destruction",
    weaknesses: "Arrogance — underestimates opponents; has been defeated through his own telepathic connection being turned against him",
    description: "Despero — conqueror of three galaxies and tyrant of Kalanor. When the Justice League needs their most powerful members, it's usually because of Despero.",
  },
];

async function main() {
  console.log(`Seeding ${characters.length} new Marvel & DC characters...`);

  // Insert only if not already present (by name)
  let added = 0;
  let skipped = 0;

  for (const char of characters) {
    const existing = await db.execute(
      sql`SELECT id FROM characters WHERE LOWER(name) = LOWER(${char.name}) LIMIT 1`
    );
    if ((existing as any).rows?.length > 0) {
      console.log(`  SKIP (exists): ${char.name}`);
      skipped++;
      continue;
    }
    await db.insert(charactersTable).values(char);
    console.log(`  + ${char.name} (${char.universe})`);
    added++;
  }

  console.log(`\nDone. Added: ${added}, Skipped: ${skipped}`);
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
