import { db, charactersTable } from "@workspace/db";
import { sql } from "drizzle-orm";

const characters = [
  // Action Heroes
  {
    name: "John Rambo",
    universe: "Action Heroes",
    strength: 85,
    speed: 75,
    intelligence: 74,
    durability: 83,
    specialAbility: "Guerrilla warfare mastery; survival expert; explosive traps and compound bow; fights through extreme injury",
    weaknesses: "PTSD flashbacks; fully human — enough firepower can kill him",
    description: "A Vietnam vet pushed too far who wages one-man wars against entire armies.",
  },
  {
    name: "John McClane",
    universe: "Action Heroes",
    strength: 74,
    speed: 72,
    intelligence: 80,
    durability: 78,
    specialAbility: "Improvised combat; refuses to quit; turns any environment into a weapon; extraordinary luck under pressure",
    weaknesses: "Fully human; no shoes",
    description: "A New York cop who somehow survives every disaster imaginable, usually barefoot.",
  },
  {
    name: "Ethan Hunt",
    universe: "Mission: Impossible",
    strength: 76,
    speed: 78,
    intelligence: 90,
    durability: 75,
    specialAbility: "Master of disguise and infiltration; tactical genius; impossible stunt execution; zero-failure mindset",
    weaknesses: "Operates alone — team casualties are his greatest vulnerability",
    description: "IMF's top agent, who accepts missions deemed truly impossible — then completes them.",
  },
  {
    name: "James Bond",
    universe: "Action Heroes",
    strength: 75,
    speed: 76,
    intelligence: 88,
    durability: 74,
    specialAbility: "MI6 license to kill; master spy and seducer; Q-Branch gadgetry; expert marksman and driver",
    weaknesses: "Overconfidence; can be caught off-guard by personal attachments",
    description: "Her Majesty's most dangerous secret agent — suave, lethal, and always in a tuxedo.",
  },
  {
    name: "The Punisher",
    universe: "Marvel",
    strength: 78,
    speed: 72,
    intelligence: 82,
    durability: 76,
    specialAbility: "Military-grade arsenal; expert tactician and marksman; no hesitation — will kill any villain",
    weaknesses: "No superpowers; obsessive tunnel vision on vengeance",
    description: "Frank Castle, a Marine whose family was murdered and who declared one-man war on all criminals.",
  },
  {
    name: "Ellen Ripley",
    universe: "Alien",
    strength: 68,
    speed: 68,
    intelligence: 87,
    durability: 70,
    specialAbility: "Xenomorph survival expertise; power loader operation; improvised flamethrower warfare; unbreakable will",
    weaknesses: "Fully human; isolated from backup; emotional attachment to survivors",
    description: "The ultimate survivor who faced Xenomorphs repeatedly — and lived every time.",
  },
  {
    name: "Mad Max",
    universe: "Mad Max",
    strength: 76,
    speed: 78,
    intelligence: 75,
    durability: 77,
    specialAbility: "Post-apocalyptic vehicle combat; survival skills in wasteland; shotgun mastery; near-suicidal resilience",
    weaknesses: "Haunted by his dead family; prefers solitude and avoids alliances",
    description: "A lone road warrior drifting through the Australian wasteland after civilization's collapse.",
  },
  {
    name: "Bryan Mills",
    universe: "Action Heroes",
    strength: 78,
    speed: 75,
    intelligence: 84,
    durability: 74,
    specialAbility: "A very particular set of skills: CIA-trained kidnapping retrieval; hand-to-hand and interrogation mastery",
    weaknesses: "Fully human; driven by emotion when family is threatened",
    description: "An ex-CIA operative with a very particular set of skills that make him a nightmare for kidnappers.",
  },
  {
    name: "Sarah Connor",
    universe: "Terminator",
    strength: 74,
    speed: 72,
    intelligence: 83,
    durability: 73,
    specialAbility: "Military training and weapons expertise; tactical planning against machine uprisings; fierce maternal drive",
    weaknesses: "Fully human; can be overwhelmed by Terminator-level threats",
    description: "From waitress to hardened resistance fighter — the mother of humanity's future savior.",
  },
  {
    name: "The Bride (Beatrix Kiddo)",
    universe: "Kill Bill",
    strength: 80,
    speed: 84,
    intelligence: 80,
    durability: 76,
    specialAbility: "Deadly Viper assassination techniques; Hanzo steel sword mastery; Five Point Palm Exploding Heart Technique",
    weaknesses: "Emotional drive for revenge can override tactical thinking",
    description: "A former assassin who awoke from a coma to take revenge on everyone who wronged her.",
  },
  {
    name: "Jason Bourne",
    universe: "Action Heroes",
    strength: 80,
    speed: 82,
    intelligence: 88,
    durability: 78,
    specialAbility: "Treadstone super-soldier conditioning; fights with anything at hand — a pen, a magazine, a toaster",
    weaknesses: "Fractured memory causes disorientation; avoids killing unless necessary",
    description: "A black ops assassin who lost his memory and went on the run from the very agency that made him.",
  },
  {
    name: "Indiana Jones",
    universe: "Action Heroes",
    strength: 72,
    speed: 70,
    intelligence: 92,
    durability: 70,
    specialAbility: "Bullwhip mastery; archaeological expertise; improvised combat in any setting; artifact knowledge",
    weaknesses: "Afraid of snakes; mortal — lucky far more often than skilled",
    description: "An archaeology professor who moonlights as the world's most reluctant adventurer.",
  },
  {
    name: "Martin Riggs",
    universe: "Action Heroes",
    strength: 78,
    speed: 76,
    intelligence: 76,
    durability: 78,
    specialAbility: "LAPD special forces training; will put himself in insane danger with zero hesitation; lethal in close quarters",
    weaknesses: "Suicidal tendencies; emotional instability from loss of his wife",
    description: "A borderline suicidal LAPD detective and war veteran who is a genuine lethal weapon.",
  },
  {
    name: "Neo (John Wick Mode)",
    universe: "Action Heroes",
    strength: 82,
    speed: 86,
    intelligence: 84,
    durability: 80,
    specialAbility: "Gun-fu mastery; hand-to-hand combat at elite level; tactical gun reload choreography",
    weaknesses: "Fully human outside the Matrix; can be exhausted",
    description: "The template for gun-fu action — every environment becomes a lethal weapon in his hands.",
  },
  {
    name: "Snake Plissken",
    universe: "Action Heroes",
    strength: 80,
    speed: 74,
    intelligence: 80,
    durability: 78,
    specialAbility: "Special Forces black ops training; works under extreme time pressure; cynical genius for survival",
    weaknesses: "Operates without backup; deeply mistrustful of allies",
    description: "A one-eyed ex-soldier who escapes New York and LA — even when nobody asked him to.",
  },
  {
    name: "The Driver",
    universe: "Action Heroes",
    strength: 70,
    speed: 90,
    intelligence: 82,
    durability: 70,
    specialAbility: "Unmatched vehicular control at any speed; ice-cold under fire; precision stunt driving",
    weaknesses: "Avoids direct confrontation; lethal only when cornered",
    description: "A Hollywood stunt driver and wheelman who never misses a window — five minutes, that's all you get.",
  },
  // Action Villains
  {
    name: "Hans Gruber",
    universe: "Action Villains",
    strength: 62,
    speed: 60,
    intelligence: 96,
    durability: 60,
    specialAbility: "Masterful heist planning; manipulation and misdirection; ice-cold under pressure; always has a backup plan",
    weaknesses: "Underestimates opponents who don't follow his script; overconfidence at critical moments",
    description: "A brilliant thief who orchestrated the Nakatomi Plaza takeover — until one cop ruined everything.",
  },
  {
    name: "Anton Chigurh",
    universe: "Action Villains",
    strength: 82,
    speed: 74,
    intelligence: 88,
    durability: 84,
    specialAbility: "Captive bolt pistol; unstoppable determination; philosophical indifference to his own injuries",
    weaknesses: "Rigid coin-flip philosophy — predictable when the coin lands wrong",
    description: "A hitman who operates by his own pitiless philosophy, offering a coin flip as mercy.",
  },
  {
    name: "Hannibal Lecter",
    universe: "Action Villains",
    strength: 72,
    speed: 68,
    intelligence: 100,
    durability: 68,
    specialAbility: "Surgical manipulation of the human mind; attacks at psychological weak points; lethal in close quarters when free",
    weaknesses: "Prefers wit over brute force; requires careful planning of escape",
    description: "A brilliant psychiatrist and cannibalistic serial killer — the most dangerous mind in captivity.",
  },
  {
    name: "The Joker",
    universe: "DC",
    strength: 65,
    speed: 65,
    intelligence: 92,
    durability: 64,
    specialAbility: "Complete unpredictability; Joker toxin; turns any situation into chaos; psychological warfare genius",
    weaknesses: "No fixed agenda — pure chaos limits long-term success; Batman refuses to kill him",
    description: "Gotham's Clown Prince of Crime — a force of pure chaos with no plan except anarchy.",
  },
  {
    name: "Bane",
    universe: "DC",
    strength: 94,
    speed: 72,
    intelligence: 88,
    durability: 90,
    specialAbility: "Venom serum granting superhuman strength; tactical military genius; broke Batman's back",
    weaknesses: "Venom mask is a critical vulnerability — destroy it and he's crippled by pain",
    description: "The man who broke the Bat — a genius strategist fueled by pain-numbing Venom.",
  },
  {
    name: "T-1000",
    universe: "Terminator",
    strength: 85,
    speed: 82,
    intelligence: 85,
    durability: 97,
    specialAbility: "Liquid metal morphing — can mimic any person and reshape limbs into blades; near-indestructible",
    weaknesses: "Extreme cold or heat can temporarily disrupt its form; acid can destroy it",
    description: "A mimetic polyalloy Terminator — it cannot be bargained with, cannot be reasoned with.",
  },
  {
    name: "Agent Smith",
    universe: "The Matrix",
    strength: 88,
    speed: 88,
    intelligence: 86,
    durability: 90,
    specialAbility: "Can replicate himself into any human body inside the Matrix; superhuman combat ability; virus-like spread",
    weaknesses: "Exists only within the Matrix; obsessive hatred of Neo clouds judgment",
    description: "A rogue program who became a virus — every human in the Matrix could become him.",
  },
  {
    name: "Colonel Hans Landa",
    universe: "Action Villains",
    strength: 62,
    speed: 60,
    intelligence: 98,
    durability: 60,
    specialAbility: "Detective-level intellect; perfect multilingualism; psychological intimidation; self-serving adaptability",
    weaknesses: "Ultimately loyal only to himself — will betray any cause for personal survival",
    description: "The 'Jew Hunter' — a charming, brilliant, and utterly terrifying SS colonel.",
  },
  {
    name: "Frank Booth",
    universe: "Action Villains",
    strength: 75,
    speed: 68,
    intelligence: 65,
    durability: 72,
    specialAbility: "Extreme unpredictability and sadism; criminal network control; sheer terrifying volatility",
    weaknesses: "Drug dependency impairs judgment; psychotic episodes make him reckless",
    description: "A deeply disturbed crime boss whose sheer unhinged violence makes him more dangerous than any army.",
  },
  {
    name: "Nurse Ratched",
    universe: "Action Villains",
    strength: 50,
    speed: 50,
    intelligence: 94,
    durability: 55,
    specialAbility: "Psychological manipulation and systematic control of anyone under her authority; institutional power as a weapon",
    weaknesses: "Loses power entirely when outside her institutional environment",
    description: "A psychiatric ward nurse who wields bureaucracy and psychology as instruments of cruelty.",
  },
  {
    name: "Keyser Soze",
    universe: "Action Villains",
    strength: 76,
    speed: 74,
    intelligence: 99,
    durability: 72,
    specialAbility: "Master criminal who erased his own identity; orchestrates plans from the shadows; myth-level fear factor",
    weaknesses: "Real identity being discovered would collapse his entire operation",
    description: "The greatest trick the devil ever pulled was convincing the world he didn't exist.",
  },
  {
    name: "Vincent (Collateral)",
    universe: "Action Villains",
    strength: 78,
    speed: 78,
    intelligence: 90,
    durability: 76,
    specialAbility: "Contract killer precision; ice-cold under fire; shoots in near-darkness; philosophy as a weapon",
    weaknesses: "Overconfidence that his detachment makes him untouchable",
    description: "A silver-haired hitman with a single night to complete five kills — methodical, brilliant, lethal.",
  },
  {
    name: "Terminator T-3000",
    universe: "Terminator",
    strength: 92,
    speed: 85,
    intelligence: 88,
    durability: 95,
    specialAbility: "Nanomachine-based body; can reconfigure itself mid-fight; magnetic disruption immunity after adaptation",
    weaknesses: "Magnetic fields of extreme power; still processing human host conversion",
    description: "A Terminator built from a converted human — molecular machines instead of metal.",
  },
  {
    name: "Ivan Drago",
    universe: "Action Villains",
    strength: 95,
    speed: 80,
    intelligence: 60,
    durability: 92,
    specialAbility: "2000 PSI punch force; chemically-enhanced Soviet boxing physique; absolutely no mercy",
    weaknesses: "Relies solely on raw power; can be broken by sheer willpower and heart",
    description: "The Soviet super-boxer engineered to destroy — if he dies, he dies.",
  },
  {
    name: "Clubber Lang",
    universe: "Action Villains",
    strength: 92,
    speed: 82,
    intelligence: 60,
    durability: 88,
    specialAbility: "Raw aggressive boxing power; relentless pressure; punches through any defense",
    weaknesses: "Overconfidence; tires in extended fights against disciplined opponents",
    description: "A savage boxer from Chicago who became World Champion by sheer brutal force.",
  },
  {
    name: "Silva (Skyfall)",
    universe: "Action Villains",
    strength: 70,
    speed: 68,
    intelligence: 96,
    durability: 68,
    specialAbility: "World-class cyberterrorism and hacking; MI6 insider knowledge; personal vendetta with M",
    weaknesses: "Personal obsession with M means he can be baited",
    description: "A former MI6 agent turned cyberterrorist who wants to watch M's world burn.",
  },
];

async function seed() {
  console.log(`Seeding ${characters.length} action heroes and villains...`);

  let added = 0;
  let skipped = 0;

  for (const char of characters) {
    try {
      const existing = await db
        .select()
        .from(charactersTable)
        .where(sql`lower(${charactersTable.name}) = lower(${char.name})`);

      if (existing.length > 0) {
        console.log(`  SKIP: ${char.name} already exists`);
        skipped++;
        continue;
      }

      await db.insert(charactersTable).values(char);
      console.log(`  ADD:  ${char.name} (${char.universe})`);
      added++;
    } catch (err) {
      console.error(`  ERROR seeding ${char.name}:`, err);
    }
  }

  console.log(`\nDone! Added: ${added}, Skipped: ${skipped}`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
