import { db, charactersTable } from "@workspace/db";
import { sql } from "drizzle-orm";

const characters = [
  // Marvel Universe
  {
    name: "Iron Man",
    universe: "Marvel",
    strength: 85,
    speed: 78,
    intelligence: 99,
    durability: 82,
    specialAbility: "Arc Reactor-powered Iron Man suit with repulsor beams and advanced AI (JARVIS)",
    weaknesses: "Suit can be disabled by powerful EMP; heart condition; overconfidence",
    description: "Genius billionaire Tony Stark, who built a powered armor suit to become Iron Man.",
  },
  {
    name: "Spider-Man",
    universe: "Marvel",
    strength: 75,
    speed: 84,
    intelligence: 88,
    durability: 70,
    specialAbility: "Spider-sense, wall-crawling, web-slinging, and superhuman agility",
    weaknesses: "Ethyl chloride pesticide, Vibranium (when used against him), overextending himself",
    description: "Peter Parker, bitten by a radioactive spider and granted incredible arachnid abilities.",
  },
  {
    name: "Thor",
    universe: "Marvel",
    strength: 95,
    speed: 85,
    intelligence: 72,
    durability: 93,
    specialAbility: "Control over lightning and storms with Mjolnir; Asgardian physiology",
    weaknesses: "Loss of Mjolnir removes weather powers; prolonged battles without rest",
    description: "The Asgardian God of Thunder, wielder of the enchanted hammer Mjolnir.",
  },
  {
    name: "Hulk",
    universe: "Marvel",
    strength: 100,
    speed: 60,
    intelligence: 30,
    durability: 99,
    specialAbility: "Limitless strength that grows with rage; near-invulnerability; regeneration",
    weaknesses: "Psychological manipulation targeting Bruce Banner; gamma radiation reversal",
    description: "Dr. Bruce Banner transformed by gamma radiation into an unstoppable green giant.",
  },
  {
    name: "Captain America",
    universe: "Marvel",
    strength: 78,
    speed: 75,
    intelligence: 82,
    durability: 76,
    specialAbility: "Super-Soldier Serum giving peak human perfection; indestructible Vibranium shield",
    weaknesses: "Not superhuman — can still be killed by sufficient force",
    description: "Steve Rogers, transformed from a frail man into the ultimate soldier of World War II.",
  },
  {
    name: "Doctor Strange",
    universe: "Marvel",
    strength: 55,
    speed: 70,
    intelligence: 97,
    durability: 68,
    specialAbility: "Master of the Mystic Arts; time manipulation with the Eye of Agamotto; dimensional travel",
    weaknesses: "Injured hands limit some spellcasting; spells require concentration",
    description: "Stephen Strange, former surgeon turned Sorcerer Supreme of Earth.",
  },
  {
    name: "Wolverine",
    universe: "Marvel",
    strength: 80,
    speed: 72,
    intelligence: 70,
    durability: 95,
    specialAbility: "Adamantium skeleton and claws; superhuman healing factor that regenerates almost any injury",
    weaknesses: "Adamantium can be melted; powerful telepaths can overwhelm him",
    description: "James Howlett, a mutant with bone claws and an indestructible Adamantium skeleton.",
  },
  {
    name: "Scarlet Witch",
    universe: "Marvel",
    strength: 65,
    speed: 68,
    intelligence: 85,
    durability: 72,
    specialAbility: "Reality-warping chaos magic; probability manipulation; hex bolts",
    weaknesses: "Emotional instability can destabilize her powers; magical counterattacks",
    description: "Wanda Maximoff, a mutant sorceress with the power to alter reality itself.",
  },
  {
    name: "Black Panther",
    universe: "Marvel",
    strength: 82,
    speed: 82,
    intelligence: 90,
    durability: 84,
    specialAbility: "Vibranium-woven Panther Habit that absorbs kinetic energy; enhanced senses from Heart-Shaped Herb",
    weaknesses: "Powerful energy attacks that exceed Vibranium absorption limits",
    description: "T'Challa, King of Wakanda and the Black Panther, protector of his people.",
  },
  {
    name: "Deadpool",
    universe: "Marvel",
    strength: 76,
    speed: 74,
    intelligence: 65,
    durability: 98,
    specialAbility: "Extreme regenerative healing factor; enhanced strength; master combatant and marksman; fourth-wall breaking",
    weaknesses: "Brain damage can disorient him; carbonadium slows healing factor",
    description: "Wade Wilson, a mercenary with an accelerated healing factor and a very dark sense of humor.",
  },
  {
    name: "Thanos",
    universe: "Marvel",
    strength: 98,
    speed: 70,
    intelligence: 92,
    durability: 97,
    specialAbility: "Infinity Gauntlet with all six Infinity Stones; reality manipulation; matter control",
    weaknesses: "Overconfidence; deliberate self-sabotage rooted in nihilism",
    description: "The Mad Titan who seeks to collect the Infinity Stones to reshape the universe.",
  },
  {
    name: "Magneto",
    universe: "Marvel",
    strength: 60,
    speed: 72,
    intelligence: 94,
    durability: 74,
    specialAbility: "Total control over magnetism, allowing flight, metal manipulation, and electromagnetic pulse generation",
    weaknesses: "Extreme mental strain; non-metallic substances; powerful telepathy",
    description: "Erik Lehnsherr, a Holocaust survivor turned master of magnetism and leader of mutantkind.",
  },
  {
    name: "Storm",
    universe: "Marvel",
    strength: 65,
    speed: 78,
    intelligence: 80,
    durability: 73,
    specialAbility: "Complete mastery over weather — lightning, wind, blizzards, tornadoes, and more",
    weaknesses: "Claustrophobia can compromise concentration; loss of powers in contained spaces",
    description: "Ororo Munroe, a mutant who commands the weather with goddess-like power.",
  },
  {
    name: "Captain Marvel",
    universe: "Marvel",
    strength: 93,
    speed: 95,
    intelligence: 82,
    durability: 90,
    specialAbility: "Photon energy blasts; binary form granting stellar power; flight at near-light speed",
    weaknesses: "Can be overwhelmed by sufficiently powerful cosmic forces; memory tampering",
    description: "Carol Danvers, an Air Force pilot transformed into a cosmic-powered superhero.",
  },
  {
    name: "Silver Surfer",
    universe: "Marvel",
    strength: 88,
    speed: 99,
    intelligence: 86,
    durability: 95,
    specialAbility: "Power Cosmic; can travel faster than light on a surfboard; energy manipulation",
    weaknesses: "Cannot enter Earth's atmosphere easily; emotional vulnerability from past",
    description: "Norrin Radd, who gave up his freedom to become the Herald of Galactus.",
  },
  // DC Universe
  {
    name: "Batman",
    universe: "DC",
    strength: 70,
    speed: 68,
    intelligence: 100,
    durability: 67,
    specialAbility: "World's greatest detective; mastery of 127 martial arts; cutting-edge tech and gadgets",
    weaknesses: "No superhuman powers; mortality; loved ones as leverage",
    description: "Bruce Wayne, a billionaire who channels his grief into becoming the Dark Knight of Gotham.",
  },
  {
    name: "Superman",
    universe: "DC",
    strength: 100,
    speed: 97,
    intelligence: 85,
    durability: 100,
    specialAbility: "Solar-powered flight, heat vision, freeze breath, near-invulnerability and super strength",
    weaknesses: "Kryptonite; red sun radiation; magic",
    description: "Kal-El of Krypton, Earth's greatest hero who stands for truth, justice and hope.",
  },
  {
    name: "Wonder Woman",
    universe: "DC",
    strength: 93,
    speed: 88,
    intelligence: 87,
    durability: 90,
    specialAbility: "God-forged Lasso of Truth; divine Amazonian warrior training; near-invulnerable bracelets",
    weaknesses: "Piercing weapons bypassing her defenses; binding her bracelets",
    description: "Princess Diana of Themyscira, an Amazonian warrior blessed by the gods.",
  },
  {
    name: "The Flash",
    universe: "DC",
    strength: 70,
    speed: 100,
    intelligence: 80,
    durability: 72,
    specialAbility: "Speed Force connection; time travel via running; infinite mass punch at near-light speed",
    weaknesses: "Needs to eat constantly; tachyon-based traps; speed-stealing abilities",
    description: "Barry Allen, the fastest man alive, connected to the Speed Force.",
  },
  {
    name: "Green Lantern",
    universe: "DC",
    strength: 78,
    speed: 80,
    intelligence: 82,
    durability: 82,
    specialAbility: "Power Ring constructs limited only by willpower and imagination",
    weaknesses: "Yellow color (in older versions); strong emotional trauma weakening the ring's power",
    description: "Hal Jordan, an Air Force pilot chosen to be the greatest Green Lantern of the Corps.",
  },
  {
    name: "Aquaman",
    universe: "DC",
    strength: 88,
    speed: 75,
    intelligence: 75,
    durability: 85,
    specialAbility: "Telepathy with marine life; superhuman strength amplified underwater; Trident of Poseidon",
    weaknesses: "Dehydration significantly weakens him; land-based combat is less effective",
    description: "Arthur Curry, King of Atlantis and protector of the seven seas.",
  },
  {
    name: "Martian Manhunter",
    universe: "DC",
    strength: 90,
    speed: 85,
    intelligence: 92,
    durability: 88,
    specialAbility: "Shapeshifting, telepathy, intangibility, flight, and Martian super-strength",
    weaknesses: "Extreme vulnerability to fire; isolated Martian psychology",
    description: "J'onn J'onzz, the last survivor of Mars and one of Earth's greatest protectors.",
  },
  {
    name: "Darkseid",
    universe: "DC",
    strength: 99,
    speed: 72,
    intelligence: 95,
    durability: 99,
    specialAbility: "Omega Beams that can erase targets from existence; near-omnipotent New God power",
    weaknesses: "Anti-Life Equation has conditions; other New Gods; rare emotional vulnerability",
    description: "The God of Evil, ruler of Apokolips, who seeks the Anti-Life Equation to subjugate all reality.",
  },
  {
    name: "Shazam",
    universe: "DC",
    strength: 92,
    speed: 90,
    intelligence: 75,
    durability: 91,
    specialAbility: "Wisdom of Solomon, Strength of Hercules, Stamina of Atlas, Power of Zeus (lightning), Courage of Achilles, Speed of Mercury",
    weaknesses: "Reverts to a child (Billy Batson) if forced to say his name; magic-based vulnerabilities",
    description: "Billy Batson, a boy who transforms into a godlike champion by shouting 'SHAZAM!'",
  },
  {
    name: "Lex Luthor",
    universe: "DC",
    strength: 60,
    speed: 55,
    intelligence: 99,
    durability: 58,
    specialAbility: "Kryptonite-powered War Suit; unmatched scientific genius; vast corporate empire",
    weaknesses: "Completely human without his technology; obsessive hatred of Superman clouds judgment",
    description: "The greatest criminal mind in Metropolis and Superman's most dangerous enemy.",
  },
  // Anime
  {
    name: "Goku",
    universe: "Dragon Ball",
    strength: 99,
    speed: 98,
    intelligence: 60,
    durability: 96,
    specialAbility: "Ultra Instinct; Kamehameha; Spirit Bomb; Super Saiyan transformations",
    weaknesses: "Heart virus susceptibility; reckless in battle; underestimates opponents",
    description: "Son Goku, a Saiyan warrior raised on Earth who pushes his limits beyond all reason.",
  },
  {
    name: "Vegeta",
    universe: "Dragon Ball",
    strength: 97,
    speed: 96,
    intelligence: 72,
    durability: 94,
    specialAbility: "Final Flash; Super Saiyan Blue Evolution; pride-driven power surges",
    weaknesses: "Pride causes strategic mistakes; sometimes hesitates against former allies",
    description: "The Prince of all Saiyans, who fights both for his people's honor and his own redemption.",
  },
  {
    name: "Naruto Uzumaki",
    universe: "Naruto",
    strength: 90,
    speed: 92,
    intelligence: 65,
    durability: 88,
    specialAbility: "Nine-Tails Chakra; Sage Mode; Rasengan; Shadow Clone Jutsu; Six Paths Sage Mode",
    weaknesses: "Emotional attacks targeting his loved ones; early overreliance on brute force",
    description: "The boy who was shunned by his village and became its greatest hero — the Seventh Hokage.",
  },
  {
    name: "Sasuke Uchiha",
    universe: "Naruto",
    strength: 87,
    speed: 91,
    intelligence: 90,
    durability: 83,
    specialAbility: "Rinnegan and Sharingan eyes; Chidori; Amaterasu; Susanoo; interdimensional teleportation",
    weaknesses: "Lone wolf mentality; loss of Rinnegan severely limits power",
    description: "The last loyal Uchiha, who walked a dark path before becoming a guardian of the shinobi world.",
  },
  {
    name: "Ichigo Kurosaki",
    universe: "Bleach",
    strength: 92,
    speed: 93,
    intelligence: 68,
    durability: 89,
    specialAbility: "Bankai: Tensa Zangetsu; Hollow mask transformation; Final Getsuga Tensho",
    weaknesses: "Power fluctuates with emotional state; has lost his powers multiple times",
    description: "A teenager with the power of a Soul Reaper who defends the living and the dead.",
  },
  {
    name: "Monkey D. Luffy",
    universe: "One Piece",
    strength: 91,
    speed: 88,
    intelligence: 55,
    durability: 93,
    specialAbility: "Gear transformations; Conqueror's Haki; Rubber body and Gear 5 Sun God Nika awakening",
    weaknesses: "Cannot swim; needs to eat massive amounts; reckless in battle",
    description: "A rubber-bodied pirate with the dream of becoming King of the Pirates.",
  },
  {
    name: "Roronoa Zoro",
    universe: "One Piece",
    strength: 89,
    speed: 85,
    intelligence: 65,
    durability: 90,
    specialAbility: "Three-sword style (including a blade in his mouth); Conqueror's Haki; Asura technique",
    weaknesses: "Terrible sense of direction; extreme injuries can incapacitate him temporarily",
    description: "A swordsman who trains relentlessly to become the world's greatest, carrying his friend's dream.",
  },
  {
    name: "Saitama",
    universe: "One Punch Man",
    strength: 100,
    speed: 100,
    intelligence: 60,
    durability: 100,
    specialAbility: "Limitless physical strength, speed, and durability from rigorous training",
    weaknesses: "Extreme boredom; cannot sense ki or chakra; may hesitate at full power",
    description: "The hero who trained so hard he became unbeatable — to the point of losing all joy in battle.",
  },
  {
    name: "Levi Ackerman",
    universe: "Attack on Titan",
    strength: 78,
    speed: 90,
    intelligence: 85,
    durability: 72,
    specialAbility: "Ackerman bloodline giving superhuman physical ability; ODM gear mastery; Titan slaying expertise",
    weaknesses: "Still human — mortal wounds can kill him; explosives once incapacitated him",
    description: "Humanity's Strongest Soldier, a compact titan-killer of legendary skill.",
  },
  {
    name: "Eren Yeager",
    universe: "Attack on Titan",
    strength: 85,
    speed: 80,
    intelligence: 82,
    durability: 87,
    specialAbility: "Attack Titan, War Hammer, and Founding Titan powers; future memory access; Rumbling command",
    weaknesses: "Transformation takes preparation; body is vulnerable when outside his Titan form",
    description: "A boy who wanted freedom and became a force of apocalyptic destruction.",
  },
  {
    name: "Killua Zoldyck",
    universe: "Hunter x Hunter",
    strength: 78,
    speed: 95,
    intelligence: 88,
    durability: 75,
    specialAbility: "Godspeed Nen ability; lightning-based Killua Mode; trained assassin from birth",
    weaknesses: "Emotional attachment to Gon sometimes overrides strategic thinking",
    description: "A prodigy assassin from a family of killers who chose friendship over duty.",
  },
  {
    name: "Meruem",
    universe: "Hunter x Hunter",
    strength: 96,
    speed: 97,
    intelligence: 98,
    durability: 94,
    specialAbility: "Royal Guard Nen absorption; Nen evolution through consuming others; near-perfect combat instinct",
    weaknesses: "Rose poison eventually; rare emotional blind spots following his awakening",
    description: "The Chimera Ant King, born to dominate all species — until he discovered his humanity.",
  },
  {
    name: "Giorno Giovanna",
    universe: "JoJo's Bizarre Adventure",
    strength: 72,
    speed: 80,
    intelligence: 88,
    durability: 74,
    specialAbility: "Gold Experience Requiem: returns any action to zero, nullifying all cause and effect",
    weaknesses: "Stand fight limitations; cannot use GER offensively without a trigger condition",
    description: "The son of DIO who dreams of becoming a gang-star and protecting the innocent.",
  },
  {
    name: "Jotaro Kujo",
    universe: "JoJo's Bizarre Adventure",
    strength: 80,
    speed: 82,
    intelligence: 85,
    durability: 80,
    specialAbility: "Star Platinum: time-stopping Stand with superhuman precision and strength",
    weaknesses: "Time stop duration is limited; emotional coldness can be exploited",
    description: "A stoic delinquent who inherited the Joestar legacy and fought DIO across time.",
  },
  {
    name: "Alucard",
    universe: "Hellsing",
    strength: 88,
    speed: 90,
    intelligence: 90,
    durability: 99,
    specialAbility: "True Immortality via Schrodinger; shadow manipulation; absorbed soul army; Casull pistol",
    weaknesses: "Can be temporarily sealed; sunlight in weakened states; religious artifacts",
    description: "The No Life King, Hellsing's ultimate weapon, a vampire of truly terrifying power.",
  },
  {
    name: "Rimuru Tempest",
    universe: "That Time I Got Reincarnated as a Slime",
    strength: 88,
    speed: 85,
    intelligence: 92,
    durability: 92,
    specialAbility: "Great Sage/Raphael; predator skill absorbing any ability; True Dragon power",
    weaknesses: "Early reliance on information gathering; mercy for allies can delay decisive action",
    description: "A reincarnated salary worker who became the slime Demon Lord Rimuru Tempest.",
  },
  {
    name: "Edward Elric",
    universe: "Fullmetal Alchemist",
    strength: 74,
    speed: 76,
    intelligence: 93,
    durability: 71,
    specialAbility: "Alchemy without a transmutation circle; Automail arm and leg; Truth's absolute knowledge",
    weaknesses: "Automail arm can be detached; still mortal; emotional vulnerability regarding Al",
    description: "The Fullmetal Alchemist, a prodigy who sacrificed a limb and his brother's body in forbidden alchemy.",
  },
  // Video Games
  {
    name: "Kratos",
    universe: "God of War",
    strength: 99,
    speed: 80,
    intelligence: 72,
    durability: 97,
    specialAbility: "Leviathan Axe; Blades of Chaos; Spartan Rage; God-killing combat experience",
    weaknesses: "Haunted by guilt that blinds him; protective of Atreus at great cost",
    description: "The Ghost of Sparta who slew the Greek pantheon and now navigates the Norse realms.",
  },
  {
    name: "Master Chief",
    universe: "Halo",
    strength: 82,
    speed: 78,
    intelligence: 83,
    durability: 88,
    specialAbility: "Mjolnir Powered Assault Armor; enhanced Spartan reflexes; AI companion Cortana",
    weaknesses: "Relies on armor for much of his enhancement; human limitations beneath the suit",
    description: "John-117, the UNSC's greatest warrior, who has saved humanity from extinction multiple times.",
  },
  {
    name: "Doomslayer",
    universe: "Doom",
    strength: 94,
    speed: 88,
    intelligence: 68,
    durability: 96,
    specialAbility: "Praetor Suit; glory kill health system; BFG-9000; rage-fueled power against demonic energy",
    weaknesses: "No subtlety; ranged opponents at great distance; targeted by Maykr gods",
    description: "An ancient warrior betrayed and condemned to fight demons for eternity — and he's very good at it.",
  },
  {
    name: "Cloud Strife",
    universe: "Final Fantasy",
    strength: 86,
    speed: 82,
    intelligence: 74,
    durability: 82,
    specialAbility: "Buster Sword; Limit Break: Omnislash; enhanced Jenova cells giving superhuman ability",
    weaknesses: "Psychological trauma and identity crisis; Sephiroth's mental influence",
    description: "A SOLDIER turned mercenary who carries the weight of the Planet's fate on his shoulders.",
  },
  {
    name: "Geralt of Rivia",
    universe: "The Witcher",
    strength: 78,
    speed: 80,
    intelligence: 85,
    durability: 80,
    specialAbility: "Witcher mutations; Signs (magic); silver sword for monsters, steel for men",
    weaknesses: "Politically neutral stance limits resources; emotional bonds are exploited",
    description: "A mutant monster hunter who navigates a morally grey world with a sharp sword and sharper wit.",
  },
  {
    name: "Link",
    universe: "The Legend of Zelda",
    strength: 76,
    speed: 78,
    intelligence: 80,
    durability: 75,
    specialAbility: "Master Sword that banishes evil; Triforce of Courage; wide arsenal of divine tools",
    weaknesses: "Without Master Sword or Triforce, much of his divine protection is lost",
    description: "The eternal hero of Hyrule, chosen by the Triforce of Courage to oppose the darkness.",
  },
  {
    name: "Sephiroth",
    universe: "Final Fantasy",
    strength: 92,
    speed: 90,
    intelligence: 88,
    durability: 88,
    specialAbility: "Masamune; Supernova; near-omnipotent One-Winged Angel transformation; Jenova cells",
    weaknesses: "Obsession with Cloud; emotional coldness prevents adaptability in unexpected situations",
    description: "SOLDIER's greatest warrior gone mad, seeking to become a god by destroying the Planet.",
  },
  {
    name: "Dante",
    universe: "Devil May Cry",
    strength: 88,
    speed: 92,
    intelligence: 76,
    durability: 90,
    specialAbility: "Devil Trigger transformation; dual pistols Ebony and Ivory; sword Rebellion/Sparda; near-immortal",
    weaknesses: "Overconfidence; often deliberately holds back for fun",
    description: "Son of the Legendary Dark Knight Sparda, a demon hunter who fights evil with style.",
  },
  {
    name: "Bayonetta",
    universe: "Bayonetta",
    strength: 84,
    speed: 93,
    intelligence: 82,
    durability: 82,
    specialAbility: "Witch Time (bullet-time dodging); hair-based Infernal Demon summons; four-gun combat",
    weaknesses: "Running out of magic power limits Witch Time; holy water attacks",
    description: "An Umbra Witch who fights angels and demons in stilettos, guns on all four limbs.",
  },
  // Lord of the Rings
  {
    name: "Gandalf",
    universe: "Lord of the Rings",
    strength: 75,
    speed: 65,
    intelligence: 98,
    durability: 78,
    specialAbility: "Narya the Great Ring of Fire; ancient Maiar power; command of armies and beasts",
    weaknesses: "Self-imposed limitations on direct power; mortality of his mortal form",
    description: "The Grey Pilgrim, a Maiar spirit sent to Middle-earth to guide the free peoples against Sauron.",
  },
  {
    name: "Aragorn",
    universe: "Lord of the Rings",
    strength: 82,
    speed: 76,
    intelligence: 86,
    durability: 80,
    specialAbility: "Andúril, Flame of the West; Dunedain healing touch; command of the Dead Men of Dunharrow",
    weaknesses: "Mortal — lives a long life but can be killed; burden of kingship causes hesitation",
    description: "The last heir of Isildur, the Ranger who would become King Elessar of Gondor.",
  },
  {
    name: "Legolas",
    universe: "Lord of the Rings",
    strength: 77,
    speed: 86,
    intelligence: 82,
    durability: 78,
    specialAbility: "Elven vision and reflexes; never misses a shot; walks on snow without sinking",
    weaknesses: "Emotional bonds can cloud his judgement in battle",
    description: "A Prince of the Woodland Realm with supernatural elven sight and an infallible aim.",
  },
  {
    name: "Saruman",
    universe: "Lord of the Rings",
    strength: 70,
    speed: 60,
    intelligence: 97,
    durability: 75,
    specialAbility: "White Council magic; persuasive voice of power; Palantír foresight; master of industry and treachery",
    weaknesses: "Pride and lust for power led to his corruption and eventual ruin",
    description: "The White Wizard who betrayed Middle-earth for promises of power from the Dark Lord.",
  },
  // Harry Potter
  {
    name: "Voldemort",
    universe: "Harry Potter",
    strength: 65,
    speed: 70,
    intelligence: 95,
    durability: 85,
    specialAbility: "Horcruxes granting near-immortality; Avada Kedavra; Parseltongue; wandless magic mastery",
    weaknesses: "Horcruxes can be destroyed; inability to love is both moral and magical blind spot; Harry",
    description: "Tom Marvolo Riddle, the Dark Lord who split his soul to achieve immortality.",
  },
  {
    name: "Dumbledore",
    universe: "Harry Potter",
    strength: 70,
    speed: 72,
    intelligence: 99,
    durability: 78,
    specialAbility: "Elder Wand mastery; supreme dueling skill; Obscurus knowledge; Phoenix Fawkes",
    weaknesses: "Strategic gambits involving sacrifice; the curse from the Gaunt ring",
    description: "The greatest wizard of his age, Headmaster of Hogwarts and leader of the Order of the Phoenix.",
  },
  {
    name: "Hermione Granger",
    universe: "Harry Potter",
    strength: 50,
    speed: 58,
    intelligence: 98,
    durability: 55,
    specialAbility: "Encyclopedic magical knowledge; Time-Turner; quick-cast spellwork; unbreakable logical mind",
    weaknesses: "Overreliance on rule-based thinking in chaotic scenarios",
    description: "The brightest witch of her age, whose intelligence and loyalty saved Harry more times than he admits.",
  },
  // Movies & TV
  {
    name: "John Wick",
    universe: "John Wick",
    strength: 78,
    speed: 80,
    intelligence: 82,
    durability: 75,
    specialAbility: "Judo; tactical pistol shooting; vehicle combat; can fight through near-fatal wounds",
    weaknesses: "Fully human; can be overwhelmed by sheer numbers eventually",
    description: "An ex-hitman drawn back into the underworld who leaves a trail of bodies in his wake.",
  },
  {
    name: "Terminator T-800",
    universe: "Terminator",
    strength: 90,
    speed: 68,
    intelligence: 78,
    durability: 93,
    specialAbility: "Titanium endoskeleton; never tires; can repair itself; tactical targeting from future AI",
    weaknesses: "Flesh exterior can be damaged; can be melted by extreme heat sources; limited adaptability",
    description: "A cybernetic assassin sent back from the future, later reprogrammed to protect.",
  },
  {
    name: "Predator",
    universe: "Predator",
    strength: 85,
    speed: 78,
    intelligence: 80,
    durability: 82,
    specialAbility: "Thermal vision; active cloaking; shoulder plasma cannon; wrist blades and spear",
    weaknesses: "Honor code limits kills to armed opponents; extreme cold disrupts thermal vision",
    description: "An alien trophy hunter who travels across the galaxy to hunt the most dangerous prey.",
  },
  {
    name: "Xenomorph",
    universe: "Alien",
    strength: 80,
    speed: 84,
    intelligence: 55,
    durability: 80,
    specialAbility: "Acidic blood that burns through armor; endoparasitic life cycle; incredible stealth and speed",
    weaknesses: "Vacuum of space; fire; targeted destruction of hive queen breaks their coordination",
    description: "A perfect biological weapon — no mercy, no hesitation, only the hunt.",
  },
  {
    name: "Neo",
    universe: "The Matrix",
    strength: 85,
    speed: 90,
    intelligence: 85,
    durability: 82,
    specialAbility: "Reality manipulation within the Matrix; bullet-time; can fly; resurrection from death",
    weaknesses: "Powers are largely limited to the Matrix digital world",
    description: "The One, a human who bent the rules of a simulated reality and freed humanity.",
  },
  // Mythology & Literature
  {
    name: "Dracula",
    universe: "Gothic Horror",
    strength: 86,
    speed: 84,
    intelligence: 88,
    durability: 85,
    specialAbility: "Vampire immortality; shapeshifting; telepathic thrall; mist and bat forms",
    weaknesses: "Sunlight; holy symbols; garlic; must sleep in home soil; invitation needed to enter",
    description: "The immortal Count of Transylvania, master of the night and lord of the undead.",
  },
  {
    name: "Hercules",
    universe: "Greek Mythology",
    strength: 99,
    speed: 74,
    intelligence: 65,
    durability: 95,
    specialAbility: "Divine strength from Zeus; Twelve Labors hardened body and will; Nemean Lion pelt armor",
    weaknesses: "Temporary madness sent by Hera; trusting nature makes him manipulable",
    description: "The greatest of all Greek heroes, a demigod of legendary strength and courage.",
  },
  {
    name: "Achilles",
    universe: "Greek Mythology",
    strength: 90,
    speed: 94,
    intelligence: 75,
    durability: 88,
    specialAbility: "Near-invulnerable body (except heel); divine speed and fighting skill; Myrmidons command",
    weaknesses: "The infamous heel; pride and rage cause critical strategic errors",
    description: "The greatest warrior of the Trojan War, whose wrath shaped the fate of nations.",
  },
  {
    name: "Sun Wukong",
    universe: "Journey to the West",
    strength: 96,
    speed: 96,
    intelligence: 80,
    durability: 94,
    specialAbility: "72 transformations; cloud somersault; Ruyi Jingu Bang (magic staff); immortality from Heaven's peaches",
    weaknesses: "Pride; the Five Elements Mountain seal; Tripitaka's headband",
    description: "The Monkey King, a trickster deity of limitless power who challenged Heaven itself.",
  },
  // Sci-Fi
  {
    name: "Darth Vader",
    universe: "Star Wars",
    strength: 88,
    speed: 72,
    intelligence: 88,
    durability: 85,
    specialAbility: "Force choke; lightsaber mastery; Sith telekinesis; life support armor",
    weaknesses: "Life support suit has vulnerabilities; internal conflict between dark side and fatherly love",
    description: "Once Anakin Skywalker, fallen Jedi Knight, now the Dark Lord of the Sith.",
  },
  {
    name: "Yoda",
    universe: "Star Wars",
    strength: 50,
    speed: 82,
    intelligence: 100,
    durability: 68,
    specialAbility: "Unmatched Force mastery; lightsaber Form IV (Ataru); Force lightning absorption; precognition",
    weaknesses: "Small physical frame limits some combat options; foresight has limits",
    description: "The ancient Grand Master of the Jedi Order, 900 years of wisdom in a small green body.",
  },
  {
    name: "T'Challa / Black Panther",
    universe: "Marvel",
    strength: 84,
    speed: 83,
    intelligence: 91,
    durability: 86,
    specialAbility: "Vibranium Panther Habit that stores and releases kinetic energy; enhanced senses and healing",
    weaknesses: "Suit has energy absorption limits; political pressures can limit decisive action",
    description: "Wakanda's warrior king, whose suit turns every blow against him into his greatest weapon.",
  },
  {
    name: "Optimus Prime",
    universe: "Transformers",
    strength: 97,
    speed: 75,
    intelligence: 88,
    durability: 94,
    specialAbility: "Transform between truck and robot; Matrix of Leadership; Energon axe; trailer arsenal",
    weaknesses: "Protective nature causes him to shield allies at personal cost; Energon dependency",
    description: "Leader of the Autobots, who fights to protect both Cybertron and humanity.",
  },
];

async function seed() {
  console.log(`Seeding ${characters.length} characters...`);

  let added = 0;
  let skipped = 0;

  for (const char of characters) {
    try {
      const existing = await db
        .select()
        .from(charactersTable)
        .where(sql`lower(${charactersTable.name}) = lower(${char.name})`);

      if (existing.length > 0) {
        console.log(`  SKIP: ${char.name} already exists`);
        skipped++;
        continue;
      }

      await db.insert(charactersTable).values(char);
      console.log(`  ADD:  ${char.name} (${char.universe})`);
      added++;
    } catch (err) {
      console.error(`  ERROR seeding ${char.name}:`, err);
    }
  }

  console.log(`\nDone! Added: ${added}, Skipped: ${skipped}`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
