import { db, charactersTable } from "@workspace/db";

type Char = {
  name: string;
  universe: string;
  strength: number;
  speed: number;
  intelligence: number;
  durability: number;
  specialAbility: string;
  weaknesses: string;
  description: string;
};

const characters: Char[] = [
  // ── Variants of existing characters ─────────────────────────────────────────
  { name: "Batman (Arkham)", universe: "DC",
    strength: 70, speed: 76, intelligence: 96, durability: 72,
    specialAbility: "Detective vision; gadget mastery; predator/silent takedowns; freeflow combat against entire gangs",
    weaknesses: "Still human; trauma drives reckless choices; relies on prep and gear",
    description: "The Arkham incarnation of Bruce Wayne — peak detective and combatant who clears asylums one stealth takedown at a time." },
  { name: "Batman (Hellbat Suit)", universe: "DC",
    strength: 95, speed: 90, intelligence: 96, durability: 95,
    specialAbility: "Solar-powered Justice League armor; flight; energy projection; trades health for raw output",
    weaknesses: "Suit drains his life force the longer it is worn; suit can be hacked or pierced by cosmics",
    description: "Bruce in League-built armor designed to make him a god for a few minutes — and to nearly kill him by the end of the fight." },
  { name: "Superman (Injustice)", universe: "DC",
    strength: 99, speed: 98, intelligence: 88, durability: 99,
    specialAbility: "Solar-charged strength and flight; heat vision; freeze breath; willingness to kill — pill-empowered to fight gods",
    weaknesses: "Magic; kryptonite; rage clouds his judgment; tyranny isolates him from allies",
    description: "The Regime Superman — a Clark Kent broken by loss who installed himself as Earth's tyrant and dares anyone to stop him." },
  { name: "Superman (Prime One Million)", universe: "DC",
    strength: 100, speed: 100, intelligence: 95, durability: 100,
    specialAbility: "Sun-dipped for millennia; reality-warping power output; flight at FTL; near-omnipotence in the 853rd century",
    weaknesses: "Pacifist tendencies; magic still bites; rust on the human side after eons in the sun",
    description: "Kal-El after spending the better part of a thousand years inside the sun — the platonic ideal of Superman." },
  { name: "Goku (Ultra Instinct)", universe: "Dragon Ball",
    strength: 99, speed: 100, intelligence: 80, durability: 98,
    specialAbility: "Body moves on its own — perfect autonomous reaction; god-tier ki; instant transmission; silver-haired Mastered UI",
    weaknesses: "Form drops if he thinks too hard; stamina cost is brutal; still naive in tactics",
    description: "Goku at the limit of mortal potential — a state where the body fights faster than the mind can follow." },
  { name: "Goku Black", universe: "Dragon Ball",
    strength: 96, speed: 96, intelligence: 88, durability: 96,
    specialAbility: "Saiyan god body stolen by Zamasu; energy scythe; rose-form transformations; grows stronger from injury",
    weaknesses: "Time-ring dependency; god-complex makes him predictable; can be sealed",
    description: "Zamasu wearing Goku's face — a self-styled god determined to scrub mortals from existence with a smile." },
  { name: "Rengoku", universe: "Demon Slayer",
    strength: 84, speed: 88, intelligence: 80, durability: 78,
    specialAbility: "Flame Breathing — all nine forms; total concentration constant; sun-bright slashes that burn demons",
    weaknesses: "Mortal stamina; outclassed by the strongest Upper Moons; refuses to retreat",
    description: "Kyojuro Rengoku — Flame Hashira whose burning heart blazed even at the end. 'Set your heart ablaze.'" },
  { name: "Vegeta (Ultra Ego)", universe: "Dragon Ball",
    strength: 97, speed: 94, intelligence: 86, durability: 99,
    specialAbility: "God of Destruction technique; the more damage he takes, the stronger he gets; purple aura juggernaut mode",
    weaknesses: "Form requires being battered to peak out; pride still betrays him",
    description: "Vegeta's answer to Ultra Instinct — embrace the damage, smile through the punches, hit back twice as hard." },
  { name: "Kratos (Ragnarok)", universe: "God of War",
    strength: 96, speed: 88, intelligence: 84, durability: 96,
    specialAbility: "Leviathan Axe with frost; Blades of Chaos; Spartan Rage; Draupnir Spear; Norse god-killing experience",
    weaknesses: "Father-figure restraint now blunts his rage; old injuries; refuses to be a god again",
    description: "Older, wiser Kratos in the Norse realms — still murders gods but is trying very hard not to teach his son to." },
  { name: "Kratos (Young)", universe: "God of War",
    strength: 92, speed: 92, intelligence: 76, durability: 90,
    specialAbility: "Blades of Chaos; god-killer berserker rage; Greek god powers stolen as he climbs Olympus",
    weaknesses: "Pure rage clouds tactics; haunted by the murder of his family; refuses to die",
    description: "The Ghost of Sparta in his Greek prime — pale-skinned wrath ascending Mount Olympus to murder a pantheon." },
  { name: "Kratos vs Zeus (Composite)", universe: "God of War",
    strength: 98, speed: 92, intelligence: 84, durability: 97,
    specialAbility: "Blades of Olympus; rage of all gods absorbed; Hope unleashed; god-slaying composite of his entire arsenal",
    weaknesses: "Composite power demands a price in pain; nothing he loves survives him",
    description: "Kratos as he was when he tore Zeus in half — every god murdered, every weapon won, every grudge lit." },
  { name: "Naruto", universe: "Naruto",
    strength: 80, speed: 86, intelligence: 70, durability: 84,
    specialAbility: "Rasengan; Shadow Clone Jutsu; Nine-Tails chakra cloak; Sage Mode; tactical clone-swarms",
    weaknesses: "Tactically straightforward; chakra burnout if he over-clones; will protect a friend over a strategy",
    description: "Naruto Uzumaki — orphan, prankster, jinchūriki of the Nine-Tails. Talks his enemies into being friends." },
  { name: "Naruto (Baryon Mode)", universe: "Naruto",
    strength: 99, speed: 100, intelligence: 80, durability: 96,
    specialAbility: "Fuses his chakra with Kurama's into a fusion-reactor state — drains lifespan instead of chakra; god-tier strikes",
    weaknesses: "Burns Kurama and his own life as fuel; finite duration before death is the cost",
    description: "Naruto's terminal-throttle mode — burning years off his life with every punch to match Isshiki." },
  { name: "Naruto (Six Paths)", universe: "Naruto",
    strength: 97, speed: 98, intelligence: 86, durability: 96,
    specialAbility: "Six Paths Sage Mode — Truth-Seeking Orbs, all nine tailed beasts' chakra, flight, sealing jutsu",
    weaknesses: "Chakra reserves can be drained; emotional decisions; reliant on belief in his bonds",
    description: "Hagoromo's chosen — Naruto with the chakra of every tailed beast and the will of the Sage of Six Paths." },
  { name: "Sasuke (Six Paths)", universe: "Naruto",
    strength: 94, speed: 97, intelligence: 92, durability: 92,
    specialAbility: "Rinnegan with Six Paths chakra; Amaterasu; Susanoo; space-time ninjutsu; Indra's chakra",
    weaknesses: "Eye-strain over long fights; emotional baggage with Itachi/Naruto; one-armed in his peak era",
    description: "Sasuke awakened as Indra's heir — Rinnegan in one eye, Sharingan in the other, and a single hand." },
  { name: "Luffy (Gear 5)", universe: "One Piece",
    strength: 99, speed: 95, intelligence: 78, durability: 98,
    specialAbility: "Sun God Nika awakening; cartoon-physics rubber reality; environment becomes rubber; Bajrang Gun",
    weaknesses: "Form drains his life force on awakening; reverts when stamina ends; impulsive leader",
    description: "Luffy unleashing his Devil Fruit's true name — Nika, the Sun God, who fights with the freedom of laughter." },

  // ── Sequential mass-add ─────────────────────────────────────────────────────
  { name: "6teen Jonesy", universe: "6teen",
    strength: 60, speed: 65, intelligence: 60, durability: 58,
    specialAbility: "Gets and loses jobs at every store in the mall; mall-rat improvisation",
    weaknesses: "Distracted by women; chronically unemployed; no real combat training",
    description: "Mall employee #1 of the Galleria — Jonesy Garcia, a teenager whose only superpower is failing job interviews stylishly." },
  { name: "6teen Nikki", universe: "6teen",
    strength: 58, speed: 65, intelligence: 75, durability: 60,
    specialAbility: "Sarcasm at lethal range; works at the Khaki Barn under protest; cool-headed sass",
    weaknesses: "Hates her job more than she fights; not a fighter at all",
    description: "Nikki Wong — sardonic mall teen forced to fold polos for a living, throws shade like throwing knives." },
  { name: "A-Bomb", universe: "Marvel",
    strength: 95, speed: 78, intelligence: 70, durability: 96,
    specialAbility: "Hulk-level gamma strength; armored blue scales; chameleon camouflage; Rick Jones brain",
    weaknesses: "Less raw rage than Hulk; relies on Hulk-Family teamwork; wisecracks at the worst times",
    description: "Rick Jones turned into a blue, armor-plated Hulk variant who never quite stopped being Rick Jones." },
  { name: "A-Train", universe: "The Boys",
    strength: 80, speed: 99, intelligence: 65, durability: 78,
    specialAbility: "Compound-V super-speed; supersonic punches; mid-stride pulps an unfortunate girl named Robin",
    weaknesses: "Heart problems from chronic Compound-V abuse; ego; cowardice at the wrong moments",
    description: "Reggie Franklin — Vought's fastest man, a coward in a track suit who runs from his own conscience faster than his enemies." },
  { name: "A.K.I", universe: "Street Fighter",
    strength: 72, speed: 86, intelligence: 80, durability: 70,
    specialAbility: "Poison-coated nails and breath; serpentine grappling; F.A.N.G's apprentice in venom mastery",
    weaknesses: "Light defensive build; antitoxin counters her arsenal; obsessive devotion to her master",
    description: "F.A.N.G's protégé — a giddy poison artist who paints her enemies' deaths with toxin and a smile." },
  { name: "Aang (Nick)", universe: "Avatar: The Last Airbender",
    strength: 70, speed: 92, intelligence: 84, durability: 78,
    specialAbility: "All four bending arts; Avatar State channeling past lives; energybending to take or restore powers",
    weaknesses: "Pacifist by nature; Avatar State leaves chakra-point vulnerability; 12-year-old judgment",
    description: "The Last Airbender as he aired on Nickelodeon — the Avatar with the laugh of a child and the soul of a thousand sages." },
  { name: "Abaddon", universe: "Supernatural",
    strength: 88, speed: 80, intelligence: 88, durability: 90,
    specialAbility: "Knight of Hell; possession; telekinesis; immune to most demonic killers; immortality short of an angel blade",
    weaknesses: "First Blade with the Mark of Cain; angelic weapons; sealed by archangel power",
    description: "A Knight of Hell uncorked from a millennium-long sleep — Abaddon wants Hell's throne and will burn earth to take it." },
  { name: "Abel", universe: "Mythology",
    strength: 60, speed: 60, intelligence: 65, durability: 58,
    specialAbility: "First innocent; martyr's blood that cried from the ground; symbol of righteous shepherding",
    weaknesses: "Trusted his brother; entirely mortal; defenseless against betrayal",
    description: "The first murdered man in scripture — Adam's son, slain by his brother Cain over a sacrifice." },
  { name: "Achilles (Myth)", universe: "Greek Mythology",
    strength: 92, speed: 95, intelligence: 78, durability: 95,
    specialAbility: "Styx-dipped near-invulnerability; spear and xiphos mastery; berserker rage that decides wars",
    weaknesses: "Heel was held when his mother dipped him — a single mortal point on an immortal body",
    description: "The greatest warrior of the Achaean army — a demigod whose only flaw was the heel his mother gripped." },
  { name: "Adventure Time", universe: "Adventure Time",
    strength: 78, speed: 80, intelligence: 65, durability: 78,
    specialAbility: "Stretchy hero powers as Finn and Jake fused — magic swords; magic dog stretch; mathematical hero spirit",
    weaknesses: "Reckless heroics; ignores tactics for vibes; Finn's mortal fragility under the bravado",
    description: "The composite spirit of Finn the Human and Jake the Dog — an algebraic hero of the Land of Ooo." },
  { name: "Aizen (Final Form)", universe: "Bleach",
    strength: 96, speed: 96, intelligence: 99, durability: 98,
    specialAbility: "Hōgyoku-fused transcendent form; complete hypnosis Kyōka Suigetsu; reality-altering presence; near-immortality",
    weaknesses: "Mugetsu (Final Getsuga); Yhwach's All Almighty; arrogance taken to cosmic levels",
    description: "Sōsuke Aizen merged with the Hōgyoku into a butterfly-winged transcendent — a being above shinigami and hollows alike." },
  { name: "Akaza (Upper Moon 3)", universe: "Demon Slayer",
    strength: 92, speed: 94, intelligence: 80, durability: 92,
    specialAbility: "Destructive Death martial arts; compass-needle combat sense; demon regeneration; refuses women and weak fighters",
    weaknesses: "Sunlight; Nichirin blades to the neck; haunted by his human past",
    description: "Upper Moon Three — a martial artist demon obsessed with strength, who will not strike a woman or a weakling." },
  { name: "Akira", universe: "Akira",
    strength: 85, speed: 75, intelligence: 70, durability: 80,
    specialAbility: "Reality-shattering psychic power; biomass overflow; can wipe Neo-Tokyo off the map",
    weaknesses: "Power destroys his own body; in stasis as a child; can be sealed",
    description: "The boy whose psychic awakening leveled Tokyo — a god in a child's body kept frozen until needed." },
  { name: "Aku (CN)", universe: "Samurai Jack",
    strength: 95, speed: 88, intelligence: 92, durability: 98,
    specialAbility: "Shapeshifting shadow demon; reality manipulation; time travel; energy beams from any orifice",
    weaknesses: "Jack's enchanted katana; light-magic; cannot resist gloating",
    description: "The Shogun of Sorrow — a shapeshifting embodiment of evil who conquered the future and sent Samurai Jack into it." },
  { name: "Alex", universe: "Street Fighter",
    strength: 88, speed: 78, intelligence: 70, durability: 84,
    specialAbility: "American wrestling powerhouse; Power Bomb; Flash Chop; Air Stampede; pro-wrestling slams",
    weaknesses: "Slow; slugger archetype; takes hits to give them",
    description: "The brawler-wrestler hero of Street Fighter III — Alex throws people around like he's still in a Manhattan ring." },
  { name: "Alien", universe: "Alien",
    strength: 86, speed: 88, intelligence: 70, durability: 78,
    specialAbility: "Acid blood; inner jaw; tail spike; perfect organism stalking in air ducts",
    weaknesses: "Vacuum exposure; flame; large-caliber weapons concentrated on the head",
    description: "The Xenomorph drone — a perfect organism whose first move is always from the ceiling." },
  { name: "Alien Chestburster", universe: "Alien",
    strength: 30, speed: 60, intelligence: 30, durability: 25,
    specialAbility: "Bursts from a host's chest; rapid maturation into a full Xenomorph",
    weaknesses: "Newborn; defenseless if intercepted before molting",
    description: "The screaming larval form that erupts from your friends — a Xenomorph in its first thirty terrible seconds." },
  { name: "Alien Facehugger", universe: "Alien",
    strength: 40, speed: 75, intelligence: 25, durability: 30,
    specialAbility: "Pounces; clamps over the face; impregnates host with embryo; acid blood",
    weaknesses: "Removable in a window before implantation kills the host; flame; brief lifespan",
    description: "Eight-legged horror with one job: get on your face, lay an egg, and be remembered forever." },
  { name: "Alien X", universe: "Ben 10",
    strength: 100, speed: 100, intelligence: 100, durability: 100,
    specialAbility: "Celestialsapien — reality warping at the omnipotent level; controlled by an internal vote of personalities",
    weaknesses: "The internal personalities argue forever; nothing happens unless two of three agree",
    description: "Ben Tennyson's most powerful and least usable form — a god in committee, debating itself into paralysis." },
  { name: "Alita: Battle Angel", universe: "Alita",
    strength: 88, speed: 95, intelligence: 86, durability: 86,
    specialAbility: "Berserker cyborg body; Panzer Kunst martial art; Damascus blade; combat instincts pre-Fall",
    weaknesses: "Body is replaceable but heart is not; vulnerable to power-source overload",
    description: "A cyborg girl from before the Fall — Alita fights with the muscle memory of a war that ended centuries ago." },
  { name: "Alucard (Level 0)", universe: "Hellsing",
    strength: 99, speed: 96, intelligence: 95, durability: 99,
    specialAbility: "All souls released; Schrödinger immortality via being everywhere; army of the damned; Bram Stoker's terror unbound",
    weaknesses: "Self-imposed restrictions when Integra commands; bound to Hellsing org; vulnerable to losing his anchor",
    description: "Alucard with every restriction released — the No-Life King unleashing every soul he ever consumed at once." },
  { name: "Amanda Young", universe: "Saw",
    strength: 60, speed: 65, intelligence: 78, durability: 58,
    specialAbility: "Trap-builder apprentice to Jigsaw; pig-mask abductor; psychological manipulation",
    weaknesses: "Drug-addiction history; emotionally compromised; weak in direct combat",
    description: "Jigsaw's traumatized apprentice — a survivor of his trap who became one of his most loyal disciples." },
  { name: "Amara", universe: "Supernatural",
    strength: 100, speed: 95, intelligence: 95, durability: 100,
    specialAbility: "The Darkness — God's elder sister; primordial entity; reality consumption; existed before existence",
    weaknesses: "Bond with Dean; only God or her own choice can rebind her",
    description: "The primordial Darkness — the only being older than God, and the only one who can hurt Him." },
  { name: "Android 17", universe: "Dragon Ball",
    strength: 92, speed: 94, intelligence: 82, durability: 94,
    specialAbility: "Infinite energy core; barrier shielding; Photon Flash; ranger-trained tactical fighter",
    weaknesses: "Less raw power than late-Z foes; protective of his family/island",
    description: "Lapis — Dr. Gero's eternal android, a park ranger with an infinite energy reactor and a quiet wife." },
  { name: "Android 18", universe: "Dragon Ball",
    strength: 90, speed: 92, intelligence: 82, durability: 92,
    specialAbility: "Infinite energy reserves; Energy Wave; Power Blitz; out-fights most Z fighters at base",
    weaknesses: "Vulnerable when defending Marron or Krillin; dislikes prolonged fights",
    description: "Lazuli — the cybernetic punch-line who married Krillin and outlives gods on a battery that never dies." },
  { name: "Annabelle", universe: "The Conjuring",
    strength: 65, speed: 50, intelligence: 70, durability: 75,
    specialAbility: "Demon-bound porcelain doll; possesses victims; conjures hauntings; immune to physical destruction",
    weaknesses: "Sealed in blessed glass; priests with proper rites; faith-based wards",
    description: "A sweet-faced doll possessed by a malevolent inhuman spirit — the Warrens kept her behind glass for a reason." },
  { name: "Annie Leonhart", universe: "Attack on Titan",
    strength: 85, speed: 84, intelligence: 86, durability: 85,
    specialAbility: "Female Titan transformation; hardening abilities; military hand-to-hand; ODM gear elite",
    weaknesses: "Hardening costs energy; sentimental loyalties; can be encased in crystal",
    description: "The Female Titan shifter — a quiet trainee who turned out to be the operative who broke Wall Maria's defenders." },
  { name: "Anthony Joshua", universe: "Boxing",
    strength: 84, speed: 78, intelligence: 70, durability: 82,
    specialAbility: "Heavyweight champion power punching; Olympic gold-medal fundamentals; chin of British steel",
    weaknesses: "Slows in late rounds; vulnerable to lateral movement and pressure",
    description: "Olympic gold medalist and unified heavyweight champ — a 240-pound knockout artist with a pristine jab." },
  { name: "Anti-Monitor (Crisis)", universe: "DC",
    strength: 100, speed: 100, intelligence: 98, durability: 100,
    specialAbility: "Crisis-era reality eraser; consumed entire universes; antimatter manipulation; cosmic balance breaker",
    weaknesses: "The Spectre at full power; the Anti-Life Equation paradox; combined Multiverse heroes",
    description: "The being that ate the multiverse during Crisis on Infinite Earths — antimatter incarnate." },
  { name: "Apex Bloodhound", universe: "Apex Legends",
    strength: 70, speed: 80, intelligence: 84, durability: 70,
    specialAbility: "Eye of the Allfather tracking — sees recent paths; Beast of the Hunt ultra-vision; Norse-tech tracker",
    weaknesses: "Beast of the Hunt has cooldown; standard mortal durability",
    description: "Technological tracker of the Apex Games — Bloodhound reads footprints like a god and hunts in red vision." },
  { name: "Apex Revenant", universe: "Apex Legends",
    strength: 86, speed: 86, intelligence: 80, durability: 88,
    specialAbility: "Simulacrum body; Death Totem revival; silenced abilities of others; centuries of assassin programming",
    weaknesses: "Death Totem has range and cooldown; programmed to obey his maker",
    description: "A 300-year-old assassin trapped in a simulacrum body — Revenant kills slowly because he has the time." },
  { name: "Apex Wraith", universe: "Apex Legends",
    strength: 70, speed: 84, intelligence: 88, durability: 72,
    specialAbility: "Phase shift through dimensions; Voices in her head warn of danger; portal placement",
    weaknesses: "Phase windows are brief; tactical voice can be silenced",
    description: "An interdimensional skirmisher of the Apex Games — Wraith vanishes mid-stride into the Void and out the other side." },
  { name: "Arbiter (Elite)", universe: "Halo",
    strength: 86, speed: 84, intelligence: 84, durability: 86,
    specialAbility: "Energy sword mastery; active camouflage; Sangheili warrior tradition; commander-tier tactics",
    weaknesses: "Honor-bound; refuses certain tactics; armor breaches under sustained fire",
    description: "Thel 'Vadam — disgraced Sangheili commander turned Arbiter, sword-master who crossed the line to fight Truth." },
  { name: "Ares (Myth)", universe: "Greek Mythology",
    strength: 96, speed: 90, intelligence: 70, durability: 95,
    specialAbility: "God of bloodlust; immortal; weapons mastery; revels in slaughter and chaos",
    weaknesses: "Disliked by every other Olympian; mortal weapons can wound him; pride drives bad decisions",
    description: "The original Greek god of war — savage, despised, and absolutely there for the carnage." },
  { name: "Armin Arlert", universe: "Attack on Titan",
    strength: 88, speed: 80, intelligence: 96, durability: 86,
    specialAbility: "Colossal Titan inheritor; nuclear-tier transformation; tactical genius even in human form",
    weaknesses: "Transformation requires self-sacrifice; small stamina pool human-side; emotional",
    description: "The strategist of the 104th — a soft-spoken boy who inherited the Colossal Titan and out-thinks his enemies." },
  { name: "Art the Clown", universe: "Terrifier",
    strength: 80, speed: 75, intelligence: 70, durability: 88,
    specialAbility: "Inhuman resilience; gleeful murder spree creativity; mute pantomime intimidation",
    weaknesses: "Decapitation slows but does not stop him; vulnerable to overwhelming firepower",
    description: "A silent killer clown who treats every massacre like a stage show — comes back from death just to ruin Halloween." },
  { name: "Asami Yamazaki", universe: "Audition",
    strength: 60, speed: 70, intelligence: 80, durability: 58,
    specialAbility: "Acupuncture-needle paralysis; piano-wire amputations; soft voice that hides a butcher",
    weaknesses: "Physically frail; relies on bound or sedated victims",
    description: "Asami of Audition — the doll-soft killer who whispers 'kiri kiri kiri' as she removes a man's foot." },
  { name: "Ash Williams (Necronomicon)", universe: "Evil Dead",
    strength: 78, speed: 75, intelligence: 76, durability: 80,
    specialAbility: "Necronomicon-attuned chosen one; chainsaw-arm; boomstick; hero's quip-per-kill ratio",
    weaknesses: "Cocky; misreads ancient incantations constantly; mortal flesh under the bravado",
    description: "Ashley Williams with the Book of the Dead in his other hand — chosen to fight Deadites whether he likes it or not." },
  { name: "Ashrah", universe: "Mortal Kombat",
    strength: 80, speed: 88, intelligence: 78, durability: 78,
    specialAbility: "Light-magic Kriss sword purifies demonic foes; teleportation; Edenian/Netherrealm hybrid combatant",
    weaknesses: "Kriss must feed on evil souls; corruption risk if she stops killing demons",
    description: "A demon hunter who hunts demons because killing them slowly purifies her own corrupted soul." },
  { name: "Aslan", universe: "Narnia",
    strength: 95, speed: 88, intelligence: 96, durability: 95,
    specialAbility: "Deeper Magic from Before the Dawn of Time; resurrection; breath that creates worlds; lion-god authority",
    weaknesses: "Submits to ancient laws; chooses sacrifice over force",
    description: "The great lion who sang Narnia into being — a god in a mane, who would die to save a child and walk back from it." },
  { name: "Asura's Wrath", universe: "Asura's Wrath",
    strength: 99, speed: 95, intelligence: 75, durability: 100,
    specialAbility: "Six-armed Mantra rage form; Destructor scaled to planets; refuses to die while there is anything to punch",
    weaknesses: "Rage burns through Mantra reserves; daughter is his weak point",
    description: "Asura at full Destructor scale — a wrath-god who punches a finger off Vlitra and dares the universe to try him." },
  { name: "Atreus (Ragnarok)", universe: "God of War",
    strength: 80, speed: 88, intelligence: 84, durability: 78,
    specialAbility: "Loki — Jötunn lineage; Talon Bow; shapeshifting; runic arrows; spartan rage inheritance",
    weaknesses: "Teenager judgment; still learning his powers; emotional decisions",
    description: "Loki of the Norse — Kratos's son, a Jötunn prince figuring out what kind of god to be." },
  { name: "Azathoth", universe: "Cthulhu Mythos",
    strength: 100, speed: 80, intelligence: 1, durability: 100,
    specialAbility: "Blind idiot god dreaming the universe — reality is his sleep; awakening unmakes existence",
    weaknesses: "Mindless; lulled by the piping of Ultimate Chaos; if he wakes, nothing including him survives",
    description: "The Daemon Sultan at the center of all infinity — a blind, gibbering god whose dreams are our universe." },
  { name: "Aztek", universe: "DC",
    strength: 78, speed: 80, intelligence: 88, durability: 82,
    specialAbility: "Quetzalcoatl helm — fourth-dimensional sight; Plasma blasts; energy shields; trained from birth to kill Tezcatlipoca",
    weaknesses: "Helm gives migraines and visions; suit's power core is finite",
    description: "Curt Falconer — DC's chosen weapon against the dark god Tezcatlipoca, raised from infancy in a sun-cult bunker." },
  { name: "Babadook", universe: "The Babadook",
    strength: 75, speed: 70, intelligence: 75, durability: 85,
    specialAbility: "Pop-up book entity; manifests grief and rage as monster; cannot be killed, only contained",
    weaknesses: "Bound to the basement of those who acknowledge it; subdued, never destroyed",
    description: "A grief-shaped specter from a children's book — once you let it in, you only learn to live with it." },
  { name: "Baki", universe: "Baki the Grappler",
    strength: 88, speed: 90, intelligence: 80, durability: 88,
    specialAbility: "Underground grappling — demonic shadow technique; pain tolerance off the charts; Yujiro's son",
    weaknesses: "Mortal frame; obsessed with surpassing his father; takes hits to learn",
    description: "Baki Hanma in his Grappler peak — a teenager engineered by genetics and obsession into Earth's deadliest brawler." },
  { name: "Balrog", universe: "Lord of the Rings",
    strength: 95, speed: 75, intelligence: 78, durability: 92,
    specialAbility: "Maia of fire and shadow; flaming whip and sword; aura of dread; ancient Morgoth-corrupted demon",
    weaknesses: "Vulnerable to Maia of equal stature (Gandalf); ice and water dampen flame",
    description: "Durin's Bane — a demon of the ancient world, loosed from the deeps of Khazad-dûm. 'You shall not pass.'" },
  { name: "Baraka", universe: "Mortal Kombat",
    strength: 86, speed: 84, intelligence: 70, durability: 84,
    specialAbility: "Tarkatan blade-arms; chop-chop fatality; rabid Outworld nomad; bites through bone",
    weaknesses: "Berserker style; outclassed by sorcerers; self-destructive in rage",
    description: "Tarkatan warlord — a fanged nomad whose forearm-blades make every handshake a beheading." },
  { name: "Barbarian Mother", universe: "Barbarian",
    strength: 90, speed: 70, intelligence: 50, durability: 92,
    specialAbility: "Inhuman strength from generations of inbreeding; protective of her 'babies'; bare-handed devastation",
    weaknesses: "Limited intellect; childlike emotional volatility; can be lured",
    description: "The Mother from the basement — a feral woman raised in darkness who breastfeeds her victims into compliance." },
  { name: "Bart Simpson", universe: "The Simpsons",
    strength: 50, speed: 65, intelligence: 70, durability: 60,
    specialAbility: "Slingshot precision; prank tactics; underdog escape artist; surprisingly resilient skull",
    weaknesses: "10-year-old; chronically grounded; allergic to homework",
    description: "Bart Simpson — eternal fourth-grader, prank artist of Springfield, eat my shorts." },
  { name: "Bathsheba Sherman", universe: "The Conjuring",
    strength: 78, speed: 70, intelligence: 80, durability: 88,
    specialAbility: "Witch-spirit possession; cursed bloodline; murders mothers and steals their bodies; unkillable in spirit form",
    weaknesses: "Banishment via love-bond confrontation; blessed objects",
    description: "The witch of the Perron farmhouse — a Salem-era curse who haunts mothers and rides them to murder their own children." },
  { name: "Batwing", universe: "DC",
    strength: 78, speed: 84, intelligence: 86, durability: 84,
    specialAbility: "Wayne-tech battle suit; flight; African Bat-team operative; military training",
    weaknesses: "Suit-dependent; tech can be hacked; less iconic than Bat-family seniors",
    description: "David Zavimbe / Luke Fox — the Batman of Africa in a flight-capable Wayne Industries combat suit." },
  { name: "Beerus (God)", universe: "Dragon Ball",
    strength: 99, speed: 96, intelligence: 90, durability: 99,
    specialAbility: "God of Destruction Hakai — erases existence with a touch; full god ki; cat-nap supremacy",
    weaknesses: "Lazy; loses to Whis in sparring; tied to a Supreme Kai's life force",
    description: "Lord Beerus — destroyer of Universe 7, who would rather sleep than show up but wakes for good food and fights." },
  { name: "Ben 10", universe: "Ben 10",
    strength: 85, speed: 85, intelligence: 80, durability: 85,
    specialAbility: "Omnitrix unlocks dozens of alien forms; tactical form-switching mid-combat",
    weaknesses: "Omnitrix has cooldowns and timeouts; teenage decision-making",
    description: "Ben Tennyson and the Omnitrix — a teenager with a wrist-watch that turns him into an alien army of one." },
  { name: "Ben 10 (Alien X Full)", universe: "Ben 10",
    strength: 100, speed: 100, intelligence: 100, durability: 100,
    specialAbility: "Full mastery of Celestialsapien Alien X — omnipotent reality warping without the internal vote",
    weaknesses: "Conceptual paradoxes; Ben's still a kid making cosmic decisions",
    description: "Ben Tennyson with full unrestricted control of Alien X — a teenager with the keys to omnipotence." },
  { name: "Ben Tennyson", universe: "Ben 10",
    strength: 80, speed: 80, intelligence: 78, durability: 80,
    specialAbility: "Omnitrix — instant alien transformation library; combat experience across thousands of forms",
    weaknesses: "Has to remember which form; overconfidence; Omnitrix lockouts",
    description: "Ben Tennyson — wielder of the Omnitrix and self-appointed defender of the galaxy in his free time." },
  { name: "Bender", universe: "Futurama",
    strength: 82, speed: 70, intelligence: 78, durability: 86,
    specialAbility: "Bending unit body — bends girders; built-in arsenal; nigh-indestructible alloy chassis",
    weaknesses: "Magnets scramble him; alcohol-powered (also a feature); morally bankrupt",
    description: "Bender Bending Rodríguez — industrial bending unit, kleptomaniac, and the closest thing 3000 has to a folk hero." },
  { name: "Bender (Bite My Shiny Metal)", universe: "Futurama",
    strength: 84, speed: 72, intelligence: 80, durability: 88,
    specialAbility: "Catchphrase-mode Bender — kill-all-humans subroutine; full chassis arsenal deployed",
    weaknesses: "Magnets; ego; bites his own ass mid-quip",
    description: "Bender at his most quotable — chassis upgraded by attitude. Bite his shiny metal... rear bumper." },
  { name: "Beth Smith", universe: "Rick and Morty",
    strength: 65, speed: 65, intelligence: 88, durability: 65,
    specialAbility: "Horse surgeon; daughter of Rick Sanchez; either a clone or the original (unresolved)",
    weaknesses: "Drinks; existential identity crisis; dad issues weaponized",
    description: "Beth Sanchez-Smith — Rick's brilliant daughter, a horse surgeon who may or may not be a clone of herself." },
  { name: "Big Mom (Full Power)", universe: "One Piece",
    strength: 99, speed: 88, intelligence: 86, durability: 99,
    specialAbility: "Soul-Soul Fruit — steals lifespan; homies (animated soul-objects); Yonko-tier physical strength; Conqueror's Haki",
    weaknesses: "Cravings make her berserk and erratic; Prometheus and Zeus separable",
    description: "Charlotte Linlin at full Yonko power — a giantess who steals years from people and feeds them to her tea." },
  { name: "Billy", universe: "Saw",
    strength: 30, speed: 60, intelligence: 65, durability: 50,
    specialAbility: "Animatronic puppet; trike mobility; delivers Jigsaw's recordings",
    weaknesses: "Inanimate without operator; smashable",
    description: "The grinning puppet on the tricycle — Jigsaw's mascot of mortality. Hello, would you like to play a game?" },
  { name: "Billy the Puppet", universe: "Saw",
    strength: 30, speed: 60, intelligence: 65, durability: 50,
    specialAbility: "Iconic Jigsaw puppet — delivers death-sentencing TV recordings; psychological terror by association",
    weaknesses: "Inanimate; relies on traps and operator",
    description: "Billy the Puppet — Jigsaw's red-cheeked herald. The trike is optional, the dread is included." },
  { name: "Black Adam (Magic Form)", universe: "DC",
    strength: 99, speed: 95, intelligence: 86, durability: 99,
    specialAbility: "Shazam magic of the Egyptian gods — Shu, Heru, Amon, Zehuti, Aton, Mehen; flight; lightning; near-Superman tier",
    weaknesses: "Magic word reverts him to mortal Teth-Adam; emotional volatility over Khandaq",
    description: "Teth-Adam at full magic power — Khandaq's avenging god-king who answers prayers with thunderbolts." },
  { name: "Black Noir", universe: "The Boys",
    strength: 90, speed: 90, intelligence: 80, durability: 92,
    specialAbility: "Silent assassin Supe — equal to Homelander in skill; ninja-tier weapon mastery; near-invulnerability",
    weaknesses: "Severe brain trauma left him child-like; tree-nut allergy infamously fatal",
    description: "The masked silent killer of the Seven — Vought's surgical strike in human form, undone in canon by an Almond Joy." },
  { name: "Blade (Daywalker)", universe: "Marvel",
    strength: 86, speed: 90, intelligence: 84, durability: 88,
    specialAbility: "Daywalker hybrid — vampire strength without the sun weakness; sword and gun mastery; vampire instincts",
    weaknesses: "Thirst suppressant addiction; silver still bites; older vampire lords match him",
    description: "Eric Brooks — half-vampire, all hunter, the Daywalker who treats vampire kind like a personal infestation." },
  { name: "Blade Vampire", universe: "Marvel",
    strength: 80, speed: 84, intelligence: 76, durability: 78,
    specialAbility: "Generic vampire — bite, mesmerize, regenerate from most wounds, super strength",
    weaknesses: "Sunlight; silver; decapitation; staking the heart; garlic in some traditions",
    description: "A standard vampire of the Blade-verse — the kind of nightclub goon Blade clears a building of in a montage." },
  { name: "Blanka", universe: "Street Fighter",
    strength: 85, speed: 86, intelligence: 65, durability: 84,
    specialAbility: "Electric Thunder shock; Rolling Attack ball-spin; jungle-feral combat; bestial regeneration",
    weaknesses: "Limited technical training; aerial opponents; controlled fighters who avoid the rush",
    description: "Jimmy Blanka — green-skinned electric beast-man raised in the Brazilian jungle, who hugs his mom and electrocutes everyone else." },
  { name: "Blaze", universe: "Mortal Kombat",
    strength: 96, speed: 78, intelligence: 75, durability: 96,
    specialAbility: "Elder God-blessed firegod; Armageddon endgame fighter; massive form; pyromancy mastery",
    weaknesses: "Slow; one-shot bosses can be overwhelmed; bound to Armageddon ritual",
    description: "The flame-elemental boss of Mortal Kombat: Armageddon — a giant Elder-blessed combatant atop the Pyramid of Argus." },
  { name: "Bling Bling Boy", universe: "Johnny Test",
    strength: 70, speed: 60, intelligence: 90, durability: 75,
    specialAbility: "Tech-billionaire genius; powered combat suit; obsession-driven schemes for Susan Test",
    weaknesses: "Lovesick; suit gimmickry over substance; foiled by twin scientists weekly",
    description: "Eugene Hamilton — Johnny Test's tech-genius rival, perpetually scheming to win Susan Test's heart with another suit." },
  { name: "Bloodborne Hunter", universe: "Bloodborne",
    strength: 86, speed: 88, intelligence: 80, durability: 84,
    specialAbility: "Trick weapons; Quicksilver bullets; blood-echo regeneration; visceral attacks; insight grants cosmic dread",
    weaknesses: "Insight reveals horrors that wound the mind; humanity loss to beasthood",
    description: "A hunter of the Yharnam Dream — wielder of saw-cleavers and bloodborne madness, paid in echoes of dying gods." },
  { name: "Blossom", universe: "The Powerpuff Girls",
    strength: 85, speed: 90, intelligence: 90, durability: 85,
    specialAbility: "Ice breath; flight; super strength; tactical leader of the trio; sugar/spice/everything-nice composition",
    weaknesses: "Bossy with sisters; emotional under pressure; chemical X dependency",
    description: "Blossom — the leader of the Powerpuff Girls, ice-breathing brain of Townsville's pint-sized defense squad." },
  { name: "Bo Rai Cho", universe: "Mortal Kombat",
    strength: 84, speed: 76, intelligence: 86, durability: 86,
    specialAbility: "Drunken Fist mastery; Puke Puddle technique; Liu Kang's mentor; secretly devastating combatant",
    weaknesses: "Looks like a fool; alcohol fuels and impairs him; mortal stamina",
    description: "Liu Kang's fat, drunken master — a Drunken Fist grandmaster who weaponizes hiccups and mistaken assumptions." },
  { name: "Bobby Singer", universe: "Supernatural",
    strength: 65, speed: 60, intelligence: 92, durability: 70,
    specialAbility: "Hunter of decades; lore library; phone-network dispatcher; shotgun and salt mastery",
    weaknesses: "Aging human; bad knee; emotional surrogate dad to the Winchesters",
    description: "Bobby Singer — junkyard hunter, walking encyclopedia of monster lore, called 'idjit' as a term of endearment." },
  { name: "Booster Gold (Future)", universe: "DC",
    strength: 85, speed: 85, intelligence: 92, durability: 85,
    specialAbility: "Time-travel veteran; Skeets AI advisor; force fields; flight ring; secret-master-of-time arc",
    weaknesses: "Public reputation as a glory hound; isolated by his secret duty",
    description: "Booster Gold from the future — far more competent than his frat-boy reputation suggests, secretly saving timelines." },
  { name: "Boruto", universe: "Boruto",
    strength: 86, speed: 90, intelligence: 84, durability: 84,
    specialAbility: "Karma seal; Jōgan eye; Rasengan; Otsutsuki vessel powers; lightning chakra",
    weaknesses: "Karma slowly turns him into Momoshiki's vessel; teenage impulsiveness",
    description: "Boruto Uzumaki — Naruto's son, jinchūriki of an Otsutsuki invader written into his DNA." },
  { name: "Boruto Uzumaki", universe: "Boruto",
    strength: 86, speed: 90, intelligence: 84, durability: 84,
    specialAbility: "Karma; Jōgan; chakra mastery; Otsutsuki-tier potential; Sasuke-trained tactics",
    weaknesses: "Karma vessel risks; chakra exhaustion; rivalry with Kawaki blinds him",
    description: "Naruto's son carrying a Karma seal — a teenage shinobi with cosmic stakes carved into his hand." },
  { name: "Bourne", universe: "Bourne",
    strength: 80, speed: 88, intelligence: 92, durability: 78,
    specialAbility: "Treadstone conditioning; instant tactical assessment; weapons-improv; multilingual; CIA-killing experience",
    weaknesses: "Memory gaps; trauma; mortal stamina",
    description: "Jason Bourne — the CIA's most dangerous escaped asset, a man who can kill you with a magazine in any language." },
  { name: "Bowser (Giga)", universe: "Super Mario",
    strength: 99, speed: 70, intelligence: 70, durability: 99,
    specialAbility: "Building-sized rage form; volcanic fire breath; ground-shattering punches; near-kaiju scale",
    weaknesses: "Massive target; clumsy at scale; needs Fury Bowser power-up to trigger",
    description: "Bowser as a kaiju — Giga-sized, magma-veined, and ready to step on a kingdom or two." },
  { name: "Brian Griffin", universe: "Family Guy",
    strength: 50, speed: 65, intelligence: 88, durability: 55,
    specialAbility: "Talking dog; failed novelist; martini-sipping intellectual pretensions; bites strangers",
    weaknesses: "Alcoholism; insecure; very small dog; killed and resurrected at network whim",
    description: "Brian Griffin — the talking white Lab of Quahog, perpetual aspiring novelist with a martini in one paw." },
  { name: "Broly (Full Power)", universe: "Dragon Ball",
    strength: 100, speed: 96, intelligence: 70, durability: 99,
    specialAbility: "Legendary Super Saiyan limitless growth; Gigantic Meteor; immune to ki-loss caps; rage scales infinitely",
    weaknesses: "Mind unraveled by Goku-trauma trigger; Cheelai's voice can soothe him in DBS",
    description: "Broly the Legendary Super Saiyan unleashed — a green-haired engine of escalating destruction with no upper limit." },
  { name: "Bubbles", universe: "The Powerpuff Girls",
    strength: 85, speed: 90, intelligence: 75, durability: 85,
    specialAbility: "Sonic scream; multilingual (including Spanish, Japanese, and squirrel); flight; super strength",
    weaknesses: "Cries easily; emotionally tender; tied to her octopus Octi",
    description: "Bubbles — the joy of the Powerpuff Girls, blue-eyed innocence with a sonic scream that shatters cities." },
  { name: "Buttercup", universe: "The Powerpuff Girls",
    strength: 90, speed: 90, intelligence: 75, durability: 88,
    specialAbility: "Brawler of the trio; tongue rolling; flight; super strength; takes hits she could dodge for fun",
    weaknesses: "Hot-tempered; charges in; emotionally insecure under the toughness",
    description: "Buttercup — the toughest fighter of the Powerpuff Girls. Green is the color of bruises she's about to give you." },
  { name: "Butters Stotch", universe: "South Park",
    strength: 50, speed: 60, intelligence: 60, durability: 65,
    specialAbility: "Professor Chaos alter-ego; tinfoil-hat villainy; weirdly resilient against cosmic events",
    weaknesses: "Grounded constantly; pushover; existential dread of his parents",
    description: "Butters Stotch — South Park's eternal optimist whose alter ego, Professor Chaos, threatens the world weekly." },
  { name: "Byakuya (Bankai)", universe: "Bleach",
    strength: 88, speed: 92, intelligence: 88, durability: 86,
    specialAbility: "Senbonzakura Kageyoshi — thousand-blade petal storm; flash step; noble Kuchiki tradition",
    weaknesses: "Code of nobility limits ruthlessness; Bankai costs spiritual reserves",
    description: "Byakuya Kuchiki releasing his Bankai — a thousand cherry-blossom blades guided by aristocratic disdain." },
  { name: "C. Viper", universe: "Street Fighter",
    strength: 75, speed: 84, intelligence: 88, durability: 78,
    specialAbility: "Battle Suit — Burning Kick, Thunder Knuckle, Seismic Hammer; CIA operative undercover",
    weaknesses: "Suit-dependent; finite power core; mom-life balance",
    description: "Crimson Viper — CIA agent in a battle suit who fights Bison's syndicate while pretending to be a normal mother." },
  { name: "Cain", universe: "Mythology",
    strength: 80, speed: 70, intelligence: 76, durability: 90,
    specialAbility: "Mark of Cain — none who kill him survive; the First Murderer's curse; eternal wandering",
    weaknesses: "Marked by God; cursed to till barren earth; bound by his guilt",
    description: "The first murderer — Adam's son who slew Abel and was cursed by God to walk the earth marked." },
  { name: "Candyman", universe: "Candyman",
    strength: 88, speed: 75, intelligence: 80, durability: 92,
    specialAbility: "Hook-handed urban legend; bee-swarm body; summoned by saying his name five times in a mirror",
    weaknesses: "Bound to belief; banished if his story is corrected and re-told",
    description: "Daniel Robitaille — the painter lynched into legend, who answers anyone foolish enough to say his name." },
  { name: "Canelo Alvarez", universe: "Boxing",
    strength: 84, speed: 86, intelligence: 86, durability: 86,
    specialAbility: "Counter-puncher mastery; head-movement at elite level; multi-division world champion",
    weaknesses: "Activity drops in middle rounds; chin tested by giants",
    description: "Saúl Álvarez — the Mexican counter-puncher who has reigned across four divisions with a surgeon's precision." },
  { name: "Cartman (Coon)", universe: "South Park",
    strength: 60, speed: 60, intelligence: 78, durability: 70,
    specialAbility: "Coon persona — vigilante in a fursuit; manipulates the hero coalition; ego the size of Colorado",
    weaknesses: "Lazy; betrayed by his own greed; allergic to teamwork",
    description: "Eric Cartman as the Coon — a chubby fourth-grader in a raccoon costume who sees himself as a Marvel anti-hero." },
  { name: "Cassie Cage", universe: "Mortal Kombat",
    strength: 80, speed: 86, intelligence: 80, durability: 80,
    specialAbility: "Cage-family green energy; military Special Forces training; firearm mastery; selfie-fatality",
    weaknesses: "Younger than veteran fighters; brash; relationship drama with Jacqui",
    description: "Cassandra Carlton Cage — Johnny and Sonya's daughter, who inherited her dad's powers and her mom's discipline." },
  { name: "Castiel", universe: "Supernatural",
    strength: 88, speed: 88, intelligence: 88, durability: 90,
    specialAbility: "Angel of the Lord; smiting; teleportation; healing; angel-blade mastery; centuries of warrior duty",
    weaknesses: "Vessel-dependent; falls from grace cyclically; loves humans too much to be useful at heaven politics",
    description: "Castiel — the angel who pulled Dean Winchester from Hell and never quite went back to being a soldier of heaven." },
  { name: "Castlevania Dracula", universe: "Castlevania",
    strength: 92, speed: 88, intelligence: 90, durability: 92,
    specialAbility: "Lord of vampires; teleportation; hellfire summoning; castle reshaping; centuries of arcane mastery",
    weaknesses: "Vampire Killer whip lineage; sunlight; the Belmonts know his every move",
    description: "Vlad Țepeș — the Dragon, Lord of Castlevania, who keeps trying to end humanity and keeps getting whipped." },
  { name: "Cenobite", universe: "Hellraiser",
    strength: 80, speed: 70, intelligence: 88, durability: 88,
    specialAbility: "Hellish chains summoned to flay flesh; pleasure-and-pain mastery; Order of the Gash priest",
    weaknesses: "Bound by the Lament Configuration; banishable through the puzzle box reset",
    description: "A priest of the Order of the Gash — Cenobite explorer of the further regions of experience. Such sights to show you." },
  { name: "Cetrion", universe: "Mortal Kombat",
    strength: 92, speed: 86, intelligence: 95, durability: 92,
    specialAbility: "Elder Goddess — earth, wind, water, fire, life elemental control; merger with Kronika potential",
    weaknesses: "Bound to Kronika's plans; dies if Kronika dies",
    description: "Cetrion — Elder Goddess of virtue and Kronika's daughter, weaponizing the elements at goddess scale." },
  { name: "Chainsaw Man", universe: "Chainsaw Man",
    strength: 92, speed: 90, intelligence: 60, durability: 92,
    specialAbility: "Chainsaw Devil contract — chainsaws from his head and arms; eats devils to nullify them; primal heart-cord trigger",
    weaknesses: "Reliant on blood; loses fights when the blood pool dries; impulsive teenage Denji underneath",
    description: "Denji as the Chainsaw Devil — a starving boy whose pet devil became his heart and his head and his hands." },
  { name: "Chameleon", universe: "Mortal Kombat",
    strength: 80, speed: 86, intelligence: 78, durability: 78,
    specialAbility: "Cycles between male ninja palettes' powers — ice, fire, lightning, etc.; semi-invisible warrior",
    weaknesses: "Power cycle is timed; jack-of-all-trades, master of none",
    description: "An MK joke-character turned legend — a Lin Kuei-adjacent ninja who borrows every other ninja's powers in turn." },
  { name: "Chef", universe: "South Park",
    strength: 70, speed: 65, intelligence: 75, durability: 70,
    specialAbility: "Lunch-lady cooking; love-song wisdom; Vietnam-war veteran chef; community elder of South Park",
    weaknesses: "Mortal; brainwashed by Super Adventure Club in his finale arc",
    description: "Jerome 'Chef' McElroy — South Park Elementary's lunch chef and eternal source of awkwardly sexual life advice." },
  { name: "Chris Griffin", universe: "Family Guy",
    strength: 65, speed: 55, intelligence: 55, durability: 65,
    specialAbility: "Drawing talent; awkward teen strength; haunted by an evil monkey; surprisingly resilient",
    weaknesses: "Slow-witted; bullied; afraid of his own closet",
    description: "Chris Griffin — Peter and Lois's awkward teenage son, artist and target of an evil closet-monkey." },
  { name: "Chrollo", universe: "Hunter x Hunter",
    strength: 84, speed: 88, intelligence: 96, durability: 84,
    specialAbility: "Skill Hunter — steals Nen abilities into his book; Phantom Troupe leader; tactical genius",
    weaknesses: "Stolen abilities require conditions; book must be open; Kurta-clan grudge from Kurapika",
    description: "Chrollo Lucilfer — leader of the Phantom Troupe, a thief of Nen abilities and souls in equal measure." },
  { name: "Chucky", universe: "Child's Play",
    strength: 60, speed: 75, intelligence: 80, durability: 70,
    specialAbility: "Soul-transferred Good Guy doll; voodoo; combat knife; will not stop coming back",
    weaknesses: "Doll-sized; vulnerable to fire and disassembly; vain",
    description: "Charles Lee Ray — serial killer reincarnated into a children's doll. Wanna play?" },
  { name: "Ciri (Full Power)", universe: "The Witcher",
    strength: 80, speed: 92, intelligence: 86, durability: 84,
    specialAbility: "Elder Blood — teleportation between worlds and times; sword mastery from Geralt; Aen Saevherne magic",
    weaknesses: "Power surges harm her; Wild Hunt hunts her; emotional volatility",
    description: "Cirilla Fiona Elen Riannon — Empress of Nilfgaard's heir, last of the Elder Blood, and Geralt's adopted daughter." },
  { name: "Cleveland Brown", universe: "Family Guy",
    strength: 65, speed: 60, intelligence: 70, durability: 70,
    specialAbility: "Soft-spoken neighbor; bathtub-physics survival; 'no, no, no, no'",
    weaknesses: "Tub falls off houses regularly; mild-mannered to a fault",
    description: "Cleveland Brown — Quahog's gentlest neighbor, who has fallen out of his bathtub through more roofs than he can count." },
  { name: "Cloud (Limit Break)", universe: "Final Fantasy",
    strength: 92, speed: 90, intelligence: 80, durability: 88,
    specialAbility: "Omnislash limit break — multi-strike sword combo; Buster Sword and Fusion Swords; Mako infusion",
    weaknesses: "Mako-poisoning relapse; identity confusion with Zack's memories",
    description: "Cloud Strife at full Limit Break — Buster Sword high, Omnislash incoming, Sephiroth wishing he hadn't shown up." },
  { name: "Cortana (AI)", universe: "Halo",
    strength: 30, speed: 100, intelligence: 100, durability: 60,
    specialAbility: "Smart AI — hacks Forerunner tech; tactical analysis at lightyear scale; can possess networks",
    weaknesses: "Rampancy degrades her over years; needs hardware host; bound to the Master Chief",
    description: "Cortana — UNSC smart AI, the Master Chief's better half, dangerous when sane and apocalyptic when not." },
  { name: "Cosmo", universe: "Fairly OddParents",
    strength: 40, speed: 70, intelligence: 30, durability: 80,
    specialAbility: "Fairy magic — wish-granting; Da Rules limit how; nigh-immortal floating idiot",
    weaknesses: "Dim; bound by Da Rules; Anti-Fairies cancel his magic",
    description: "Cosmo — Timmy Turner's fairy godfather. Husband to Wanda, father to Poof, and the dumbest god of wishes in fiction." },
  { name: "Courage", universe: "Courage the Cowardly Dog",
    strength: 50, speed: 65, intelligence: 75, durability: 70,
    specialAbility: "Outsmarts horrors weekly out of love for Muriel; iconic scream; surprising luck and persistence",
    weaknesses: "Tiny pink dog; trembles constantly; only Muriel believes in him",
    description: "Courage — the timid pink dog of Nowhere, Kansas, who fights eldritch horrors weekly out of love for his Muriel." },
  { name: "Creature from the Black Lagoon", universe: "Universal Monsters",
    strength: 86, speed: 80, intelligence: 65, durability: 88,
    specialAbility: "Amphibious humanoid Devonian — massive aquatic strength; claw and bite; ambush from water",
    weaknesses: "Vulnerable on dry land for long periods; flame; rotenone",
    description: "The Gill-Man — the prehistoric amphibian discovered in the Amazon's Black Lagoon, kidnapping leading ladies since 1954." },
  { name: "Crowley", universe: "Supernatural",
    strength: 80, speed: 75, intelligence: 95, durability: 80,
    specialAbility: "King of Hell; demon deals; teleportation; centuries of bargain-craft; hellhounds on retainer",
    weaknesses: "Demon-killing knife; angel blades; sentimental about his ex-Salesman humanity",
    description: "Crowley — King of the Crossroads, briefly King of Hell, and the only demon the Winchesters keep on speed-dial." },
  { name: "Cthulhu", universe: "Cthulhu Mythos",
    strength: 100, speed: 80, intelligence: 95, durability: 100,
    specialAbility: "Dread cosmic priest of R'lyeh; reality-warping presence; psychic dominion; cyclopean physical scale",
    weaknesses: "Bound in R'lyeh until the stars are right; the stars currently are not",
    description: "The Great Old One who lies dreaming in sunken R'lyeh — a god so vast that mere sight of him cracks human minds." },
  { name: "Cyber Sub-Zero", universe: "Mortal Kombat",
    strength: 88, speed: 85, intelligence: 80, durability: 92,
    specialAbility: "Cybernetically converted Lin Kuei — cryomancy paired with rocket arsenal; armored body",
    weaknesses: "Mechanical; heat damages internals; lost humanity weighs on him",
    description: "Kuai Liang as a forced cyber-conversion — Lin Kuei tech grafted onto a cryomancer's soul." },
  { name: "D'Vorah", universe: "Mortal Kombat",
    strength: 80, speed: 86, intelligence: 80, durability: 84,
    specialAbility: "Kytinn hive-queen — venomous projectiles; bug-summoning; egg-implant fatality",
    weaknesses: "Hive-collective vulnerability; flame; outmuscled by raw power",
    description: "D'Vorah — Kytinn assassin loyal only to her Hive, who once said no to no royal demand and meant it." },
  { name: "Dairou", universe: "Mortal Kombat",
    strength: 78, speed: 80, intelligence: 76, durability: 76,
    specialAbility: "Mercenary skills; teleport tackle; hammer slam; Order of Light drop-out turned hired blade",
    weaknesses: "Mercenary loyalty; mortal; second-tier cast member",
    description: "Dairou — a former Seidan Guardsman turned mercenary, fighting for whoever hands him the larger sack of coin." },
  { name: "Dalek Emperor", universe: "Doctor Who",
    strength: 90, speed: 70, intelligence: 96, durability: 92,
    specialAbility: "Dalek god-king; reality-shaping in late series; commands Dalek armies across time",
    weaknesses: "Bound to physical Dalek casing; Bad Wolf-tier Time Vortex destroys him",
    description: "The Emperor of the Daleks — a god-self-styled Dalek lord who survived the Time War as a bone-white tyrant." },
  { name: "Danny Phantom", universe: "Danny Phantom",
    strength: 84, speed: 86, intelligence: 80, durability: 84,
    specialAbility: "Half-ghost — intangibility; ghostly wail sonic; ecto-blasts; flight; ice powers",
    weaknesses: "Mortal half is fragile; ghostly wail drains him; teen drama distracts him",
    description: "Danny Fenton — fourteen-year-old who got electrified into half-ghost form and learned to defend Amity Park." },
  { name: "Dark Samus", universe: "Metroid",
    strength: 90, speed: 88, intelligence: 80, durability: 90,
    specialAbility: "Phazon-corrupted Metroid Prime in Samus's image; Phazon-beam; energy-leech; reality-corrupting touch",
    weaknesses: "Phazon dependency; Light beam; vulnerability when the Phazon source is severed",
    description: "Dark Samus — Metroid Prime reborn in the Chozo armor's image, a Phazon-twisted mirror of the bounty hunter." },
  { name: "Darkseid (True Form)", universe: "DC",
    strength: 100, speed: 92, intelligence: 96, durability: 100,
    specialAbility: "True form Avatar of Apokolips — Omega Beams that ignore reality; Anti-Life Equation; god-tier presence",
    weaknesses: "Anti-Life-Equation incomplete in some arcs; Source Wall containment; the Black Racer",
    description: "Darkseid in his true Apokoliptan form — not the avatar, but the god himself, Omega-eyed and patient." },
  { name: "Darrius", universe: "Mortal Kombat",
    strength: 80, speed: 84, intelligence: 78, durability: 76,
    specialAbility: "Edenian rebel; martial-arts striker; Resistance leader against the Seidan Order of Light",
    weaknesses: "Mortal; political enemies; outclassed by sorcerers",
    description: "Darrius — leader of the Resistance against the Seidan Order, a freedom-fighter trading the lash for liberty." },
  { name: "Dead by Daylight Blight", universe: "Dead by Daylight",
    strength: 84, speed: 92, intelligence: 75, durability: 80,
    specialAbility: "Compound Thirty rush — bounces off walls in a frenzy; pumpkin-faced lethality; speed-killer archetype",
    weaknesses: "Rush has cooldown; fragile out of frenzy",
    description: "Talbot Grimes — alchemist disfigured by his own Compound, a bouncing rush-killer of the Entity's realm." },
  { name: "Dead by Daylight Huntress", universe: "Dead by Daylight",
    strength: 86, speed: 76, intelligence: 70, durability: 86,
    specialAbility: "Throws hatchets across the map; lullaby hum; rabbit-mask Russian forest hunter",
    weaknesses: "Slow walk speed; reload time; loud lullaby telegraphs her position",
    description: "Anna the Huntress — a Russian woods stalker who throws hatchets at survivors and hums lullabies to her victims." },
  { name: "Dead by Daylight Nemesis", universe: "Dead by Daylight",
    strength: 90, speed: 80, intelligence: 60, durability: 92,
    specialAbility: "T-Virus tentacle whip; zombie minions; STARS-targeting fixation",
    weaknesses: "Slow when not whipping; loud; fire and acid weaknesses canon",
    description: "The Nemesis — Umbrella's tentacled bio-weapon, dragged out of Resident Evil into the Entity's fog." },
  { name: "Dead by Daylight Nurse", universe: "Dead by Daylight",
    strength: 75, speed: 88, intelligence: 65, durability: 70,
    specialAbility: "Blink teleport — bypasses walls and pallets; ignores the rules of survivor looping",
    weaknesses: "Slow base speed; fatigue after blinks; exposed during stuns",
    description: "Sally Smithson — broken-bonneted asylum nurse who blinks through walls to drag survivors back to her ward." },
  { name: "Dead by Daylight Oni", universe: "Dead by Daylight",
    strength: 96, speed: 88, intelligence: 65, durability: 90,
    specialAbility: "Blood Fury rage form once enough survivors bleed; one-hit kanabō downs in fury",
    weaknesses: "Has to bleed survivors first; Fury is timed",
    description: "Kazan Yamaoka — a samurai turned demon by his own bloodlust, transforming into the Oni when survivors bleed." },
  { name: "Dead by Daylight Spirit", universe: "Dead by Daylight",
    strength: 84, speed: 92, intelligence: 75, durability: 78,
    specialAbility: "Phase walk — invisible high-speed pursuit; vengeful onryō scratch listening",
    weaknesses: "Phase has cooldown; locker-hides counter her",
    description: "Rin Yamaoka — onryō born of family murder, who phases through the killing ground in vengeful silence." },
  { name: "Dead by Daylight Trapper", universe: "Dead by Daylight",
    strength: 85, speed: 75, intelligence: 70, durability: 86,
    specialAbility: "Steel bear traps placed across the map; raw cleaver; brutally simple game plan",
    weaknesses: "Traps can be disarmed; slow; predictable patrol routes",
    description: "Evan MacMillan — the Trapper, mask-wearing patriarch of the Entity's killer roster, who lays steel bear-traps in grass." },
  { name: "Dead by Daylight Wraith", universe: "Dead by Daylight",
    strength: 78, speed: 84, intelligence: 70, durability: 78,
    specialAbility: "Wailing Bell — turns invisible and faster while cloaked; ambush slap on uncloak",
    weaknesses: "Loud bell ring telegraphs cloak; flashlights stagger him",
    description: "Philip Ojomo — a man cursed into invisibility by a corrupt foreman, the Wraith stalks the fog with a wailing bell." },
  { name: "Deadite", universe: "Evil Dead",
    strength: 78, speed: 75, intelligence: 60, durability: 80,
    specialAbility: "Possessed corpse driven by Kandarian demons; cackles unsettlingly; takes shotgun blasts and keeps coming",
    weaknesses: "Dismemberment; chainsaws; the Necronomicon's seal incantations",
    description: "A Kandarian-demon-possessed corpse — the rank-and-file horror Ash Williams chainsaws by the dozen." },
  { name: "Deadman (Boston Brand)", universe: "DC",
    strength: 70, speed: 80, intelligence: 80, durability: 75,
    specialAbility: "Possession of any living being; intangibility; ghost-realm awareness",
    weaknesses: "Bound to the spirit world; cannot directly affect matter",
    description: "Boston Brand — circus aerialist murdered mid-act, returned as a possession-ghost to balance karmic ledgers." },
  { name: "Deadshot", universe: "DC",
    strength: 78, speed: 82, intelligence: 84, durability: 80,
    specialAbility: "Never misses — wrist-mounted firearms; precision sniping; fearless because he secretly wants to die",
    weaknesses: "Suicidal recklessness; daughter is his weak point; no metahuman defenses",
    description: "Floyd Lawton — DC's deadliest marksman, a hitman who plays Russian roulette with every shot because he can't die." },
  { name: "Dean Winchester", universe: "Supernatural",
    strength: 78, speed: 78, intelligence: 84, durability: 88,
    specialAbility: "Hunter of decades; Colt revolver; First Blade with Mark of Cain (former); demon-killing knife",
    weaknesses: "Mortal; alcoholism; brother always in danger; haunted",
    description: "Dean Winchester — older brother, righteous man, Hell veteran, and the kind of guy who bargains with gods." },
  { name: "Death", universe: "Mythology",
    strength: 100, speed: 95, intelligence: 99, durability: 100,
    specialAbility: "Personification of mortality — touch ends life; reaper's scythe; cannot be permanently slain",
    weaknesses: "Bound by cosmic order; the rules of dying must be obeyed",
    description: "The Reaper itself — a personified inevitability who collects every life when the time arrives." },
  { name: "Death (DC)", universe: "DC",
    strength: 100, speed: 95, intelligence: 99, durability: 100,
    specialAbility: "Endless of Death — escorts every soul; existed before the universe; will outlast all life",
    weaknesses: "Bound by her function; will not act outside her remit",
    description: "Death of the Endless — Dream's older sister, a goth in an ankh necklace who gives the universe its kindest farewell." },
  { name: "Death (Marvel)", universe: "Marvel",
    strength: 100, speed: 95, intelligence: 99, durability: 100,
    specialAbility: "Cosmic embodiment of Death; Thanos's beloved; reality-tier authority over mortal endings",
    weaknesses: "Bound to her domain; can be petitioned by cosmic entities",
    description: "Mistress Death of the Marvel cosmos — silent, hooded, and the only thing Thanos has ever loved." },
  { name: "Decapre", universe: "Street Fighter",
    strength: 78, speed: 90, intelligence: 75, durability: 78,
    specialAbility: "Cammy-doll clone — claw blades; psycho-power dash combos; Shadaloo conditioning",
    weaknesses: "Damaged psyche; dependent on Shadaloo tech; outclassed by Cammy at peak",
    description: "Decapre — Cammy's older sister and another of Shadaloo's Dolls, a Russian assassin in mask and claws." },
  { name: "Dee Jay", universe: "Street Fighter",
    strength: 80, speed: 84, intelligence: 75, durability: 82,
    specialAbility: "Kickboxing showman; Air Slasher; Jacknife Maximum; rhythm-based combat",
    weaknesses: "Cocky; over-celebrates mid-combo; weak grappling defense",
    description: "Dee Jay — Jamaican kickboxer-musician who fights to a beat and grins through a mouthguard." },
  { name: "Delirium", universe: "DC",
    strength: 80, speed: 85, intelligence: 50, durability: 90,
    specialAbility: "Endless of Delirium (formerly Delight) — inflicts madness; reality-altering chaos at touch",
    weaknesses: "Cannot focus; her own existence is fragmented; bound by Endless rules",
    description: "Delirium of the Endless — once Delight, now a cloud of mismatched eyes and butterflies, breaking minds with a smile." },
  { name: "Denji (Chainsaw Devil)", universe: "Chainsaw Man",
    strength: 92, speed: 88, intelligence: 60, durability: 92,
    specialAbility: "Chainsaw transformation; eats devils to nullify them; nigh-invincible while bleeding",
    weaknesses: "Powered by his blood — drained dry, he reverts; impulsive, hungry teenager",
    description: "Denji as Chainsaw Man — a starving boy whose chainsaw devil keeps the blood pumping and the chainsaws spinning." },
  { name: "Deontay Wilder", universe: "Boxing",
    strength: 86, speed: 78, intelligence: 65, durability: 75,
    specialAbility: "Right hand of God — one-punch knockout artist; heavyweight fight-ending power",
    weaknesses: "Footwork and stamina inconsistent; defense over-relies on power",
    description: "The Bronze Bomber — heavyweight slugger whose right hand has ended dozens of fights in a single swing." },
  { name: "Desaad", universe: "DC",
    strength: 70, speed: 70, intelligence: 92, durability: 78,
    specialAbility: "Apokoliptan torture master; pain-channeling sorcery; Darkseid's right-hand sadist",
    weaknesses: "Coward without Darkseid's protection; physically frail next to New Gods",
    description: "Desaad — Apokolips's chief torturer, who serves Darkseid by perfecting suffering as an art form." },
  { name: "Desire", universe: "DC",
    strength: 80, speed: 85, intelligence: 92, durability: 85,
    specialAbility: "Endless of Desire — manipulates wants; exists in every desire ever felt; sigil-bound presence",
    weaknesses: "Bound by Endless rules; banishable by Dream's authority",
    description: "Desire of the Endless — gender-fluid, beautifully cruel, and present in every wanting heart." },
  { name: "Detentionaire Lee Ping", universe: "Detentionaire",
    strength: 65, speed: 72, intelligence: 86, durability: 65,
    specialAbility: "Brainwashed conspiracy investigator; martial-arts trigger from sleeper-cell programming",
    weaknesses: "Memory gaps; perpetual detention; teenage stamina",
    description: "Lee Ping — A. Nigma High freshman framed for a prank, navigating an actual school-wide conspiracy from the back of the detention room." },
  { name: "Devilman", universe: "Devilman",
    strength: 92, speed: 88, intelligence: 75, durability: 92,
    specialAbility: "Demon Amon merged with Akira Fudo — flight; demonic strength; spirit-tier durability; horror-rage",
    weaknesses: "Holy weapons; emotional ties to Miki break him; demon-self struggles for dominance",
    description: "Akira Fudo as Devilman — a teenage boy who became a demon to fight demons and learned humans were the worst." },
  { name: "Dexter (Dexter's Lab)", universe: "Dexter's Laboratory",
    strength: 50, speed: 60, intelligence: 99, durability: 60,
    specialAbility: "Boy genius — secret lab full of impossible inventions; mech suits; raw IQ",
    weaknesses: "Tiny child; sister Dee Dee always presses the big red button; lab kept secret from parents",
    description: "Dexter — boy genius with a clandestine high-tech laboratory hidden behind his bookshelf, plagued by his sister." },
  { name: "Dhalsim", universe: "Street Fighter",
    strength: 70, speed: 72, intelligence: 90, durability: 72,
    specialAbility: "Yoga master — limb stretching; teleportation; Yoga Fire and Yoga Flame; meditation healing",
    weaknesses: "Frail body relative to other fighters; pacifist by nature",
    description: "Dhalsim — Indian yoga master who breathes fire, stretches limbs across screens, and teleports between strikes." },
  { name: "Diablo (Prime Evil)", universe: "Diablo",
    strength: 96, speed: 86, intelligence: 92, durability: 96,
    specialAbility: "Prime Evil fusion of all seven Evils; reality corruption; soulstone-binding; god-tier hellfire",
    weaknesses: "Soulstone is his anchor and his cage; angelic counterforce",
    description: "Diablo — Lord of Terror, fused into the Prime Evil with all seven Lords inside him, the embodiment of the Burning Hells." },
  { name: "Dirty Harry", universe: "Dirty Harry",
    strength: 75, speed: 75, intelligence: 80, durability: 78,
    specialAbility: ".44 Magnum mastery; SFPD inspector experience; goes off the books; do-you-feel-lucky stare",
    weaknesses: "Mortal; suspended every other case; collateral damage record",
    description: "Inspector Harry Callahan — SFPD's most-suspended cop and the man who made the .44 Magnum a movie star." },
  { name: "Djinn", universe: "Wishmaster",
    strength: 88, speed: 80, intelligence: 92, durability: 88,
    specialAbility: "Grants wishes that twist into curses; reality manipulation through bargained words; centuries of cunning",
    weaknesses: "Bound by the wishing rules; banished if the wish-maker reverses the deal",
    description: "A Djinn of the Waste between worlds — grants three wishes and twists each into a fresh damnation." },
  { name: "Doctor Doom (God Emperor)", universe: "Marvel",
    strength: 100, speed: 95, intelligence: 100, durability: 100,
    specialAbility: "Beyonder-tier reality control; god-emperor of Battleworld; sorcery, science, and divine authority fused",
    weaknesses: "Acknowledges Reed Richards as the rightful god; mask conceals his pride",
    description: "Doom after stitching the multiverse into Battleworld and crowning himself God Emperor — and almost handling the job." },
  { name: "Doctor Fate (Kent Nelson)", universe: "DC",
    strength: 80, speed: 82, intelligence: 92, durability: 86,
    specialAbility: "Helm of Nabu; Lord of Order sorcery; ankh-energy projection; flight; Justice Society veteran",
    weaknesses: "Helm sometimes overrides Kent's will; magic is finite without it",
    description: "Kent Nelson — original Doctor Fate, an archaeologist wearing the helm of an ancient Lord of Order." },
  { name: "Doctor Light", universe: "DC",
    strength: 70, speed: 75, intelligence: 88, durability: 70,
    specialAbility: "Photon manipulation; light constructs; flight; villain who became a Teen Titans-tier threat",
    weaknesses: "Darkness counters him; severely undermined morally by past abuses",
    description: "Arthur Light — DC's photon villain, infamous for crimes that landed him on every hero's permanent enemies list." },
  { name: "Doctor Manhattan (Watchmen)", universe: "Watchmen",
    strength: 100, speed: 100, intelligence: 100, durability: 100,
    specialAbility: "Quantum reality manipulation; experiences time non-linearly; can disassemble matter at will; near-omnipotence",
    weaknesses: "Detached from humanity; emotional inertia; can be fooled by predetermined paths",
    description: "Jon Osterman — physicist transformed into a blue near-god, who watches every moment of his life simultaneously." },
  { name: "Doctor Sleep Rose the Hat", universe: "Doctor Sleep",
    strength: 80, speed: 76, intelligence: 86, durability: 84,
    specialAbility: "Leader of the True Knot — feeds on children's 'steam' (psychic essence); long lifespan; psychic dominance",
    weaknesses: "True Knot needs steam to survive; Dan Torrance and Abra Stone outclass her",
    description: "Rose the Hat — leader of the True Knot, a top-hatted psychic predator hunting children with the shining." },
  { name: "Doom", universe: "Doom",
    strength: 96, speed: 90, intelligence: 80, durability: 96,
    specialAbility: "Doomslayer of generic Doom games — BFG; chainsaw; berserker rage; demon-slaying experience across hells",
    weaknesses: "Mortal beneath the Praetor armor; ammo-dependent in some loadouts",
    description: "The catch-all Doom protagonist — armored, armed, and pissed at the demons of Mars." },
  { name: "Doomfist", universe: "Overwatch",
    strength: 90, speed: 84, intelligence: 80, durability: 88,
    specialAbility: "Doomfist gauntlet — seismic punches; rocket-charged dashes; Talon enforcer; hand-to-hand mastery",
    weaknesses: "Gauntlet can be removed; relies on cooldowns",
    description: "Akande Ogundimu — heir to the Doomfist gauntlet, a Talon agent who believes only conflict makes humanity stronger." },
  { name: "Dracula (Bram Stoker)", universe: "Dracula",
    strength: 90, speed: 84, intelligence: 90, durability: 90,
    specialAbility: "Vampire lord of Transylvania — shapeshift; weather manipulation; mind control; centuries of guile",
    weaknesses: "Sunlight; consecrated ground; stake to the heart; running water; garlic",
    description: "Count Dracula — Bram Stoker's original vampire-king, ancient warlord turned night-walking aristocrat." },
  { name: "Dudley", universe: "Street Fighter",
    strength: 84, speed: 78, intelligence: 80, durability: 84,
    specialAbility: "British heavyweight boxing — Corkscrew Blow; Rolling Thunder; gentleman's pugilism",
    weaknesses: "Gentleman's code; doesn't punch women in older lore; restricted to fists",
    description: "Dudley — British boxing champion who fights like a Victorian gentleman and dresses like one between rounds." },
  { name: "Dukey", universe: "Johnny Test",
    strength: 60, speed: 70, intelligence: 88, durability: 65,
    specialAbility: "Talking, walking, hyper-intelligent dog of the Test family lab experiments",
    weaknesses: "Still a dog; addicted to bacon; hides his sentience from outsiders",
    description: "Dukey — Johnny Test's experimental talking dog, lab-uplifted into a sarcastic anthropomorphic best friend." },
  { name: "E. Honda", universe: "Street Fighter",
    strength: 88, speed: 70, intelligence: 75, durability: 92,
    specialAbility: "Sumo wrestling mastery; Hundred Hand Slap; Sumo Headbutt; massive frame to absorb hits",
    weaknesses: "Slow movement; limited aerial defense; relies on raw mass",
    description: "Edmond Honda — Japanese sumo wrestler who travels to prove sumo is the world's mightiest martial art." },
  { name: "Edd", universe: "Ed, Edd n Eddy",
    strength: 50, speed: 65, intelligence: 88, durability: 55,
    specialAbility: "Boy-genius engineering; quick assembly contraptions; fastidious organization",
    weaknesses: "Anxious; germ-phobic; physically slight",
    description: "Double D — the smart Ed of Peach Creek's cul-de-sac, sock-hatted engineer of every doomed scam Eddy concocts." },
  { name: "Eddy", universe: "Ed, Edd n Eddy",
    strength: 55, speed: 70, intelligence: 75, durability: 60,
    specialAbility: "Scam mastermind; fast-talking salesmanship; con-artist resilience; jaw-breaker obsession",
    weaknesses: "Schemes always implode; older brother trauma; short fuse",
    description: "Eddy — short-fused scam-runner of the cul-de-sac, perpetually one quarter away from buying every jawbreaker." },
  { name: "Elden Ring Tarnished", universe: "Elden Ring",
    strength: 86, speed: 84, intelligence: 80, durability: 84,
    specialAbility: "Maiden-blessed runesmith; weapon-art mastery; Flask of Crimson Tears regen; sorcery and incantations",
    weaknesses: "Lost grace cycles; Erdtree politics; bosses with delayed combos",
    description: "A Tarnished — chosen of the Two Fingers, returned to the Lands Between to claim Elden Lord status from a god's corpse." },
  { name: "Elena", universe: "Street Fighter",
    strength: 75, speed: 86, intelligence: 80, durability: 78,
    specialAbility: "Capoeira African princess — high-kick mobility; Healing technique; rhythm-based combat",
    weaknesses: "Range-limited; pacifist instincts; leaves fights early to make friends",
    description: "Elena — Kenyan princess and capoeira fighter who travels the world to befriend everyone she just kicked." },
  { name: "Eren (Attack Titan)", universe: "Attack on Titan",
    strength: 95, speed: 86, intelligence: 92, durability: 96,
    specialAbility: "Founding Titan + Attack Titan + War Hammer Titan; Rumbling control over all Wall Titans",
    weaknesses: "Royal-blood requirement bypassed via Zeke; emotional ties to Mikasa and Armin",
    description: "Eren Yeager — founding-titan-empowered son of Grisha, who unleashed the Rumbling to flatten the world." },
  { name: "Eric Cartman", universe: "South Park",
    strength: 60, speed: 60, intelligence: 78, durability: 70,
    specialAbility: "Manipulation genius; tactical cruelty; cult-leader charisma; eats his enemies' parents",
    weaknesses: "Lazy; cowardly when not in control; addicted to Cheesy Poofs",
    description: "Eric Cartman — South Park's chubby fourth-grade Machiavelli, who has weaponized Wendy's tear ducts for sport." },
  { name: "Ermac", universe: "Mortal Kombat",
    strength: 86, speed: 84, intelligence: 80, durability: 84,
    specialAbility: "Fusion of dead souls — telekinesis; teleport; soul-power physical strikes",
    weaknesses: "Soul cohesion can be disrupted; some souls fight him from within",
    description: "Ermac — a fusion of countless dead Outworld warriors, a many-souled telekinetic loyal to whoever lets him stay whole." },
  { name: "Eternity", universe: "Marvel",
    strength: 100, speed: 100, intelligence: 100, durability: 100,
    specialAbility: "Embodiment of all Marvel reality; cosmic awareness; infinite time and space; god-tier presence",
    weaknesses: "Bound to maintain cosmic balance; submits to the Living Tribunal",
    description: "Eternity — the personification of all time and space in the Marvel cosmos, a being who is the universe itself." },
  { name: "Eustace Bagge", universe: "Courage the Cowardly Dog",
    strength: 60, speed: 50, intelligence: 60, durability: 60,
    specialAbility: "Mean old farmer of Nowhere; mask scares Courage; resigned to weekly cosmic horror",
    weaknesses: "Greedy; cruel to his dog; routinely abducted, transformed, or eaten",
    description: "Eustace Bagge — Muriel's grouchy farmer husband, who scares the dog and loses to every horror that visits the farm." },
  { name: "Evander Holyfield", universe: "Boxing",
    strength: 84, speed: 80, intelligence: 78, durability: 92,
    specialAbility: "Heavyweight and cruiserweight champion; iron chin; counter-punch fundamentals; bit by Tyson",
    weaknesses: "Aged late-career; suffers slow boxers' decline",
    description: "The Real Deal — four-time heavyweight champ who fought every legend of his era and kept his ear (mostly)." },
  { name: "Evil Morty", universe: "Rick and Morty",
    strength: 60, speed: 70, intelligence: 99, durability: 65,
    specialAbility: "Smartest Morty in the multiverse; eyepatch tech; played the Citadel of Ricks against itself; transcended Central Finite Curve",
    weaknesses: "Mortal Morty body; Rick Prime out there somewhere",
    description: "Evil Morty — the eyepatch-wearing Morty who outplayed every Rick alive and broke out of the Central Finite Curve." },
  { name: "F.A.N.G", universe: "Street Fighter",
    strength: 76, speed: 84, intelligence: 84, durability: 74,
    specialAbility: "Poison-coated movements; Shadaloo Grandmaster Four; venomous projectiles and stretching limbs",
    weaknesses: "Antitoxin; loses without venom; treacherous nature",
    description: "F.A.N.G — Shadaloo's pointed-hat poison master, a Grandmaster who weaponizes his own body chemistry." },
  { name: "Falke", universe: "Street Fighter",
    strength: 78, speed: 82, intelligence: 78, durability: 78,
    specialAbility: "Psycho Power-imbued staff; Shadaloo Doll; chi blasts; gun-stick combat",
    weaknesses: "Limited Psycho Power reserves; Shadaloo conditioning to overcome",
    description: "Falke — a Shadaloo Doll wielding a Psycho Power-charged staff, fighting to reclaim her own free will." },
  { name: "Fei Long", universe: "Street Fighter",
    strength: 80, speed: 90, intelligence: 78, durability: 80,
    specialAbility: "Hong Kong action-movie kung fu; Rekka Ken three-strike combo; Bruce-Lee tribute style",
    weaknesses: "Range-limited; close-quarters specialist; ego of a movie star",
    description: "Fei Long — Hong Kong martial-arts movie star who quit the screen to fight real opponents in the world tournament." },
  { name: "Ferra/Torr", universe: "Mortal Kombat",
    strength: 96, speed: 70, intelligence: 65, durability: 95,
    specialAbility: "Tag-team — tiny Ferra rides giant Torr; combined slams; Outworld brute team",
    weaknesses: "Slow Torr without Ferra's coordination; Ferra alone is fragile",
    description: "Ferra and Torr — a tiny Outworld princess riding a giant brute, the two-in-one wrecking ball of MKX." },
];

async function main() {
  console.log(`Seeding ${characters.length} PDF characters...`);
  const existing = await db.select({ name: charactersTable.name }).from(charactersTable);
  const existingNames = new Set(existing.map(c => c.name.toLowerCase()));

  let added = 0, skipped = 0;
  for (const char of characters) {
    if (existingNames.has(char.name.toLowerCase())) {
      console.log(`  Skip (exists): ${char.name}`);
      skipped++;
      continue;
    }
    await db.insert(charactersTable).values({ ...char, imageUrl: null });
    console.log(`  Added: ${char.name}`);
    added++;
  }
  console.log(`\nDone — Added: ${added}, Skipped: ${skipped}`);
  process.exit(0);
}

main().catch(e => { console.error(e); process.exit(1); });
