import { db, charactersTable } from "@workspace/db";
import { sql } from "drizzle-orm";

// All stats on 0–10,000 scale (direct insert — no squaring)
const characters = [

  // ═══════════════════════════════════════════════════════
  //  DISNEY
  // ═══════════════════════════════════════════════════════

  {
    name: "Hercules",
    universe: "Disney",
    strength: 9801,
    speed: 7225,
    intelligence: 5776,
    durability: 9409,
    specialAbility: "Divine strength of the gods — can lift mountains, shatter the earth, and wrestle literal monsters; immortal stamina",
    weaknesses: "His love for Meg is his Achilles heel; loses power if he surrenders his soul; emotionally impulsive",
    description: "Son of Zeus, raised by mortals, strongest man alive. Hercules fights with his heart first and his godlike fists second.",
  },
  {
    name: "Moana",
    universe: "Disney",
    strength: 5476,
    speed: 6889,
    intelligence: 7744,
    durability: 6400,
    specialAbility: "Chosen by the ocean itself; master navigator and sailor; heart of Te Fiti grants reality-restoring power at the finale",
    weaknesses: "No supernatural combat ability; relies on courage and wits over brute force",
    description: "Daughter of the chief, chosen by the ocean. Moana crossed the open sea alone to restore the heart of the world — and succeeded.",
  },
  {
    name: "Aladdin",
    universe: "Disney",
    strength: 5776,
    speed: 7744,
    intelligence: 8100,
    durability: 5476,
    specialAbility: "Extraordinary improvisational cunning; three wishes from the Genie (historically); expert thief, acrobat, and street fighter",
    weaknesses: "No inherent superpowers; relies on resourcefulness; insecurity leads him to lie when honesty would serve better",
    description: "The diamond in the rough. Aladdin survived the streets of Agrabah on cleverness alone, then used a genie's power with his heart, not his ego.",
  },
  {
    name: "Jafar",
    universe: "Disney",
    strength: 7744,
    speed: 6724,
    intelligence: 9801,
    durability: 8100,
    specialAbility: "Sorcerer Supreme of Agrabah — hypnosis staff, shape-shifting into a giant cobra; as a genie: nearly omnipotent cosmic power",
    weaknesses: "His boundless ambition is exploitable — tricked into wishing to be a genie, which imprisoned him in a lamp",
    description: "The most cunning and power-hungry sorcerer in Arabia. Jafar's brilliance is exceeded only by his ego — which is also his fatal flaw.",
  },
  {
    name: "Ursula",
    universe: "Disney",
    strength: 7744,
    speed: 5476,
    intelligence: 9409,
    durability: 8100,
    specialAbility: "Dark sea magic — steals voices, transforms bodies, commands kraken-like power; grows to enormous size using King Triton's trident",
    weaknesses: "Overconfidence at the moment of victory; can't resist monologuing; her power ultimately depends on contracts",
    description: "The sea witch of the deep. Ursula deals in dreams — takes everything you value, gives you exactly what you asked for, and calls it a fair trade.",
  },
  {
    name: "Gaston",
    universe: "Disney",
    strength: 9025,
    speed: 7744,
    intelligence: 3600,
    durability: 8649,
    specialAbility: "Peak human specimen — no one fights like Gaston, no one's quite as big; expert hunter, wrestler, and bare-handed brawler",
    weaknesses: "Catastrophically overconfident; zero emotional intelligence; cannot conceive of failure",
    description: "No one hits like Gaston, nobody's built like Gaston. The definitive peak human predator — massive, brutal, and dangerously skilled at hunting.",
  },
  {
    name: "Scar",
    universe: "Disney",
    strength: 6889,
    speed: 7225,
    intelligence: 9604,
    durability: 6724,
    specialAbility: "Mastermind schemer — orchestrated regicide without touching a weapon; commands hyena armies; vicious lion combat when cornered",
    weaknesses: "Relies entirely on manipulation over direct power; collapses without his hyena army; his treachery ultimately betrays him",
    description: "The pride lands' most dangerous mind in a lion's body. Scar didn't claw his way to the throne — he talked, manipulated, and waited.",
  },
  {
    name: "Stitch",
    universe: "Disney",
    strength: 8649,
    speed: 8100,
    intelligence: 9025,
    durability: 9025,
    specialAbility: "Alien experiment #626 — can lift 3000x his weight, is bulletproof, can see in darkness, is virtually indestructible, and is a genius",
    weaknesses: "Drawn to ohana — his adopted family is his weakness; his violent programming fights his heart constantly",
    description: "Experiment 626 — designed to be an unstoppable force of destruction. Then he met a little girl named Lilo and chose to be something more.",
  },
  {
    name: "Genie",
    universe: "Disney",
    strength: 9801,
    speed: 9801,
    intelligence: 9801,
    durability: 9025,
    specialAbility: "Near-omnipotent reality manipulation — can grant any wish, transform matter and energy freely; imprisoned only by his lamp's master",
    weaknesses: "Cannot grant wishes without being summoned; bound by three rules (no killing, no forcing love, no reviving the dead)",
    description: "Phenomenal cosmic power — itty bitty living space. The Genie is arguably the most powerful being in the Disney universe, and he knows it.",
  },
  {
    name: "Chernabog",
    universe: "Disney",
    strength: 9604,
    speed: 6400,
    intelligence: 7744,
    durability: 9801,
    specialAbility: "Demon lord of Bald Mountain — summons the dead, commands hellfire, transforms souls, grows to mountain scale at night",
    weaknesses: "Power weakens at dawn; retreats from holy light and church bells; only active at night",
    description: "The demon on Bald Mountain. Disney's darkest creation — a colossal night-god who summons the damned for a single glorious midnight revel.",
  },
  {
    name: "The Beast",
    universe: "Disney",
    strength: 9025,
    speed: 7056,
    intelligence: 6724,
    durability: 8836,
    specialAbility: "Enchanted prince in monstrous form — superhuman strength, enormous fangs and claws; can withstand arctic cold and devastating injury",
    weaknesses: "His temper destroys what he loves; the curse's time limit is his existential pressure; love is his only salvation",
    description: "A prince cursed into a monster who had to learn to love before he could become human again. The Beast is exactly as dangerous as his rage.",
  },
  {
    name: "Wreck-It Ralph",
    universe: "Disney",
    strength: 9801,
    speed: 4900,
    intelligence: 5776,
    durability: 9409,
    specialAbility: "Wrecks anything — his fists can demolish steel, concrete and entire buildings; programmed for destruction with invulnerable hands",
    weaknesses: "Slow and lumbering; predictable destructive pattern; enormous heart means he can be emotionally manipulated",
    description: "The bad guy of Fix-It Felix Jr. — in the game and sometimes in life. Ralph has the strongest fists in the arcade and the biggest heart in any game.",
  },
  {
    name: "Syndrome",
    universe: "Disney",
    strength: 5184,
    speed: 8100,
    intelligence: 9801,
    durability: 6400,
    specialAbility: "Zero-Point Energy gauntlet immobilizes anything; Omnidroid series robots; zero suit flight; reverse-engineered superhero technology",
    weaknesses: "His cape — literally. Overconfident; obsessed with recognition; physically unremarkable without his tech",
    description: "If everyone is super, no one will be. Syndrome was the world's most dangerous fanboy, who built weapons out of bitterness and called it a plan.",
  },
  {
    name: "Mr. Incredible",
    universe: "Disney",
    strength: 9601,
    speed: 6889,
    intelligence: 7225,
    durability: 9601,
    specialAbility: "Superhuman strength and durability — lifts freight trains, stops 200 mph locomotives; nearly invulnerable to physical damage",
    weaknesses: "Pride and nostalgia blind him; weakest against mental manipulation; wants to work alone",
    description: "Bob Parr — the greatest superhero of his generation, forced into suburban mediocrity. When the call comes again, Mr. Incredible answers it.",
  },
  {
    name: "Buzz Lightyear",
    universe: "Disney",
    strength: 6724,
    speed: 7744,
    intelligence: 7744,
    durability: 7225,
    specialAbility: "Space Ranger combat training; laser wrist weapon; wing-assisted gliding; unshakeable tactical discipline and leadership under pressure",
    weaknesses: "Operates on regulations; can be deactivated by a child; in early form believed he was a real Space Ranger",
    description: "To infinity and beyond. Buzz Lightyear is the definitive heroic archetype — disciplined, brave, loyal, and always the one who actually has a plan.",
  },
  {
    name: "Dr. Facilier",
    universe: "Disney",
    strength: 4624,
    speed: 7056,
    intelligence: 9409,
    durability: 4900,
    specialAbility: "Shadow magic — reads tarot, commands shadow demons, transforms targets via voodoo; backed by his Friends on the Other Side",
    weaknesses: "His power is borrowed — the Friends will collect if he fails; physically fragile; his shadow can be stolen",
    description: "The Shadow Man. Dr. Facilier offers everyone exactly what they want, ensures they can never pay for it, and profits from the difference.",
  },
  {
    name: "Raya",
    universe: "Disney",
    strength: 7056,
    speed: 8649,
    intelligence: 8649,
    durability: 7225,
    specialAbility: "Master sword fighter trained since childhood; Kumandra's last guardian; wields the Dragon Gem that defeated the Druun",
    weaknesses: "Deep distrust from betrayal makes her slow to accept allies; fighting alone when teamwork is needed",
    description: "The last guardian of Kumandra. Raya trained her whole life for a war that destroyed her world, then had to learn that trust was the only real weapon.",
  },
  {
    name: "Merida",
    universe: "Disney",
    strength: 6724,
    speed: 8100,
    intelligence: 7744,
    durability: 6724,
    specialAbility: "Supernatural archer — never misses at any range; expert horse rider and highland combatant; can split an arrow at 200 yards",
    weaknesses: "Impulsiveness over planning; refuses help until crisis peaks; magic she doesn't fully understand",
    description: "Scotland's wildest princess. Merida changed her fate with a bow and arrow, broke a curse with an apology, and is still the best shot in the highlands.",
  },
  {
    name: "Tarzan",
    universe: "Disney",
    strength: 8649,
    speed: 9025,
    intelligence: 7056,
    durability: 8100,
    specialAbility: "Raised by apes — superhuman strength and agility; can swing vine-to-vine faster than a horse can run; primal combat instinct",
    weaknesses: "Naive about human society and its deceptions; protective of his gorilla family above all else",
    description: "Raised by gorillas in the deep jungle, Tarzan is the ultimate apex predator in human form — faster in the canopy than any machine, stronger than any man.",
  },
  {
    name: "The Horned King",
    universe: "Disney",
    strength: 7744,
    speed: 5776,
    intelligence: 9025,
    durability: 8836,
    specialAbility: "Wields the Black Cauldron — can raise armies of the undead (Cauldron-Born) who feel no pain and cannot die; ancient dark lord power",
    weaknesses: "Depends on the Black Cauldron; completely destroyed when the cauldron is sacrificed; arrogance in thinking victory is already won",
    description: "Disney's most terrifying villain. The Horned King doesn't want wealth or power — he wants to cover the world in the dead and rule the silence.",
  },
  {
    name: "Rapunzel",
    universe: "Disney",
    strength: 5476,
    speed: 7225,
    intelligence: 8649,
    durability: 5776,
    specialAbility: "70 feet of enchanted hair as a weapon; healing magic (flower incantation) in its original form; gifted artist, cook, and strategist",
    weaknesses: "Power tied to her hair (cut = no magic); sheltered upbringing limits real-world experience",
    description: "Locked in a tower her whole life, Rapunzel spent her first day of freedom taking on a kingdom with a frying pan and winning.",
  },
  {
    name: "Yzma",
    universe: "Disney",
    strength: 3600,
    speed: 4225,
    intelligence: 9801,
    durability: 4900,
    specialAbility: "Genius alchemist and potion-maker; has a potion for every situation; runs the most overcomplicated evil lairs in Disney history",
    weaknesses: "Extremely physically fragile; overcomplicates every plan when simplicity would work; turned into a cat at the worst moment",
    description: "Advisor, schemer, and the most needlessly theatrical villain alive. Yzma's IQ is matched only by her inexplicable failure rate.",
  },
  {
    name: "Captain Hook",
    universe: "Disney",
    strength: 6400,
    speed: 6724,
    intelligence: 8100,
    durability: 6724,
    specialAbility: "Expert fencer and naval tactician; commands the Jolly Roger and a crew of pirates; the only person Captain Pan genuinely fears",
    weaknesses: "Pathologically terrified of the crocodile with the clock; obsessive revenge blinds him to practical concerns",
    description: "The most feared pirate of Neverland, undone by a ticking crocodile and a boy who refuses to grow up. Hook is, tragically, better than the story he's in.",
  },
  {
    name: "Kronk",
    universe: "Disney",
    strength: 9025,
    speed: 6400,
    intelligence: 4624,
    durability: 8649,
    specialAbility: "Enormous physical strength; speaks squirrel; exceptional chef; shoulder angel/devil conflict renders him unmanipulable by traditional villainy",
    weaknesses: "Too kind-hearted to actually be evil; easily distracted by spinach puffs; conscience won't shut up",
    description: "Yzma's henchman by accident, good person by nature. Kronk is indestructible, speaks to woodland animals, and would do anything for a spinach puff.",
  },

  // ═══════════════════════════════════════════════════════
  //  ANIMALS — large predators, alive and extinct
  // ═══════════════════════════════════════════════════════

  // ── Modern / Still Living ────────────────────────────
  {
    name: "African Lion",
    universe: "Animals",
    strength: 7744,
    speed: 8100,
    intelligence: 6084,
    durability: 6889,
    specialAbility: "Apex ambush predator — crushes prey with 650 psi bite; 500 lb muscled frame; hunts cooperatively in prides to take down buffalo",
    weaknesses: "Requires ambush range to be effective; tires quickly at full sprint; cannot match a crocodile in water",
    description: "The apex predator of the African savanna. A 500 lb engine of muscle and fang that can snap a buffalo's neck and commands fear from every other animal.",
  },
  {
    name: "Siberian Tiger",
    universe: "Animals",
    strength: 8649,
    speed: 7744,
    intelligence: 6400,
    durability: 7744,
    specialAbility: "World's largest cat — 700 lb ambush predator; can drag a 1000 lb elk through deep snow; 1000 psi bite force; retractable 4-inch claws",
    weaknesses: "Solitary — no pack tactics; pursuits over long distance drain energy quickly",
    description: "The largest cat on Earth. The Siberian Tiger hunts alone in sub-zero wilderness, taking prey three times its weight through sheer power and stealth.",
  },
  {
    name: "Grizzly Bear",
    universe: "Animals",
    strength: 9025,
    speed: 6724,
    intelligence: 6400,
    durability: 8649,
    specialAbility: "Can lift 1100 lb, run 35 mph, swipe hard enough to break a moose's spine; 1200 psi bite; 4-inch claws; thick skull resists bear-grade firepower",
    weaknesses: "Poor endurance at high speed; predictable behavior patterns; avoids conflict when possible",
    description: "North America's ultimate land predator. A Grizzly Bear is 700 pounds of muscle, claw, and bite force that can kill a moose with a single swipe.",
  },
  {
    name: "Polar Bear",
    universe: "Animals",
    strength: 9409,
    speed: 7056,
    intelligence: 6084,
    durability: 9025,
    specialAbility: "Earth's largest land predator — 1500 lb frame; ambush hunts seals; swims 100 miles; can survive Arctic cold that kills anything else",
    weaknesses: "Heavily reliant on sea ice habitat; overheats quickly in warm environments",
    description: "The white ghost of the Arctic. A Polar Bear can smell prey 20 miles away, swim 100 miles without rest, and kill a beluga whale with one paw strike.",
  },
  {
    name: "Saltwater Crocodile",
    universe: "Animals",
    strength: 9801,
    speed: 5184,
    intelligence: 5776,
    durability: 9801,
    specialAbility: "3700 psi — most powerful bite on Earth; death roll tears prey apart; armored in osteodermal plates; unchanged predator design for 240 million years",
    weaknesses: "Cold-blooded — becomes sluggish in cold; land mobility is limited; needs water to perform death roll",
    description: "The saltwater crocodile has the strongest bite force of any living animal. It has barely evolved in 240 million years because nothing has made it necessary.",
  },
  {
    name: "Great White Shark",
    universe: "Animals",
    strength: 8836,
    speed: 8649,
    intelligence: 5184,
    durability: 8649,
    specialAbility: "2000 psi bite with 300 serrated teeth; detects blood at 1 part per million; electromagnetic sense locates heartbeats; 2.5-ton ram force",
    weaknesses: "Cannot operate in fresh water; slow turning radius; vulnerable on land",
    description: "Evolution's perfect killing machine. The Great White Shark has hunted the oceans for 11 million years and is still the apex predator of every sea.",
  },
  {
    name: "Orca",
    universe: "Animals",
    strength: 9801,
    speed: 8836,
    intelligence: 8649,
    durability: 9409,
    specialAbility: "Apex ocean predator — hunts great whites, blue whales, and sperm whales; uses coordinated pod tactics; wave-washing to knock prey off ice",
    weaknesses: "Requires ocean environment; can become beached; highly social and psychologically suffers in captivity",
    description: "The wolf of the sea — except wolves don't hunt great white sharks for sport. Orcas are the ocean's apex predator and the most intelligent marine animal alive.",
  },
  {
    name: "Sperm Whale",
    universe: "Animals",
    strength: 9801,
    speed: 6724,
    intelligence: 8100,
    durability: 9801,
    specialAbility: "World's largest toothed predator — 60 tons; battles giant squid in the abyss; uses 230-decibel sonar clicks that can stun or kill prey",
    weaknesses: "Slow surface movement; needs to breathe air; can be harmed by giant squid counterattacks",
    description: "The largest predator that has ever lived. The Sperm Whale hunts giant squid in total darkness miles underwater, armed only with sound and teeth.",
  },
  {
    name: "Hippopotamus",
    universe: "Animals",
    strength: 9601,
    speed: 6400,
    intelligence: 4900,
    durability: 9801,
    specialAbility: "4 tons of territorial aggression — 1800 psi bite, charges at 30 mph in water; skin secretes natural sunscreen/blood-like antiseptic; indestructible",
    weaknesses: "Cannot sustain long land pursuits; requires water proximity; not a predator by diet",
    description: "Africa's most dangerous animal. The hippo kills more humans than lions or leopards — not from hunger, but from pure territorial fury and four-ton muscle.",
  },
  {
    name: "Jaguar",
    universe: "Animals",
    strength: 7744,
    speed: 8100,
    intelligence: 6724,
    durability: 7056,
    specialAbility: "1500 psi bite — strongest of any big cat relative to size; pierces skulls and shells; hunts caimans, anacondas, and capybaras in the Amazon",
    weaknesses: "Smaller range than lion or tiger; avoids open confrontation; solitary",
    description: "The Americas' apex predator. The Jaguar has the strongest bite force of any big cat and is the only one that kills by piercing the skull directly.",
  },
  {
    name: "Snow Leopard",
    universe: "Animals",
    strength: 6889,
    speed: 8649,
    intelligence: 6724,
    durability: 6724,
    specialAbility: "Mountain apex predator — leaps 50 feet horizontally; thick spotted coat for near-perfect camouflage in snow; silent hunter at altitude",
    weaknesses: "Smaller than other big cats; avoids confrontation when possible; declining habitat",
    description: "The ghost of the mountains. The Snow Leopard has never been photographed in the wild by accident — it controls every interaction, then disappears.",
  },
  {
    name: "Komodo Dragon",
    universe: "Animals",
    strength: 7056,
    speed: 5776,
    intelligence: 5476,
    durability: 8649,
    specialAbility: "Venomous bite disrupts blood clotting, causes paralysis; armored in osteoderms; powerful whip-tail; ambushes prey 10x its own size",
    weaknesses: "Dependent on heat; poor endurance at sustained speed; does not heal from severe wounds quickly",
    description: "The world's largest living lizard and a venomous ambush predator. A Komodo Dragon can wait months for prey that bled out from a single bite weeks ago.",
  },
  {
    name: "Spotted Hyena",
    universe: "Animals",
    strength: 7225,
    speed: 8100,
    intelligence: 8100,
    durability: 7744,
    specialAbility: "1100 psi bite — cracks elephant bone; pack hunting intelligence rivals primates; extreme endurance chase at 36 mph for miles",
    weaknesses: "Social structure dependency — weaker alone than in clans; smaller skull than lion despite stronger bite",
    description: "The most misunderstood apex predator in Africa. Hyenas are more intelligent than most primates, crack elephant bones for breakfast, and outrun lions over distance.",
  },
  {
    name: "Gray Wolf",
    universe: "Animals",
    strength: 6084,
    speed: 8649,
    intelligence: 8649,
    durability: 6724,
    specialAbility: "Pack apex predator — coordinated pursuit hunts elk and bison; 1500 psi jaw; incredible stamina over 35 miles; complex social tactics",
    weaknesses: "Individual wolf is dramatically weaker than most apex predators; pack dependency is essential",
    description: "The ultimate pack predator. A Gray Wolf can run 35 miles non-stop, coordinate with its pack like a military unit, and take down prey ten times its size.",
  },
  {
    name: "Bull Shark",
    universe: "Animals",
    strength: 7744,
    speed: 8100,
    intelligence: 4900,
    durability: 8100,
    specialAbility: "Thrives in fresh and salt water — found miles up rivers; most aggressive shark species; highest testosterone of any animal per body weight",
    weaknesses: "Smaller than Great White; less ambush speed; territorial rather than coordinated hunter",
    description: "The most dangerous shark to humans. Bull sharks swim up rivers, lurk in shallow water, and are responsible for the majority of shark attacks worldwide.",
  },
  {
    name: "African Wild Dog",
    universe: "Animals",
    strength: 5776,
    speed: 9025,
    intelligence: 9025,
    durability: 5776,
    specialAbility: "80% hunt success rate — highest of any predator; pack coordination rivals wolf; sustains 44 mph for over 3 miles; democratic voting behavior",
    weaknesses: "Individual animal is small; easily overwhelmed by larger predators; needs large range",
    description: "The most successful predator on Earth by hunt-to-kill ratio. African Wild Dogs vote on pack decisions, coordinate like soldiers, and almost never fail.",
  },
  {
    name: "Wolverine (Animal)",
    universe: "Animals",
    strength: 6724,
    speed: 6084,
    intelligence: 6400,
    durability: 9025,
    specialAbility: "Fearless pound-for-pound fighter — drives grizzly bears off kills; scent glands deter predators; semi-retractable claws tear through frozen carcasses",
    weaknesses: "Small body (40 lbs max); not built for endurance combat against much larger animals",
    description: "The demon of the boreal forest. A wolverine weighs 40 pounds and regularly steals kills from grizzly bears. Pound for pound, the most fearless predator alive.",
  },
  {
    name: "King Cobra",
    universe: "Animals",
    strength: 4225,
    speed: 7744,
    intelligence: 6084,
    durability: 5184,
    specialAbility: "Longest venomous snake alive — 18 feet; venom shuts down the nervous system in minutes; can kill an elephant with a single bite",
    weaknesses: "Avoids confrontation when possible; cold temperatures reduce speed and venom effectiveness",
    description: "The world's longest venomous snake and one of the most intelligent reptiles. The King Cobra can kill an elephant and stands up to face threats eye-to-eye.",
  },
  {
    name: "Green Anaconda",
    universe: "Animals",
    strength: 9025,
    speed: 4900,
    intelligence: 3600,
    durability: 8836,
    specialAbility: "World's heaviest snake — 550 lbs of constricting muscle; water ambush predator; can swallow a jaguar whole; 300 psi crushing force",
    weaknesses: "Very slow on land; relies on water for ambush; no venom",
    description: "The heaviest snake ever recorded and one of the most powerful constrictors on Earth. The Green Anaconda can squeeze the life out of a fully grown caiman.",
  },
  {
    name: "Harpy Eagle",
    universe: "Animals",
    strength: 6400,
    speed: 9025,
    intelligence: 7225,
    durability: 5476,
    specialAbility: "Talons exert 110 lbs of crushing force — more than a Rottweiler's bite; snatches monkeys and sloths from the canopy at 50 mph",
    weaknesses: "Depends on forest canopy; vulnerable on the ground; declining population",
    description: "The apex aerial predator of the Amazon. The Harpy Eagle has talons as long as a grizzly bear's claws and can pluck a monkey from a treetop at full speed.",
  },
  {
    name: "Nile Monitor",
    universe: "Animals",
    strength: 6724,
    speed: 5776,
    intelligence: 6084,
    durability: 7744,
    specialAbility: "Africa's largest lizard — powerful tail whip, 5-inch claws, muscular bite; hunts crocodile eggs, fish, birds, and carrion; fast swimmer",
    weaknesses: "Cold-blooded; not an endurance fighter at sustained effort; threatened by larger predators",
    description: "Africa's most formidable lizard. The Nile Monitor can swim, climb, and dig — a relentless opportunistic predator feared by everything smaller than a croc.",
  },

  // ── Extinct predators ────────────────────────────────
  {
    name: "Tyrannosaurus Rex",
    universe: "Animals",
    strength: 10000,
    speed: 5776,
    intelligence: 3600,
    durability: 9801,
    specialAbility: "12,800 psi bite force — most powerful of any terrestrial predator ever; binocular vision superior to modern hawks; 9-ton frame that shatters bone",
    weaknesses: "Debated running speed (likely 12–25 mph); small arms are useless; massive body is difficult to maneuver",
    description: "The Tyrant Lizard King. T. Rex had the most powerful bite force ever measured in a land animal — enough to shatter the bones of prey and swallow them whole.",
  },
  {
    name: "Spinosaurus",
    universe: "Animals",
    strength: 9801,
    speed: 6084,
    intelligence: 3364,
    durability: 9601,
    specialAbility: "Largest predatory dinosaur ever — 50 feet, 20 tons; semi-aquatic apex predator; 7-inch teeth and powerful forelimbs; 10-foot sail for thermoregulation",
    weaknesses: "Adapted primarily to aquatic hunting; slower and less armored than T. Rex on land; slender conical teeth break against bone",
    description: "The largest meat-eating dinosaur to ever exist — bigger than T. Rex. Spinosaurus was a river-monster that hunted giant fish and anything else that entered its water.",
  },
  {
    name: "Megalodon",
    universe: "Animals",
    strength: 9801,
    speed: 8100,
    intelligence: 3025,
    durability: 9801,
    specialAbility: "40,000 psi bite — most powerful bite force in history; 60-foot body the size of a school bus; 7-inch triangular teeth; preyed on whales",
    weaknesses: "Required enormous caloric input (whales); climate change and prey depletion ended the species",
    description: "The largest shark that ever lived. Megalodon made the Great White look like a goldfish — a 60-foot apex predator that fed exclusively on whales.",
  },
  {
    name: "Smilodon",
    universe: "Animals",
    strength: 9025,
    speed: 7744,
    intelligence: 5476,
    durability: 8649,
    specialAbility: "11-inch saber fangs pierce the windpipe in a single crushing bite; 600 lb muscled ambush predator; hunted mammoths in packs",
    weaknesses: "Saber teeth are fragile — cannot bite bone; extinction linked to prey collapse; smaller brain than modern cats",
    description: "The Saber-Toothed Tiger. Smilodon wasn't faster or smarter than modern big cats — but its fangs could puncture a mammoth's skull, and that was enough.",
  },
  {
    name: "Allosaurus",
    universe: "Animals",
    strength: 9025,
    speed: 7056,
    intelligence: 3844,
    durability: 8836,
    specialAbility: "Jurassic apex predator — hatchet-attack style using its skull as a weapon; pack-hunts Brachiosaurus; 5-foot skull with 70 serrated teeth",
    weaknesses: "Smaller than later large theropods; depended on pack coordination for the largest prey",
    description: "Before T. Rex, Allosaurus ruled the Jurassic. This was the lion of the dinosaur world — fast, fierce, and willing to take on prey three times its own size.",
  },
  {
    name: "Giganotosaurus",
    universe: "Animals",
    strength: 9604,
    speed: 6724,
    intelligence: 3600,
    durability: 9409,
    specialAbility: "Longest carnivorous dinosaur — 47 feet; pack hunted titanosaur sauropods; faster than T. Rex with a more slender skull optimized for slashing",
    weaknesses: "Bite force weaker than T. Rex; slashing teeth rather than crushing; smaller temporal brain",
    description: "South America's apex dinosaur predator and one of the largest carnivores ever. Giganotosaurus hunted the biggest creatures on land — in coordinated packs.",
  },
  {
    name: "Velociraptor",
    universe: "Animals",
    strength: 5476,
    speed: 9409,
    intelligence: 8100,
    durability: 5184,
    specialAbility: "Sickle-claw foot pin-and-slice tactic; warm-blooded feathered predator; pack hunting with sophisticated coordination; fastest small theropod",
    weaknesses: "Turkey-sized in reality (not Jurassic Park scale); fragile relative to larger dinosaurs",
    description: "The real Velociraptor was turkey-sized — but Jurassic Park got one thing right: the intelligence. The deadliest small theropod that ever lived, hunting in packs.",
  },
  {
    name: "Mosasaurus",
    universe: "Animals",
    strength: 9801,
    speed: 8100,
    intelligence: 4225,
    durability: 9601,
    specialAbility: "56-foot ocean apex predator; double-hinged jaw swallows prey whole; mosasaurs dominated the Late Cretaceous seas; faster than most sharks",
    weaknesses: "Required breathing air; cold water reduced effectiveness; massive size limits maneuverability",
    description: "The ocean's answer to T. Rex. Mosasaurus was a 56-foot sea dragon that dominated the Cretaceous seas and made the Great White Shark look like prey.",
  },
  {
    name: "Quetzalcoatlus",
    universe: "Animals",
    strength: 7744,
    speed: 8649,
    intelligence: 4624,
    durability: 6724,
    specialAbility: "Largest flying animal ever — 36-foot wingspan, 550 lb; pole-vaults into flight; stabs prey with lance-like 8-foot beak; hunts like a giant stork",
    weaknesses: "Hollow bones are fragile; cannot sustain prolonged aerial combat; grounded by severe weather",
    description: "The largest flying creature in Earth's history. Quetzalcoatlus was as tall as a giraffe when standing, with a wingspan wider than an F-16 fighter jet.",
  },
  {
    name: "Short-Faced Bear",
    universe: "Animals",
    strength: 9801,
    speed: 8100,
    intelligence: 5476,
    durability: 9601,
    specialAbility: "Largest terrestrial mammalian predator — 2000 lb; longer legs than any bear; could run 40 mph; dominated North America for 800,000 years",
    weaknesses: "Massive caloric requirements; climate change collapse in prey at end of Pleistocene",
    description: "Arctodus simus — the Short-Faced Bear was twice the size of a Grizzly and could run 40 miles per hour. It made cave lions flinch.",
  },
  {
    name: "Andrewsarchus",
    universe: "Animals",
    strength: 9601,
    speed: 7225,
    intelligence: 4900,
    durability: 9409,
    specialAbility: "Largest terrestrial mammalian predator of the Eocene — estimated 1000+ lbs; skull alone is 3 feet long; crushing bone-cracking molars",
    weaknesses: "Known only from skull fragments — behavior is inferred; possibly scavenged more than actively hunted",
    description: "Andrewsarchus had the largest skull of any known land mammal predator. Walking on hooves, this was the most terrifying meat-eater of the ancient world.",
  },
  {
    name: "Carnotaurus",
    universe: "Animals",
    strength: 8836,
    speed: 8649,
    intelligence: 3364,
    durability: 8649,
    specialAbility: "Fastest large theropod — sustained 35 mph sprint; bull-like bone horns for head-butting; forward-facing eyes for excellent depth perception",
    weaknesses: "Comically small arms even by theropod standards; lighter build than T. Rex or Spinosaurus",
    description: "The bull dinosaur. Carnotaurus was built differently — horns, forward eyes, and legs designed for speed. It was the fastest large predator of its era.",
  },
  {
    name: "Dire Wolf",
    universe: "Animals",
    strength: 7225,
    speed: 8100,
    intelligence: 8100,
    durability: 7744,
    specialAbility: "Pack apex predator of the Pleistocene — larger, heavier, and with stronger jaws than a Gray Wolf; coordinated megafauna hunting tactics",
    weaknesses: "Specialist pack predator — depended on large prey that went extinct; couldn't adapt to smaller prey like modern wolves",
    description: "Game of Thrones made them famous — paleontology made them terrifying. The Dire Wolf was a larger, more powerful Gray Wolf that hunted prehistoric megafauna in packs.",
  },
  {
    name: "Dunkleosteus",
    universe: "Animals",
    strength: 9601,
    speed: 6724,
    intelligence: 2025,
    durability: 10000,
    specialAbility: "Self-sharpening bone-blade jaws — 80,000 psi bite force (estimated strongest in fish history); armored head and thorax in 2-inch bone plates",
    weaknesses: "Large and slow-turning; extinct 360 million years ago; no teeth — bone blades only",
    description: "The armored terror of the Devonian seas. Dunkleosteus had bone-plated armor and self-sharpening blade jaws that may have been the most powerful bite in history.",
  },
];

async function main() {
  console.log(`Seeding ${characters.length} Disney & Animals characters...`);
  let added = 0;
  let skipped = 0;

  for (const char of characters) {
    const existing = await db.execute(
      sql`SELECT id FROM characters WHERE LOWER(name) = LOWER(${char.name}) LIMIT 1`
    );
    if ((existing as any).rows?.length > 0) {
      console.log(`  SKIP (exists): ${char.name}`);
      skipped++;
      continue;
    }
    await db.insert(charactersTable).values(char);
    console.log(`  + ${char.name} (${char.universe})`);
    added++;
  }

  console.log(`\nDone. Added: ${added}, Skipped: ${skipped}`);
  process.exit(0);
}

main().catch(err => { console.error(err); process.exit(1); });
