// ── Daily themes ─────────────────────────────────────────────────────────────
// Day-of-week themed lineup. Each day has a CONCEPT (not just a universe):
//
//   Sun  SHOWDOWN SUNDAY        heroes vs villains
//   Mon  MARVEL vs DC MONDAY    the eternal big-two crossover
//   Tue  TEAM-UP TUESDAY        squads & multi-character team brawls
//   Wed  WORLDS COLLIDE WEDNESDAY  cross-franchise crossovers
//   Thu  THROWDOWN THURSDAY     villain-vs-villain & horror icons
//   Fri  FACE-OFF FRIDAY        classic rivals & mirror matches
//   Sat  STREET-LEVEL SATURDAY  real fighters, no cosmic / no god-tier
//
// Each theme has its own bucket of matchups. Buckets are pre-shuffled with a
// per-theme deterministic seed; we walk DAILY_LINEUP_SIZE entries through
// each bucket using `offset = (weekIndex * size) % bucket.length`, so every
// matchup in a theme bucket appears exactly once before any repeat on that
// day-of-week (e.g. rivals bucket = 116 → 12 Fridays of unique pairings;
// marvel_vs_dc = 31 → 3 Mondays before any Marvel-vs-DC matchup repeats).
//
// Tag source: each pool entry is hand-classified via inferred composition
// (character role + universe family from the DB). The classification is
// baked in here as ENTRY_THEMES so the runtime path has no DB dependency.
// Entries can belong to multiple themes (Avengers vs Justice League is
// marvel_vs_dc AND team) — they show up in every bucket they qualify for.
//
// Lineup-stability invariant: once `ensureDailyRows` materializes a date,
// those rows ARE the canonical lineup. This module's selection only affects
// dates that have NOT been materialized yet. Already-stored dates are never
// reshuffled by a code change here — enforced in routes/daily.ts.

import { DAILY_POOL, type DailyPoolEntry, DAILY_LINEUP_SIZE } from "./dailyPool";

// ── Theme types ──────────────────────────────────────────────────────────────
export type ThemeKey =
  | "showdown"      // Sun — heroes vs villains
  | "marvel_vs_dc"  // Mon — pure Marvel vs DC matchups
  | "team"          // Tue — multi-character team brawls
  | "crossover"     // Wed — cross-franchise (not just Marvel/DC)
  | "throwdown"     // Thu — villain-vs-villain + horror icons
  | "rivals"        // Fri — 1v1 same-universe rivalries / mirror matches
  | "street"        // Sat — grounded real fighters, no cosmic tier
  | "wildcard";     // safety net — full pool

export type DailyTheme = {
  key: ThemeKey;
  label: string;       // header label, e.g. "SHOWDOWN SUNDAY"
  blurb: string;       // one-line subhead description
};

// JS Date.getUTCDay(): 0 = Sunday, 1 = Monday, ..., 6 = Saturday.
// We compute day-of-week off the ET-anchored calendar date string from
// getDailyDateString, so each theme aligns with the calendar day the user
// actually sees on the page (8pm ET rollover → ET calendar day).
const DAY_THEMES: Record<number, DailyTheme> = {
  0: { key: "showdown",     label: "SHOWDOWN SUNDAY",         blurb: "Heroes vs villains. Good vs evil. Pick a side." },
  1: { key: "marvel_vs_dc", label: "MARVEL vs DC MONDAY",     blurb: "The eternal debate. Settle it today." },
  2: { key: "team",         label: "TEAM-UP TUESDAY",         blurb: "Squads, factions, and full-roster brawls." },
  3: { key: "crossover",    label: "WORLDS COLLIDE WEDNESDAY", blurb: "Universes that were never meant to meet." },
  4: { key: "throwdown",    label: "THROWDOWN THURSDAY",      blurb: "Villains, slashers, and the worst people alive." },
  5: { key: "rivals",       label: "FACE-OFF FRIDAY",         blurb: "Classic rivalries. Mirror matches. Personal beef." },
  6: { key: "street",       label: "STREET-LEVEL SATURDAY",   blurb: "Real fighters. No gods. No cheats. Flesh and bone." },
};

// ── ENTRY_THEMES ─────────────────────────────────────────────────────────────
// Generated by classifying each DAILY_POOL entry from its character roster
// (universe family + hero/villain role + team size). Any entry not listed
// here falls into the `wildcard` bucket only. Keep in sync with DAILY_POOL.
export const ENTRY_THEMES: Record<string, ThemeKey[]> = {
  "aang-vs-azula": ["rivals"],
  "adam-warlock-vs-thanos": ["showdown", "rivals"],
  "akatsuki-coup": [],
  "akaza-vs-kokushibo": ["throwdown", "rivals"],
  "akuma-vs-bison": ["throwdown", "rivals", "street"],
  "alien-vs-predator": ["crossover", "throwdown"],
  "all-for-one-vs-all-might": ["showdown", "rivals"],
  "all-might-vs-goku": ["rivals"],
  "all-might-vs-saitama": ["crossover"],
  "alucard-vs-dracula": ["crossover"],
  "anti-monitor-vs-thanos": ["marvel_vs_dc", "throwdown"],
  "apocalypse-vs-magneto": ["throwdown", "rivals"],
  "arceus-vs-mewtwo": ["rivals"],
  "ash-vs-pinhead": ["throwdown", "rivals"],
  "asta-vs-yuno": ["rivals"],
  "atrocitus-vs-sinestro": ["throwdown", "rivals"],
  "avengers-vs-justice-league": ["marvel_vs_dc", "team"],
  "avengers-vs-xmen": ["team"],
  "bane-vs-batman": ["showdown", "rivals"],
  "bane-vs-hulk": ["showdown", "marvel_vs_dc"],
  "bat-family-vs-batman": ["team"],
  "bat-family-vs-rogues": ["team"],
  "batman-vs-daredevil": ["marvel_vs_dc", "street"],
  "batman-vs-john-wick": ["crossover", "street"],
  "batman-vs-punisher": ["marvel_vs_dc"],
  "bayonetta-vs-dante": ["rivals"],
  "beerus-vs-darkseid": ["crossover"],
  "beerus-vs-superman": ["crossover"],
  "beerus-vs-thor": ["crossover"],
  "beta-ray-bill-vs-thor": ["rivals"],
  "billionaires-with-toys": ["showdown", "team"],
  "bishop-vs-cable": ["rivals"],
  "black-panther-vs-batman": ["marvel_vs_dc"],
  "bleach-vs-naruto": ["team"],
  "boba-fett-vs-predator": ["throwdown", "rivals"],
  "brainiac-vs-lex-luthor": ["throwdown", "rivals"],
  "broly-vs-goku": ["rivals"],
  "broly-vs-hulk": ["crossover"],
  "captain-america-vs-wonder-woman": ["marvel_vs_dc"],
  "carnage-vs-venom": ["throwdown", "rivals"],
  "chainsaw-vs-jjk": ["team", "throwdown"],
  "charizard-vs-mewtwo": ["rivals"],
  "chief-vs-samus": ["crossover"],
  "cloud-vs-sephiroth": ["showdown", "rivals"],
  "daenerys-vs-cersei": ["rivals"],
  "dante-vs-vergil": ["showdown", "rivals"],
  "darth-vader-vs-yoda": ["rivals"],
  "dc-women-vs-marvel-women": ["marvel_vs_dc", "team"],
  "deadpool-vs-deathstroke": ["showdown", "marvel_vs_dc"],
  "denji-vs-power": ["rivals"],
  "devil-summit": ["team", "throwdown"],
  "devils-vs-angels": ["showdown", "team"],
  "doctor-doom-vs-doctor-strange": ["showdown", "rivals"],
  "doctor-manhattan-vs-strange": ["showdown", "marvel_vs_dc"],
  "doctor-manhattan-vs-superman": ["showdown", "rivals"],
  "doma-vs-akaza": ["throwdown", "rivals"],
  "doom-slayer-vs-kratos": ["rivals"],
  "doom-vs-lex": ["marvel_vs_dc", "throwdown"],
  "doomsday-vs-hulk": ["showdown", "marvel_vs_dc"],
  "dormammu-vs-galactus": ["throwdown", "rivals"],
  "edward-vs-roy": ["rivals"],
  "ellie-vs-aloy": ["rivals"],
  "emma-frost-vs-professor-x": ["rivals"],
  "endeavor-vs-all-might": ["rivals"],
  "fantastic-four-vs-x-men": ["team"],
  "father-vs-aizen": ["throwdown", "rivals"],
  "flash-vs-quicksilver": ["marvel_vs_dc"],
  "four-horsemen-vs-x-men": ["showdown", "team"],
  "freddy-vs-jason": ["throwdown", "rivals"],
  "frieza-vs-cell": ["throwdown", "rivals"],
  "frozone-vs-iceman": ["crossover"],
  "galactus-vs-anos": ["crossover"],
  "gandalf-vs-saruman": ["showdown", "rivals"],
  "general-zod-vs-superman": ["showdown", "rivals"],
  "geralt-vs-aloy": ["rivals"],
  "geralt-vs-aragorn": ["crossover"],
  "ghost-rider-vs-pennywise": ["showdown", "crossover", "throwdown"],
  "godzilla-vs-king-kong": ["rivals"],
  "godzilla-vs-mechagodzilla": ["rivals"],
  "gohan-vs-cell": ["showdown", "rivals"],
  "gojo-vs-aizen": ["rivals"],
  "gojo-vs-sukuna": ["rivals"],
  "goku-vs-jiren": ["rivals"],
  "goku-vs-naruto": ["rivals"],
  "goku-vs-superman": ["crossover"],
  "goku-vs-vegeta": ["rivals"],
  "green-lantern-corps-vs-sinestro-corps": ["showdown", "team"],
  "green-lantern-vs-silver-surfer": ["marvel_vs_dc"],
  "hannibal-vs-light": ["crossover", "throwdown"],
  "harry-vs-voldemort": ["showdown", "rivals"],
  "hawkeye-vs-green-arrow": ["marvel_vs_dc", "street"],
  "hela-vs-apocalypse": ["throwdown", "rivals"],
  "hitsugaya-vs-sub-zero": ["crossover"],
  "horror-icons-vs-slashers": ["team", "throwdown"],
  "hulk-vs-superman": ["marvel_vs_dc"],
  "ichigo-vs-yhwach": ["rivals"],
  "iron-fist-vs-shang-chi": ["rivals"],
  "iron-man-vs-batman": ["marvel_vs_dc"],
  "itachi-vs-sasuke": ["rivals"],
  "jean-vs-scarlet-witch": ["rivals"],
  "jin-vs-aragorn": ["crossover"],
  "jiren-vs-saitama": ["crossover"],
  "john-mcclane-vs-john-wick": ["rivals", "street"],
  "justice-league-vs-legion-of-doom": ["showdown", "team"],
  "kaido-vs-whitebeard": ["rivals"],
  "kenshiro-vs-jotaro": ["rivals"],
  "knuckles-vs-wolverine": ["crossover"],
  "knull-vs-thor": ["showdown", "rivals"],
  "kratos-vs-doomslayer": ["rivals"],
  "kratos-vs-master-chief": ["showdown", "crossover"],
  "kratos-vs-thor": ["showdown", "crossover"],
  "lara-vs-indy": ["crossover", "street"],
  "lara-vs-nathan": ["rivals", "street"],
  "larfleeze-vs-sinestro": ["throwdown", "rivals"],
  "light-vs-l": ["rivals"],
  "link-vs-cloud": ["rivals"],
  "link-vs-ganondorf": ["showdown", "rivals"],
  "living-tribunal-vs-anti-monitor": ["marvel_vs_dc"],
  "luffy-vs-naruto": ["rivals"],
  "luke-cage-vs-colossus": ["rivals"],
  "luke-vs-kylo": ["rivals"],
  "mace-vs-palpatine": ["rivals"],
  "magneto-vs-professor-x": ["showdown", "rivals"],
  "makima-vs-light": ["crossover", "throwdown"],
  "mario-vs-bowser": ["showdown", "rivals"],
  "marvel-cosmic-vs-dc-cosmic": ["marvel_vs_dc", "team"],
  "master-chief-vs-solid-snake": ["crossover"],
  "mephisto-vs-trigon": ["marvel_vs_dc", "throwdown"],
  "meruem-vs-goku": ["showdown", "rivals"],
  "mha-vs-jjk": ["showdown", "team"],
  "michael-vs-jason": ["throwdown", "rivals"],
  "mob-vs-saitama": ["rivals"],
  "mongul-vs-superman": ["showdown", "rivals"],
  "moon-knight-vs-daredevil": ["rivals", "street"],
  "mr-incredible-vs-hulk": ["crossover"],
  "naruto-vs-sasuke-final": ["rivals"],
  "neo-vs-terminator": ["crossover"],
  "night-king-vs-sauron": ["crossover", "throwdown"],
  "nightwing-vs-red-hood": ["rivals", "street"],
  "onslaught-vs-sentry": ["throwdown", "rivals"],
  "optimus-vs-megatron": ["rivals"],
  "optimus-vs-vader": ["rivals"],
  "phoenix-vs-galactus": ["showdown", "rivals"],
  "pikachu-vs-mewtwo": ["showdown", "rivals"],
  "pinhead-vs-pennywise": ["throwdown", "rivals"],
  "predator-vs-terminator": ["rivals"],
  "psylocke-vs-storm": ["rivals"],
  "punisher-vs-deathstroke": ["showdown", "marvel_vs_dc", "street"],
  "rambo-vs-predator": ["crossover"],
  "ras-al-ghul-vs-batman": ["showdown", "rivals"],
  "rayquaza-vs-charizard": ["rivals"],
  "riddler-vs-sherlock": ["crossover"],
  "rimuru-vs-goku": ["crossover"],
  "robocop-vs-judge-dredd": ["crossover"],
  "robocop-vs-t1000": ["crossover"],
  "ryu-vs-akuma": ["rivals", "street"],
  "saitama-vs-garou": ["rivals"],
  "saitama-vs-goku": ["crossover"],
  "saitama-vs-superman": ["crossover"],
  "sauron-vs-voldemort": ["throwdown", "rivals"],
  "scarlet-witch-vs-dr-strange": ["rivals"],
  "scarlet-witch-vs-raven": ["marvel_vs_dc"],
  "scarlet-witch-vs-wonder-woman": ["marvel_vs_dc"],
  "sentry-vs-hyperion": ["throwdown", "rivals"],
  "she-hulk-vs-wonder-woman": ["marvel_vs_dc"],
  "sherlock-vs-light": ["rivals"],
  "sinestro-vs-green-lantern": ["showdown", "rivals"],
  "solo-leveling-vs-hxh": ["crossover"],
  "sorcerers-summit": ["showdown", "team", "crossover"],
  "speedsters-relay": ["marvel_vs_dc", "team"],
  "spider-man-vs-miles": ["rivals"],
  "spider-man-vs-venom": ["showdown", "rivals"],
  "spiderman-vs-daredevil": ["rivals"],
  "storm-vs-magneto": ["showdown", "rivals"],
  "strange-vs-dr-fate": ["marvel_vs_dc"],
  "street-tier-war": ["team"],
  "sub-zero-vs-raiden": ["rivals", "street"],
  "sub-zero-vs-scorpion": ["throwdown", "rivals", "street"],
  "sukuna-vs-aizen": ["throwdown", "rivals"],
  "sukuna-vs-yhwach": ["throwdown", "rivals"],
  "superman-vs-sentry": ["marvel_vs_dc"],
  "superman-vs-thor": ["marvel_vs_dc"],
  "syndrome-vs-lex": ["crossover"],
  "t1000-vs-t800": ["rivals"],
  "teen-titans-vs-x-men": ["marvel_vs_dc", "team"],
  "thanos-vs-darkseid": ["marvel_vs_dc", "throwdown"],
  "thanos-vs-darkseid-cosmic": ["marvel_vs_dc", "throwdown"],
  "thor-vs-loki": ["showdown", "rivals"],
  "vegeta-vs-frieza": ["showdown", "rivals"],
  "vergil-vs-sephiroth": ["throwdown", "rivals"],
  "voldemort-vs-gandalf": ["showdown", "rivals"],
  "wally-vs-barry": ["rivals"],
  "wick-vs-bond": ["rivals", "street"],
  "wick-vs-bourne": ["rivals", "street"],
  "wolverine-vs-cyclops": ["rivals"],
  "wolverine-vs-deadpool": ["rivals"],
  "wolverine-vs-sabretooth": ["showdown", "rivals"],
  "yusuke-vs-saitama": ["rivals"],
  "z-fighters-vs-dbz-villains": ["showdown", "team"],
  "zeus-vs-thor": ["crossover"],
  "zoro-vs-mihawk": ["rivals"],
  "zuko-vs-azula": ["rivals"],
};

// ── PRNG (mulberry32) ────────────────────────────────────────────────────────
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return function () {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function themeSeed(key: ThemeKey): number {
  // Cheap deterministic 32-bit hash so each theme has a stable, distinct
  // initial shuffle order across server restarts.
  let h = 2166136261;
  for (let i = 0; i < key.length; i++) {
    h ^= key.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

// ── Bucket build (memoized; pure over DAILY_POOL + ENTRY_THEMES) ─────────────
type BucketMap = Map<ThemeKey, DailyPoolEntry[]>;

let _buckets: BucketMap | null = null;

function buildBuckets(): BucketMap {
  const themes: ThemeKey[] = [
    "showdown", "marvel_vs_dc", "team", "crossover",
    "throwdown", "rivals", "street", "wildcard",
  ];
  const map: BucketMap = new Map(themes.map((t) => [t, [] as DailyPoolEntry[]]));
  for (const entry of DAILY_POOL) {
    const tags = ENTRY_THEMES[entry.id] ?? [];
    for (const t of tags) {
      const bucket = map.get(t);
      if (bucket) bucket.push(entry);
    }
    // wildcard always contains the full pool (safety net for any themed
    // bucket that ends up smaller than DAILY_LINEUP_SIZE).
    map.get("wildcard")!.push(entry);
  }
  // Per-bucket deterministic Fisher-Yates so the walk order is stable across
  // server restarts but distinct between themes.
  for (const t of themes) {
    const list = map.get(t)!;
    const rng = mulberry32(themeSeed(t));
    for (let i = list.length - 1; i > 0; i--) {
      const j = Math.floor(rng() * (i + 1));
      const tmp = list[i]!;
      list[i] = list[j]!;
      list[j] = tmp;
    }
  }
  return map;
}

function getBuckets(): BucketMap {
  if (_buckets === null) _buckets = buildBuckets();
  return _buckets;
}

// ── Date helpers ─────────────────────────────────────────────────────────────
function epochDaysFromDate(dateStr: string): number {
  return Math.floor(Date.UTC(
    Number(dateStr.slice(0, 4)),
    Number(dateStr.slice(5, 7)) - 1,
    Number(dateStr.slice(8, 10)),
  ) / 86400000);
}

function dayOfWeekFromDate(dateStr: string): number {
  // dateStr is the ET-anchored calendar date string (YYYY-MM-DD). We read
  // the weekday from UTC midnight of that date — for any YYYY-MM-DD this
  // returns the weekday of that calendar date, which is what the user
  // sees on the page.
  const d = new Date(`${dateStr}T00:00:00Z`);
  return d.getUTCDay();
}

// ── Public API ───────────────────────────────────────────────────────────────
export function getDailyThemeForDate(dateStr: string): DailyTheme {
  return DAY_THEMES[dayOfWeekFromDate(dateStr)]!;
}

// Themed lineup for a given date. Walks DAILY_LINEUP_SIZE entries through
// the theme bucket starting at offset = (weekIndex * LINEUP_SIZE) % size.
// This means every entry in the theme's bucket appears once before any
// matchup repeats on that day-of-week. Then we do a tiny per-day re-shuffle
// inside the chosen slice so the display order on the page varies day to
// day even within the same theme-week.
export function getThemedDailyMatchupsForDate(
  dateStr: string,
  count: number = DAILY_LINEUP_SIZE,
): { theme: DailyTheme; entries: DailyPoolEntry[] } {
  const theme = getDailyThemeForDate(dateStr);
  const buckets = getBuckets();
  const bucket = buckets.get(theme.key) ?? [];
  // If the themed bucket can't supply enough distinct entries, fall back
  // to wildcard (full pool) for the gap. Defensive — keeps the function
  // total even if a future pool edit shrinks a themed bucket below 10.
  let pool: DailyPoolEntry[] = bucket;
  if (pool.length < count) {
    const wildcard = buckets.get("wildcard") ?? [];
    const seen = new Set(pool.map((e) => e.id));
    pool = [...pool, ...wildcard.filter((e) => !seen.has(e.id))];
  }
  if (pool.length === 0) {
    return { theme, entries: [] };
  }
  const epochDays = epochDaysFromDate(dateStr);
  const weekIndex = Math.floor(epochDays / 7);
  const size = pool.length;
  const offset = (((weekIndex * count) % size) + size) % size;
  const picks: DailyPoolEntry[] = [];
  for (let i = 0; i < count; i++) {
    picks.push(pool[(offset + i) % size]!);
  }
  // Per-day display-order reshuffle of the chosen 10.
  const dayRng = mulberry32(Math.imul(epochDays + 1, 2654435761));
  for (let i = picks.length - 1; i > 0; i--) {
    const j = Math.floor(dayRng() * (i + 1));
    const tmp = picks[i]!;
    picks[i] = picks[j]!;
    picks[j] = tmp;
  }
  return { theme, entries: picks };
}

// Debug helper — used by tests or admin tooling to inspect how big each
// themed bucket ended up. Not used in request paths.
export function getThemeBucketSizes(): Record<ThemeKey, number> {
  const buckets = getBuckets();
  const out = {} as Record<ThemeKey, number>;
  for (const [k, v] of buckets) out[k] = v.length;
  return out;
}
