// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ava-intro/Intro.tsx": () => import("../components/mockups/ava-intro/Intro.tsx"),
  "./components/mockups/ava-redesign/HomeRedesign.tsx": () => import("../components/mockups/ava-redesign/HomeRedesign.tsx")
};
