export type UniverseCategory =
  | "Multiverse"
  | "Legacy"
  | "Kingdom"
  | "Anime"
  | "Games"
  | "Movies & TV"
  | "Fantasy & Books"
  | "Cartoons"
  | "Myth & History"
  | "Horror"
  | "Variants"
  | "Other";

export const CATEGORY_ORDER: UniverseCategory[] = [
  "Multiverse",
  "Legacy",
  "Kingdom",
  "Anime",
  "Games",
  "Movies & TV",
  "Fantasy & Books",
  "Cartoons",
  "Myth & History",
  "Horror",
  "Variants",
  "Other",
];

export const CATEGORY_COLORS: Record<UniverseCategory, string> = {
  "Multiverse":      "#ed1d24",
  "Legacy":          "#0476f2",
  "Kingdom":          "#bf5af2",
  "Anime":           "#ff6b9d",
  "Games":           "#30d158",
  "Movies & TV":     "#ff9f0a",
  "Fantasy & Books": "#c084fc",
  "Cartoons":        "#ffe234",
  "Myth & History":  "#d4a574",
  "Horror":          "#8e1a3a",
  "Variants":        "#22d3ee",
  "Other":           "#94a3b8",
};

const UNIVERSE_TO_CATEGORY: Record<string, UniverseCategory> = {
  // Multiverse
  "Multiverse Comics": "Multiverse",
  "Marvel": "Multiverse",
  // Legacy
  "Legacy Comics": "Legacy",
  "DC": "Legacy",
  "Watchmen": "Legacy",
  // Kingdom
  "Kingdom": "Kingdom",
  // Anime / Manga
  "Naruto": "Anime",
  "Dragon Ball": "Anime",
  "One Piece": "Anime",
  "Bleach": "Anime",
  "Demon Slayer": "Anime",
  "JoJo's Bizarre Adventure": "Anime",
  "Digimon": "Anime",
  "Fullmetal Alchemist": "Anime",
  "My Hero Academia": "Anime",
  "Fairy Tail": "Anime",
  "Hunter x Hunter": "Anime",
  "Chainsaw Man": "Anime",
  "Gurren Lagann": "Anime",
  "Seven Deadly Sins": "Anime",
  "Jujutsu Kaisen": "Anime",
  "Death Note": "Anime",
  "Attack on Titan": "Anime",
  "Solo Leveling": "Anime",
  "Black Clover": "Anime",
  "Mob Psycho 100": "Anime",
  "Fire Force": "Anime",
  "Devilman": "Anime",
  "Re:Zero": "Anime",
  "Darling in the FranXX": "Anime",
  "That Time I Got Reincarnated as a Slime": "Anime",
  "Hellsing": "Anime",
  "Misfit of Demon King Academy": "Anime",
  "Code Geass": "Anime",
  "Akira": "Anime",
  "Tokyo Ghoul": "Anime",
  "Yu Yu Hakusho": "Anime",
  "One Punch Man": "Anime",
  "Fist of the North Star": "Anime",
  "Overlord": "Anime",
  "Baki": "Anime",
  "Baki the Grappler": "Anime",
  "Pokémon": "Anime",
  "Fate/Stay Night": "Anime",
  "Boruto": "Anime",
  "Alita": "Anime",
  "Castlevania": "Anime",
  // Games
  "Mortal Kombat": "Games",
  "Street Fighter": "Games",
  "Halo": "Games",
  "League of Legends": "Games",
  "Elden Ring": "Games",
  "Bloodborne": "Games",
  "Nintendo": "Games",
  "NieR: Automata": "Games",
  "Final Fantasy": "Games",
  "Devil May Cry": "Games",
  "Resident Evil": "Games",
  "inFAMOUS": "Games",
  "The Last of Us": "Games",
  "Dead Space": "Games",
  "Red Dead Redemption 2": "Games",
  "God of War": "Games",
  "Bayonetta": "Games",
  "Hades": "Games",
  "Call of Duty": "Games",
  "Prototype": "Games",
  "Diablo": "Games",
  "Metroid": "Games",
  "Capcom": "Games",
  "Sega": "Games",
  "Half-Life": "Games",
  "Uncharted": "Games",
  "Doom": "Games",
  "Ghost of Tsushima": "Games",
  "The Elder Scrolls": "Games",
  "Mass Effect": "Games",
  "The Legend of Zelda": "Games",
  "Metal Gear": "Games",
  "Warcraft": "Games",
  "Tomb Raider": "Games",
  "Asura's Wrath": "Games",
  "Sekiro: Shadows Die Twice": "Games",
  "Horizon": "Games",
  "Assassin's Creed": "Games",
  "Dead by Daylight": "Games",
  "Apex Legends": "Games",
  "Super Mario": "Games",
  "Mario": "Games",
  "Sonic": "Games",
  "Zelda": "Games",
  "Overwatch": "Games",
  // Movies & TV
  "Action Heroes": "Movies & TV",
  "Action Villains": "Movies & TV",
  "Star Wars": "Movies & TV",
  "Films": "Movies & TV",
  "Terminator": "Movies & TV",
  "Alien": "Movies & TV",
  "Predator": "Movies & TV",
  "The Matrix": "Movies & TV",
  "Breaking Bad": "Movies & TV",
  "Vikings": "Movies & TV",
  "The Boys": "Movies & TV",
  "Invincible": "Movies & TV",
  "Kaiju": "Movies & TV",
  "Supernatural": "Movies & TV",
  "Doctor Who": "Movies & TV",
  "Bourne": "Movies & TV",
  "Dirty Harry": "Movies & TV",
  // Fantasy & Books
  "Harry Potter": "Fantasy & Books",
  "Lord of the Rings": "Fantasy & Books",
  "Game of Thrones": "Fantasy & Books",
  "The Witcher": "Fantasy & Books",
  "Cirque Du Freak": "Fantasy & Books",
  "Demonata": "Fantasy & Books",
  "Victorian Fiction": "Fantasy & Books",
  "Journey to the West": "Fantasy & Books",
  "Narnia": "Fantasy & Books",
  // Cartoons
  "Cartoon Network": "Cartoons",
  "TMNT": "Cartoons",
  "Adventure Time": "Cartoons",
  "Avatar: The Last Airbender": "Cartoons",
  "Transformers": "Cartoons",
  "Ben 10": "Cartoons",
  "South Park": "Cartoons",
  "The Powerpuff Girls": "Cartoons",
  "Family Guy": "Cartoons",
  "Futurama": "Cartoons",
  "Rick and Morty": "Cartoons",
  "Johnny Test": "Cartoons",
  "Courage the Cowardly Dog": "Cartoons",
  "Ed, Edd n Eddy": "Cartoons",
  "Samurai Jack": "Cartoons",
  "The Simpsons": "Cartoons",
  "Fairly OddParents": "Cartoons",
  "Danny Phantom": "Cartoons",
  "Detentionaire": "Cartoons",
  "Dexter's Laboratory": "Cartoons",
  "6teen": "Cartoons",
  // Myth & History
  "Mythology": "Myth & History",
  "Historical": "Myth & History",
  "Boxing": "Myth & History",
  "Martial Arts": "Myth & History",
  "Greek Mythology": "Myth & History",
  // Horror
  "Horror": "Horror",
  "Saw": "Horror",
  "The Conjuring": "Horror",
  "Evil Dead": "Horror",
  "Cthulhu Mythos": "Horror",
  "Terrifier": "Horror",
  "Audition": "Horror",
  "The Babadook": "Horror",
  "Barbarian": "Horror",
  "Candyman": "Horror",
  "Hellraiser": "Horror",
  "Child's Play": "Horror",
  "Universal Monsters": "Horror",
  "Wishmaster": "Horror",
  "Doctor Sleep": "Horror",
  "Dracula": "Horror",
  // Comics publishers that don't belong to the Marvel or DC families
  "Image Comics": "Legacy",
  "Full Bleed Studios": "Legacy",
  // Real-world people sit alongside Historical / Boxing / Martial Arts
  "Real World": "Myth & History",
  // App-specific custom characters — genuinely no franchise home
  "Developer Legends": "Other",
  // Power-up / alternate-form variants of canonical characters,
  // grouped together so the main roster stays clean.
  "Variants": "Variants",
};

export function getUniverseCategory(universe: string): UniverseCategory {
  return UNIVERSE_TO_CATEGORY[universe] ?? "Other";
}
